version: 2
updates:
  - package-ecosystem: "npm"
    cooldown:
      default-days: 14
      semver-major-days: 30
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
