dist: xenial

language: node_js
node_js:
  - '17.3.0'

addons:
  chrome: stable

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm run rollup

notifications:
  email: false

deploy:
  provider: npm
  skip_cleanup: true
  email: github@careevolution.com
  api_key: "$REPO_CAREEV_APIKEY"
  on:
    tags: true
    repo: CareEvolution/MyDataHelpsUI
    all_branches: true