import { ReactElement } from "react";
import { DailyDataAvailabilityCheck, DailyDataProvider } from "./query-daily-data";

export enum DailyDataType {
	AppleHealthDistanceWalkingRunning = "AppleHealthDistanceWalkingRunning",
	AppleHealthEstimatedAppleWatchWearTime = "AppleHealthEstimatedAppleWatchWearTime",
	AppleHealthFlightsClimbed = "AppleHealthFlightsClimbed",
	AppleHealthHeartRateRange = "AppleHealthHeartRateRange",
	AppleHealthHrv = "AppleHealthHrv",
	AppleHealthMaxHeartRate = "AppleHealthMaxHeartRate",
	AppleHealthMindfulMinutes = "AppleHealthMindfulMinutes",
	AppleHealthRestingHeartRate = "AppleHealthRestingHeartRate",
	AppleHealthSleepMinutes = "AppleHealthSleepMinutes",
	AppleHealthRemSleepMinutes = "AppleHealthSleepRemMinutes",
	AppleHealthDeepSleepMinutes = "AppleHealthSleepDeepMinutes",
	AppleHealthCoreSleepMinutes = "AppleHealthSleepCoreMinutes",
	AppleHealthInBedMinutes = "AppleHealthInBedMinutes",
	AppleHealthStandMinutes = "AppleHealthStandMinutes",
	AppleHealthSteps = "AppleHealthSteps",
	AppleHealthStepsWhileWearingDevice = "AppleHealthStepsWhileWearingDevice",
	AppleHealthTherapyMinutes = "AppleHealthTherapyMinutes",
	AppleHealthWalkingHeartRateAverage = "AppleHealthWalkingHeartRateAverage",
	AppleHealthActiveEnergyBurned = "AppleHealthActiveEnergyBurned",
	AppleHealthNumberOfAlcoholicBeverages = "AppleHealthNumberOfAlcoholicBeverages",
	FitbitSedentaryMinutes = "FitbitSedentaryMinutes",
	FitbitActiveMinutes = "FitbitActiveMinutes",
	FitbitLightlyActiveMinutes = "FitbitLightlyActiveMinutes",
	FitbitFairlyActiveMinutes = "FitbitFairlyActiveMinutes",
	FitbitVeryActiveMinutes = "FitbitVeryActiveMinutes",
	FitbitBreathingRate = "FitbitBreathingRate",
	FitbitCaloriesBurned = "FitbitCaloriesBurned",
	FitbitRestingCaloriesBurned = "FitbitRestingCaloriesBurned",
	FitbitActiveCaloriesBurned = "FitbitActiveCaloriesBurned",
	FitbitElevatedHeartRateMinutes = "FitbitElevatedHeartRateMinutes",
	FitbitFatBurnHeartRateMinutes = "FitbitFatBurnHeartRateMinutes",
	FitbitCardioHeartRateMinutes = "FitbitCardioHeartRateMinutes",
	FitbitPeakHeartRateMinutes = "FitbitPeakHeartRateMinutes",
	FitbitFloors = "FitbitFloors",
	FitbitHrv = "FitbitHrv",
	FitbitRestingHeartRate = "FitbitRestingHeartRate",
	FitbitSleepMinutes = "FitbitSleepMinutes",
	FitbitLightSleepMinutes = "FitbitLightSleepMinutes",
	FitbitRemSleepMinutes = "FitbitRemSleepMinutes",
	FitbitDeepSleepMinutes = "FitbitDeepSleepMinutes",
	FitbitSpO2 = "FitbitSpO2",
	FitbitSteps = "FitbitSteps",
	FitbitWearMinutes = "FitbitWearMinutes",
	GarminSteps = "GarminSteps",
	GarminDistance = "GarminDistance",
	GarminFloors = "GarminFloors",
	GarminActiveMinutes = "GarminActiveMinutes",
	GarminActiveCalories = "GarminActiveCalories",
	GarminRestingCalories = "GarminRestingCalories",
	GarminTotalCalories = "GarminTotalCalories",
	GarminRestingHeartRate = "GarminRestingHeartRate",
	GarminMinHeartRate = "GarminMinHeartRate",
	GarminMaxHeartRate = "GarminMaxHeartRate",
	GarminAverageHeartRate = "GarminAverageHeartRate",
	GarminMaxStressLevel = "GarminMaxStressLevel",
	GarminAverageStressLevel = "GarminAverageStressLevel",
	GarminTotalStressMinutes = "GarminTotalStressMinutes",
	GarminLowStressMinutes = "GarminLowStressMinutes",
	GarminMediumStressMinutes = "GarminMediumStressMinutes",
	GarminHighStressMinutes = "GarminHighStressMinutes",
	GarminTotalSleepMinutes = "GarminTotalSleepMinutes",
	GarminLightSleepMinutes = "GarminLightSleepMinutes",
	GarminDeepSleepMinutes = "GarminDeepSleepMinutes",
	GarminRemSleepMinutes = "GarminRemSleepMinutes",
	GarminAwakeMinutes = "GarminAwakeMinutes",
	GarminSleepScore = "GarminSleepScore",
	GoogleFitMindfulMinutes = "GoogleFitMindfulMinutes",
	GoogleFitSteps = "GoogleFitSteps",
	GoogleFitTherapyMinutes = "GoogleFitTherapyMinutes",
	GoogleHealthSteps = "GoogleHealthSteps",
	GoogleHealthRestingHeartRate = "GoogleHealthRestingHeartRate",
	GoogleHealthSleepMinutes = "GoogleHealthSleepMinutes",
	GoogleHealthLightSleepMinutes = "GoogleHealthLightSleepMinutes",
	GoogleHealthRemSleepMinutes = "GoogleHealthRemSleepMinutes",
	GoogleHealthDeepSleepMinutes = "GoogleHealthDeepSleepMinutes",
	GoogleHealthCaloriesBurned = "GoogleHealthCaloriesBurned",
	GoogleHealthActiveCaloriesBurned = "GoogleHealthActiveCaloriesBurned",
	GoogleHealthFloors = "GoogleHealthFloors",
	GoogleHealthDistance = "GoogleHealthDistance",
	GoogleHealthSedentaryMinutes = "GoogleHealthSedentaryMinutes",
	GoogleHealthWearMinutes = "GoogleHealthWearMinutes",
	GoogleHealthBreathingRate = "GoogleHealthBreathingRate",
	GoogleHealthHrv = "GoogleHealthHrv",
	GoogleHealthSpO2 = "GoogleHealthSpO2",
	GoogleHealthMaxHeartRate = "GoogleHealthMaxHeartRate",
	GoogleHealthMinHeartRate = "GoogleHealthMinHeartRate",
	GoogleHealthAverageHeartRate = "GoogleHealthAverageHeartRate",
	GoogleHealthLightlyActiveMinutes = "GoogleHealthLightlyActiveMinutes",
	GoogleHealthFairlyActiveMinutes = "GoogleHealthFairlyActiveMinutes",
	GoogleHealthVeryActiveMinutes = "GoogleHealthVeryActiveMinutes",
	GoogleHealthActiveMinutes = "GoogleHealthActiveMinutes",
	GoogleHealthFatBurnHeartRateMinutes = "GoogleHealthFatBurnHeartRateMinutes",
	GoogleHealthCardioHeartRateMinutes = "GoogleHealthCardioHeartRateMinutes",
	GoogleHealthPeakHeartRateMinutes = "GoogleHealthPeakHeartRateMinutes",
	GoogleHealthElevatedHeartRateMinutes = "GoogleHealthElevatedHeartRateMinutes",
	Steps = "Steps",
	StepsWithGoogleFit = "StepsWithGoogleFit",
	ActiveCaloriesBurned = "ActiveCaloriesBurned",
	RestingHeartRate = "RestingHeartRate",
	SleepMinutes = "SleepMinutes",
	MindfulMinutes = "MindfulMinutes",
	TherapyMinutes = "TherapyMinutes",
	AirQuality = "AirQuality",
	HomeAirQuality = "HomeAirQuality",
	WorkAirQuality = "WorkAirQuality",
	HealthConnectRestingHeartRate = "HealthConnectRestingHeartRate",
	HealthConnectTotalSleepMinutes = "HealthConnectTotalSleepMinutes",
	HealthConnectLightSleepMinutes = "HealthConnectLightSleepMinutes",
	HealthConnectRemSleepMinutes = "HealthConnectRemSleepMinutes",
	HealthConnectDeepSleepMinutes = "HealthConnectDeepSleepMinutes",
	HealthConnectSteps = "HealthConnectSteps",
	HealthConnectDistance = "HealthConnectDistance",
	HealthConnectMaxHeartRate = "HealthConnectMaxHeartRate",
	HealthConnectMinHeartRate = "HealthConnectMinHeartRate",
	HealthConnectActiveCaloriesBurned = "HealthConnectActiveCaloriesBurned",
	HealthConnectTotalCaloriesBurned = "HealthConnectTotalCaloriesBurned",
	HealthConnectTherapyMinutes = "HealthConnectTherapyMinutes",
	HealthConnectMindfulMinutes = "HealthConnectMindfulMinutes",
	OuraSteps = "OuraSteps",
	OuraRestingHeartRate = "OuraRestingHeartRate",
	OuraSleepMinutes = "OuraSleepMinutes",
	OuraActiveCaloriesBurned = "OuraActiveCaloriesBurned"
}

export interface DailyDataTypeDefinition {
	dataSource?: "Unified" | "AppleHealth" | "Garmin" | "Fitbit" | "GoogleFit" | "GoogleHealth" | "AirQuality" | "Oura" | "HealthConnect";
	type: string;
	dataProvider: DailyDataProvider;
	availabilityCheck: DailyDataAvailabilityCheck;
	labelKey?: string;
	icon: ReactElement;
	formatter: (value: number) => string;
	yAxisConverter?: (value: number) => number;
	previewDataRange: [number, number];
	requiresV2Api?: boolean;
}