let strings: { [key: string]: string } = {
    "back": "Voltar",
    "done": "Concluído",
    "close": "Fechar",
    "save": "Salvar",
    "add": "Adicionar",
    "edit": "Editar",
    "cancel": "Cancelar",
    "clear": "limpar",
    "settings": "Definições",
    "connect": "Conectar",
    "reconnect": "Reconectar",
    "refresh": "Atualizar",
    "remove": "Remover",
    "help": "Ajuda",
    "view": "Visualizar",
    "health-records": "Registos de Saúde",
    "connect-ehr-title-prefix": "Conectar ",
    "connect-ehr-title-divider": " ou ",
    "connect-ehr-title-providers": "Prestador",
    "connect-ehr-title-health-plans": "Plano de Saúde",
    "connect-ehr-connected": "Estamos a receber os seus dados do EHR!",
    "connect-ehr-needs-attention": "Uma das suas contas necessita de atenção.",
    "connect-ehr-text": "Conecte o seu prestador ou plano de saúde para visualizar os resultados dos seus exames, condições, medicamentos e muito mais.",
    "connect-ehr-text-connected": "Conecte outro prestador para partilhar mais dados ou gerir as suas ligações EHR.",
    "connect-ehr-not-enabled": "A ligação ao EHR não está ativada para este projeto.",
    "search-for-provider": "Pesquisar por Prestador ou Plano de Saúde",
    "request-add": "Solicitação para adicionar",
    "expired-reconnect": "Ligação expirada. Por favor, reconecte.",
    "connect-error-reconnect": "Erro inesperado. Por favor, reconecte.",
    "connected": "Conectado",
    "search": "Pesquisar",
    "connect-fitbit-intro": "Pode partilhar os dados da sua conta Fitbit se tiver uma. Para começar, clique ou toque abaixo para iniciar sessão com as suas credenciais do Fitbit.",
    "connect-fitbit-button": "Conectar Fitbit",
    "received-fitbit-data": "Estamos a receber os seus dados do Fitbit!",
    "connect-garmin-intro": "Pode partilhar os dados da sua conta Garmin se tiver uma. Para começar, clique ou toque abaixo para iniciar sessão com as suas credenciais do Garmin.",
    "connect-garmin-button": "Conectar Garmin",
    "received-garmin-data": "Estamos a receber os seus dados do Garmin!",
    "connect-dexcom-intro": "Pode partilhar os dados da sua conta Dexcom se tiver uma. Para começar, clique ou toque abaixo para iniciar sessão com as suas credenciais do Dexcom.",
    "connect-dexcom-button": "Conectar Dexcom",
    "received-dexcom-data": "Estamos a receber os seus dados do Dexcom!",
    "downloading-data": "A descarregar dados...",
    "downloading-data-menu": "A descarregar Dados",
    "empty-tasks-incomplete": "Nenhuma tarefa pendente para mostrar de momento.",
    "empty-tasks-complete": "As tarefas concluídas serão mostradas aqui.",
    "view-all": "Ver tudo",
    "tasks": "Tarefas",
    "incomplete-tasks": "Tarefas pendentes",
    "completed-tasks": "Tarefas concluídas",
    "overdue": "Em atraso",
    "due-today": "Vence hoje",
    "due-tomorrow": "Vence amanhã",
    "due": "Vencimento",
    "due-in": "Vencimento em",
    "days": "dias",
    "notifications": "Notificações",
    "support": "Suporte",
    "all-notifications": "Todas as Notificações",
    "steps": "Passos",
    "resting-heart-rate": "Frequência cardíaca em repouso",
    "distance-traveled": "Distância percorrida",
    "google-fit-share": "Toque para partilhar dados de atividade física",
    "devices": "Dispositivos",
    "last-sync": "Última sincronização",
    "completed": "Concluído",
    "ehr-intro-search": "Pesquise digitando o nome do seu prestador ou o portal de membros do seu prestador de saúde ou do seu plano de saúde.",
    "external-accounts-title-divider": " / ",
    "external-accounts-title-providers": "Prestadores",
    "external-accounts-title-health-plans": "Planos de Saúde",
    "external-accounts-title-devices": "Dispositivos",
    "external-accounts-error": "Uma das suas contas necessita de atenção",
    "external-accounts-loading": "Os seus dados estão a ser descarregados dos seus planos de saúde e prestadores associados. Por favor, verifique novamente dentro de alguns momentos para visualizar os seus dados.",
    "external-account-authorization-expired": "Autorização expirada",
    "external-account-fetching-data": "A recuperar dados...",
    "external-account-deleting": "A remover...",
    "external-account-last-updated": "Última atualização",
    "external-account-error": "Erro inesperado",
    "external-account-reconnect": "Reconectar",
    "external-account-refresh": "Atualizar",
    "external-account-remove": "Remover",
    "device-data-no-data": "Se conectou o Apple Health, Google Fit, Fitbit ou Garmin, volte mais tarde para ver os seus dados.",
    "no-notifications-received": "Nenhuma notificação recebida",
    "next-button-text": "Próximo",
    "lab-results-title": "Resultados de laboratório",
    "medications-title": "Medicamentos",
    "immunizations-title": "Imunizações",
    "reports-title": "Relatórios",
    "allergies-title": "Alergias",
    "conditions-title": "Condições",
    "procedures-title": "Procedimentos",
    "app-download-title": "Próximo passo: Descarregue a aplicação",
    "app-download-subtitle": "Descarregar a aplicação MyDataHelps torna ainda mais fácil participar do @@PROJECT_NAME@@.",
    "app-download-google-play-link-alt": "Descarregar na Google Play Store",
    "app-download-app-store-link-alt": "Descarregar na App Store da Apple",
    "start": "Iniciar",
    "resume": "Continuar",
    "start-survey": "Iniciar pesquisa",
    "resume-survey": "Continuar pesquisa",
    "30-day-average": "Média de 30 dias",
    "today": "Hoje",
    "yesterday": "Ontem",
    "tap-to-log-today": "Toque aqui para registar os seus sintomas ou tratamentos hoje!",
    "mild": "Leve",
    "moderate": "Moderado",
    "severe": "Grave",
    "severe-shortened": "grav",
    "moderate-shortened": "mod",
    "mild-shortened": "leve",
    "log-todays-symptoms": "Registar os sintomas de hoje",
    "todays-log": "Registo de hoje",
    "symptoms": "Sintomas",
    "treatments": "Tratamentos",
    "symptoms-experiencing-today": "Que sintomas está a sentir hoje?",
    "symptoms-experiencing-previous": "Que sintomas sentia anteriormente?",
    "treatments-experiencing-today": "Que tratamentos realizou hoje?",
    "treatments-experiencing-previous": "Que tratamentos realizou anteriormente?",
    "feeling-overall-today": "Como se sente, no geral, hoje?",
    "feeling-overall-previous": "Como se sentia, no geral, anteriormente?",
    "additional-notes": "Alguma observação adicional?",
    "how-severe-is": "Quão grave é o seu",
    "how-severe-was": "Quão grave era o seu",
    "clear-symptom": "Limpar sintoma",
    "add-notes": "Adicionar notas",
    "notes": "Notas",
    "enter-symptom-name": "Introduza o nome do sintoma",
    "enter-treatment-name": "Introduza o nome do tratamento",
    "severity-tracking-none": "Não monitorizar a gravidade",
    "severity-tracking-3point": "Avaliação: Leve / Moderada / Grave",
    "severity-tracking-10point": "Avaliação de 1 a 10 pontos",
    "muted": "Silenciado",
    "not-muted": "Não Silenciado",
    "delete": "Eliminar",
    "severity": "Gravidade",
    "item-delete-warning": "Aviso: Continuar irá eliminar permanentemente os itens abaixo e todos os dados associados aos seus registos. Se não deseja eliminar esses itens, selecione \"Cancelar\".",
    "unsaved-changes": "Alterações não guardadas",
    "daily-overall-experience": "Experiência geral diária",
    "average": "Média",
    "include-symptoms": "Incluir sintomas",
    "select-symptoms": "Selecionar sintomas",
    "include-treatments": "Incluir tratamentos",
    "select-treatments": "Selecionar tratamentos",
    "download-mydatahelps": "Descarregar o MyDataHelps",
    "connect-devices-title": "Conectar dispositivos",
    "connect-devices-text": "Partilhe os dados dos seus dispositivos vestíveis, aplicações e outros dispositivos.",
    "apple-health-troubleshooting-intro": "Se não aprovou ou desativou o partilhar dos seus dados do Apple Health e gostaria de o ativar, siga estes passos:",
    "apple-health-troubleshooting-li-1": "Abra a aplicação \"Definições\"",
    "apple-health-troubleshooting-li-2": "Selecione \"Privacidade\"",
    "apple-health-troubleshooting-li-3": "Selecione \"Saúde\"",
    "apple-health-troubleshooting-li-4": "Selecione \"MyDataHelps\"",
    "apple-health-troubleshooting-li-5": "Ative as categorias de dados que deseja partilhar",
    "how-to-enable": "Como ativar",
    "new-points-title": "Bem feito!",
    "new-points-text": "Recebeu pontos pelos seguintes itens:",
    "new-points-next-reward-prefix": "Agora precisa de ",
    "new-points-next-reward-suffix": " pontos para desbloquear a sua próxima recompensa.",
    "new-points-done-button-text": "Concluído",
    "systolic-average": "Média sistólica",
    "diastolic-average": "Média diastólica",
    "highest-systolic": "Sistólica mais elevada",
    "lowest-systolic": "Sistólica mais baixa",
    "resource-default-button-text": "Abrir",
    "inbox-message-completed-status": "VISTO",
    "inbox-resource-completed-status": "VISTO",
    "inbox-survey-completed-status": "COMPLETADO",
    "inbox-history-view-title": "Histórico da Caixa de Entrada",
    "inbox-history-view-empty-text": "Não tem itens no histórico da caixa de entrada.",
    "inbox-message-view-related-resources-title": "Relacionado",
    "inbox-view-title": "Caixa de Entrada",
    "inbox-view-empty-text": "Não tem novos itens na sua caixa de entrada.",
    "inbox-view-messages-title": "Mensagens",
    "inbox-view-surveys-title": "Pesquisas",
    "inbox-view-resources-title": "Recursos",
    "inbox-view-recently-completed-title": "Recentes",
    "inbox-view-recently-completed-empty-text": "Não tem itens recentemente concluídos na sua caixa de entrada.",
    "inbox-view-history-button-text": "Ver histórico da caixa de entrada",
    "choose-report-month": "Escolher Mês do Relatório",
    "include-overall-experience": "Incluir experiência geral diária",
    "include-notes": "Incluir Notas",
    "create-report": "Criar Relatório em PDF",
    "reports": "Relatórios",
    "recent-daily-data-bar-chart-subtitle": "Últimos 7 dias",
    "recent-daily-data-bar-chart-no-data": "Sem dados",
    "resource-list-empty-text": "Nenhum recurso encontrado.",
    "asthma-symptom-level-none": "Sem sintomas",
    "asthma-symptom-level-mild": "Sintomas leves",
    "asthma-symptom-level-moderate": "Sintomas moderados",
    "asthma-symptom-level-severe": "Sintomas graves",
    "asthma-symptom-difficulty-breathing": "Dificuldade em respirar",
    "asthma-symptom-wheezing": "Chiado",
    "asthma-symptom-coughing": "Tosse",
    "asthma-symptom-chest-tightness": "Aperto ou pressão no peito",
    "asthma-impact-limit-daily-activity": "Limitar a sua atividade diária",
    "asthma-impact-waking-at-night": "Acordar à noite",
    "asthma-impact-using-rescue-inhaler": "Usar o seu inalador de resgate",
    "asthma-trigger-cold-illness": "Doença fria/viral",
    "asthma-trigger-animal-exposure": "Exposição a animais",
    "asthma-trigger-seasonal-allergens": "Alergénios sazonais/pólen",
    "asthma-trigger-exercise": "Exercício",
    "asthma-trigger-smoke": "Fumaça",
    "asthma-trigger-weather-changes": "Alterações climáticas extremas",
    "asthma-trigger-air-pollution": "Poluição do ar",
    "asthma-trigger-strong-smells": "Cheiros fortes",
    "asthma-trigger-chemicals": "Produtos químicos/produtos de limpeza",
    "asthma-trigger-dust": "Poeira",
    "asthma-trigger-mold": "Mofo",
    "asthma-trigger-dust-mites": "Ácaros",
    "asthma-trigger-rodents": "Roedores",
    "asthma-trigger-cockroaches": "Baratas",
    "asthma-trigger-nsaid": "Anti-inflamatórios não esteroidais/Aspirina",
    "asthma-trigger-beta-blocker": "Betabloqueador",
    "asthma-trigger-heartburn": "Azia",
    "asthma-trigger-red-wine": "Vinho tinto",
    "asthma-trigger-new-foods": "Novos alimentos",
    "asthma-trigger-cooked-without-ventilation": "Cozinhar (sem ventilação)",
    "asthma-trigger-pet-in-bed": "Animal de estimação na sua cama",
    "asthma-trigger-incense-or-candle": "Vela/Incenso",
    "asthma-data-status-out-of-range": "Fora do intervalo",
    "asthma-data-status-in-range": "Dentro do intervalo",
    "asthma-data-status-offline": "Offline",
    "asthma-data-status-establishing": "A estabelecer",
    "asthma-data-status-not-determined": "Linha de base não estabelecida",
    "asthma-data-status-not-found": "Nenhum dado registado",
    "asthma-data-status-not-configured": "Não configurado",
    "asthma-control-calendar-daily-entry-missed": "Entrada diária em falta",
    "asthma-control-calendar-not-logged-yet": "Ainda não registado",
    "asthma-control-calendar-log-entries-symptoms-label": "Sintomas",
    "asthma-control-calendar-log-entries-impacts-label": "Impactos",
    "asthma-control-calendar-log-entries-triggers-label": "Desencadeadores",
    "asthma-control-status-header-multiple-out-of-range-p1": "Múltiplos pontos de dados estão ",
    "asthma-control-status-header-multiple-out-of-range-p2": "fora dos seus níveis normais",
    "asthma-control-status-header-multiple-out-of-range-p3": ". Complete a sua entrada diária.",
    "asthma-control-status-header-abnormal-heart-rate-p1": "A sua frequência cardíaca em repouso está ",
    "asthma-control-status-header-abnormal-heart-rate-p2": "acima do seu nível normal",
    "asthma-control-status-header-abnormal-heart-rate-p3": ". Complete a sua entrada diária.",
    "asthma-control-status-header-abnormal-respiratory-rate-p1": "A sua frequência respiratória está ",
    "asthma-control-status-header-abnormal-respiratory-rate-p2": "acima do seu nível normal",
    "asthma-control-status-header-abnormal-respiratory-rate-p3": ". Complete a sua entrada diária.",
    "asthma-control-status-header-abnormal-steps-p1": "A sua atividade está ",
    "asthma-control-status-header-abnormal-steps-p2": "abaixo dos seus níveis normais",
    "asthma-control-status-header-abnormal-steps-p3": ". Complete a sua entrada diária.",
    "asthma-control-status-header-abnormal-sleep-p1": "As suas perturbações do sono estão ",
    "asthma-control-status-header-abnormal-sleep-p2": "acima do seu nível normal",
    "asthma-control-status-header-abnormal-sleep-p3": ". Complete a sua entrada diária.",
    "asthma-control-status-header-abnormal-blood-oxygen-p1": "O seu nível de oxigénio no sangue está ",
    "asthma-control-status-header-abnormal-blood-oxygen-p2": "abaixo do seu nível normal",
    "asthma-control-status-header-abnormal-blood-oxygen-p3": ". Complete a sua entrada diária.",
    "asthma-control-status-header-abnormal-home-aqi-p1": "O Índice de Qualidade do Ar na sua casa é ",
    "asthma-control-status-header-abnormal-home-aqi-p2": ". Complete a sua entrada diária.",
    "asthma-control-status-header-abnormal-work-aqi-p1": "O Índice de Qualidade do Ar no seu trabalho é ",
    "asthma-control-status-header-abnormal-work-aqi-p2": ". Complete a sua entrada diária.",
    "asthma-control-status-header-no-data": "Adicione uma entrada diária para avaliar o controlo da sua asma.",
    "asthma-control-status-header-no-data-caregiver": "Adicione uma entrada diária para avaliar o controlo da asma de {name}.",
    "asthma-control-status-header-not-determined": "São necessárias mais entradas diárias para avaliar o controlo da sua asma.",
    "asthma-control-status-header-not-determined-caregiver": "São necessárias mais entradas diárias para avaliar o controlo da asma de {name}.",
    "asthma-control-status-header-controlled-p1": "Com base nas suas entradas, a sua asma está ",
    "asthma-control-status-header-controlled-p1-caregiver": "Com base nas entradas, a asma de {name} está ",
    "asthma-control-status-header-controlled-p2": "sob controlo.",
    "asthma-control-status-header-not-controlled-p1": "Com base nas suas entradas, a sua asma está ",
    "asthma-control-status-header-not-controlled-p1-caregiver": "Com base nas entradas, a asma de {name} está ",
    "asthma-control-status-header-not-controlled-p2": "não está sob controlo.",
    "asthma-control-status-header-not-controlled-stat-symptom-days": "Dias de sintomas",
    "asthma-control-status-header-not-controlled-stat-rescue-inhaler": "Inalador de resgate",
    "asthma-control-status-header-not-controlled-stat-limited-activity": "Atividade limitada",
    "asthma-control-status-header-not-controlled-stat-awakenings": "Despertares",
    "asthma-action-plan-manager-title": "Plano de Ação para Asma",
    "asthma-action-plan-manager-instructions": "Guarde uma fotografia do seu plano de ação para asma para fácil referência.",
    "asthma-action-plan-manager-instructions-caregiver": "Guarde uma fotografia do plano de ação para a asma de {name} para fácil referência.",
    "asthma-action-plan-manager-learn-more": "O que é um plano de ação para asma?",
    "asthma-action-plan-manager-edit-button-text": "Editar",
    "asthma-action-plan-manager-not-found-text": "Toque para adicionar uma fotografia",
    "asthma-biometrics-title": "Saúde e Atividade",
    "asthma-biometrics-daytime-resting-heart-rate-label": "FC de Repouso (Dia)",
    "asthma-biometrics-nighttime-resting-heart-rate-label": "FC de Repouso (Noite)",
    "asthma-biometrics-beats-per-minute-units": "BPM",
    "asthma-biometrics-respiratory-rate-label": "Frequência Respiratória",
    "asthma-biometrics-breaths-per-minute-units": "BPM",
    "asthma-biometrics-steps-label": "Passos",
    "asthma-biometrics-daytime-blood-oxygen-level-label": "Saturação de Oxigénio (Dia)",
    "asthma-biometrics-nighttime-blood-oxygen-level-label": "Saturação de Oxigénio (Noite)",
    "asthma-biometrics-percent-units": "%",
    "asthma-biometrics-sleep-disturbances-label": "Distúrbios do Sono",
    "asthma-air-qualities-title": "Qualidade do Ar",
    "asthma-air-qualities-setup-button-text": "+ Configuração",
    "asthma-air-qualities-home-aqi-label": "IAQ (Casa)",
    "asthma-air-qualities-work-aqi-label": "IAQ (Trabalho)",
    "asthma-alert-takeover-notice-instructions": "Tire um momento para registar qualquer sintoma de asma numa entrada diária.",
    "asthma-alert-takeover-notice-add-entry-button-text": "+ Entrada diária",
    "asthma-alert-takeover-notice-not-now-button-text": "Agora não",
    "asthma-log-entry-details-not-editable": "Entrada diária não editável",
    "asthma-log-entry-details-not-logged-yet": "Ainda não registado",
    "asthma-log-entry-details-edit-button-text": "Editar",
    "asthma-log-entry-details-add-button-text": "Inserir",
    "asthma-log-entry-details-symptoms-label": "Sintomas",
    "asthma-log-entry-details-impacts-label": "Impactos",
    "asthma-log-entry-details-triggers-label": "Desencadeadores",
    "asthma-log-entry-details-component-no-data-p1": "Nenhum ",
    "asthma-log-entry-details-component-no-data-p2": " registado",
    "asthma-log-entry-header-today-log-label": "Hoje",
    "asthma-log-entry-header-yesterday-log-label": "Ontem",
    "asthma-log-entry-header-not-logged-yet": "Ainda não registado",
    "asthma-log-entry-header-add-button-text": "Inserir",
    "asthma-activity-view-title": "Atividade",
    "asthma-activity-view-chart-title": "Passos",
    "asthma-activity-view-alert-message": "A sua atividade está abaixo do seu nível normal.",
    "asthma-alert-takeover-message": "Vários pontos de dados estão fora dos seus níveis normais.",
    "asthma-air-quality-view-title": "Qualidade do Ar",
    "asthma-air-quality-view-home-aqi-chart-title": "Qualidade do Ar (Casa)",
    "asthma-air-quality-view-home-aqi-alert-message": "A IAQ da sua casa está insalubre.",
    "asthma-air-quality-view-work-aqi-chart-title": "Qualidade do Ar (Trabalho)",
    "asthma-air-quality-view-work-aqi-alert-message": "A IAQ do seu trabalho está insalubre.",
    "asthma-heart-and-lungs-view-title": "Coração e Pulmões",
    "asthma-heart-and-lungs-view-dhr-chart-title": "Frequência Cardíaca de Repouso (Dia)",
    "asthma-heart-and-lungs-view-dhr-alert-message": "A sua frequência cardíaca em repouso durante o dia está acima do seu nível normal.",
    "asthma-heart-and-lungs-view-nhr-chart-title": "Frequência Cardíaca de Repouso (Noite)",
    "asthma-heart-and-lungs-view-nhr-alert-message": "A sua frequência cardíaca em repouso durante a noite está acima do seu nível normal.",
    "asthma-heart-and-lungs-view-rr-chart-title": "Frequência Respiratória",
    "asthma-heart-and-lungs-view-rr-alert-message": "A sua frequência respiratória está acima do seu nível normal.",
    "asthma-heart-and-lungs-view-dbol-chart-title": "Oxigénio no Sangue (Dia)",
    "asthma-heart-and-lungs-view-dbol-alert-message": "O seu nível de oxigénio no sangue durante o dia está abaixo do seu nível normal.",
    "asthma-heart-and-lungs-view-nbol-chart-title": "Oxigénio no Sangue (Noite)",
    "asthma-heart-and-lungs-view-nbol-alert-message": "O seu nível de oxigénio no sangue durante a noite está abaixo do seu nível normal.",
    "asthma-sleep-view-title": "Sono",
    "asthma-sleep-view-chart-title": "Distúrbios do Sono",
    "asthma-sleep-view-alert-message": "Os seus distúrbios do sono estão acima do seu nível normal.",
    "asthma-log-entry-editor-view-symptom-level-title": "Nível de Sintomas",
    "asthma-log-entry-editor-view-select-one-subtitle": "Selecione um",
    "asthma-log-entry-editor-view-select-all-subtitle": "Selecione todos os que se aplicam",
    "asthma-log-entry-editor-view-symptoms-title": "Sintomas",
    "asthma-log-entry-editor-view-impacts-title": "Impactos",
    "asthma-log-entry-editor-view-triggers-title": "Desencadeadores",
    "asthma-air-quality-description-unhealthy": "Insalubre",
    "asthma-air-quality-description-very-unhealthy": "Muito insalubre",
    "asthma-air-quality-description-hazardous": "Perigoso",
    "asthma-recommended-article-21-title": "Como manter a sua asma sob controlo",
    "asthma-recommended-article-21-subtitle": "Permaneça sem sintomas, seguindo o seu plano de tratamento, compreendendo os gatilhos e reconhecendo precocemente mudanças no controlo.",
    "asthma-recommended-article-22-title": "A sua asma está sob controlo?",
    "asthma-recommended-article-22-subtitle": "4 perguntas para avaliar se a sua asma está sob controlo. Se apresenta sintomas mais de 2 vezes por semana ou se acorda à noite com sintomas de asma, a sua asma não está sob controlo.",
    "asthma-recommended-article-24-title": "Navegar pela Zona de Perigo: Preparação para Crises de Asma",
    "asthma-recommended-article-24-subtitle": "Reconheça sintomas graves, como tosse intensa e falta de ar precoce, e ative o seu plano de ação personalizado para asma, incluindo medicamentos imediatos.",
    "asthma-recommended-article-25-title": "Assumir o controlo da sua asma",
    "asthma-recommended-article-25-subtitle": "Quando a sua asma parece incontrolável, é hora de reavaliar a sua abordagem. Passos a tomar quando a sua asma não está sob controlo.",
    "asthma-recommended-article-32-title": "Quem necessita de medicação de controlo?",
    "asthma-recommended-article-32-subtitle": "Descubra o papel crucial das medicações de controlo na manutenção da asma sob controlo.",
    "asthma-recommended-article-33-title": "Acesso a medicamentos",
    "asthma-recommended-article-33-subtitle": "Quando o custo é uma barreira para os medicamentos, saiba mais sobre medicamentos gratuitos ou de baixo custo. Tomar os medicamentos conforme prescritos é importante para manter o controlo da asma.",
    "asthma-recommended-article-34-title": "Reabastecimento de medicamentos",
    "asthma-recommended-article-34-subtitle": "Mantenha os seus medicamentos para asma em dia com estratégias fáceis de reabastecimento.",
    "asthma-recommended-article-35-title": "Dificuldade em lembrar de tomar os medicamentos",
    "asthma-recommended-article-35-subtitle": "Descubra estratégias simples, mas eficazes, para recordar as suas doses diárias, desde dicas de armazenamento inteligente até à utilização de lembretes em aplicações.",
    "asthma-recommended-article-36-title": "Que inalador usar e quando",
    "asthma-recommended-article-36-subtitle": "Domine a gestão da sua asma: o inalador de resgate atua rapidamente para aliviar os sintomas, enquanto o controlador é preventivo e atua reduzindo a inflamação, sendo geralmente utilizado diariamente.",
    "asthma-recommended-article-37a-title": "Técnica do inalador - MDI",
    "asthma-recommended-article-37a-subtitle": "Dicas para a técnica do inalador de dose medida (MDI). Sem a técnica correta, pode não receber a dose completa.",
    "asthma-recommended-article-37b-title": "Técnica do inalador - DPI",
    "asthma-recommended-article-37b-subtitle": "Dicas para a técnica do inalador de pó seco (DPI). Sem a técnica correta, pode não receber a dose completa.",
    "asthma-recommended-article-37c-title": "Técnica do inalador - SMI",
    "asthma-recommended-article-37c-subtitle": "Dicas para a técnica do inalador de névoa suave (SMI). Sem a técnica correta, pode não receber a dose completa.",
    "asthma-recommended-article-37d-title": "Técnica do inalador - nebulizador",
    "asthma-recommended-article-37d-subtitle": "Dicas para a técnica do nebulizador.",
    "asthma-recommended-article-38-title": "Porque devo tomar o meu controlador?",
    "asthma-recommended-article-38-subtitle": "Compreenda o papel crítico das medicações de controlo e por que estas são a base do seu plano de gestão personalizado.",
    "asthma-recommended-article-39-title": "Efeitos secundários dos medicamentos para asma",
    "asthma-recommended-article-39-subtitle": "Saiba como identificar efeitos secundários comuns e incomuns, e as etapas simples que pode tomar para evitar o efeito secundário comum – candidíase (infecção fúngica na boca).",
    "asthma-recommended-article-39a-title": "Como sei se os meus medicamentos para asma estão a funcionar?",
    "asthma-recommended-article-39a-subtitle": "Os medicamentos de controlo podem levar dias ou semanas a fazer efeito. Registe os seus sintomas diariamente para verificar se há melhoria e, se não houver, consulte o seu médico.",
    "asthma-recommended-article-41-title": "Gatilhos inesperados",
    "asthma-recommended-article-41-subtitle": "Descubra gatilhos inesperados da asma que podem fazer parte do seu dia a dia, desde AINEs (como o ibuprofeno) até o seu copo de vinho. Saber o que procurar pode ajudá-lo a identificar esses gatilhos inesperados.",
    "asthma-recommended-article-42-title": "Asma e alergénios/pólenes sazonais",
    "asthma-recommended-article-42-subtitle": "Navegue pela época do pólen com facilidade: identifique os seus gatilhos específicos de pólen, compreenda os seus padrões sazonais e aprenda como minimizar a exposição.",
    "asthma-recommended-article-43-title": "Asma e qualidade do ar",
    "asthma-recommended-article-43-subtitle": "Compreenda que a má qualidade do ar pode desencadear a asma. Saiba como lidar com dias de elevado AQI e o que significam os níveis de AQI.",
    "asthma-recommended-article-43a-title": "Asma e infeções respiratórias",
    "asthma-recommended-article-43a-subtitle": "Infeções respiratórias são gatilhos comuns da asma. Como preveni-las e o que fazer quando ocorrem.",
    "asthma-recommended-article-43b-title": "Asma e animais",
    "asthma-recommended-article-43b-subtitle": "Animais/animais de estimação podem ser um gatilho para a asma. Saiba como diagnosticar uma alergia a animais/animais de estimação e as etapas para reduzir o impacto.",
    "asthma-recommended-article-43c-title": "Asma e fumaça",
    "asthma-recommended-article-43c-subtitle": "Incêndios florestais e a fumaça do tabaco podem desencadear a asma. Saiba quais medidas pode tomar para reduzir a sua exposição.",
    "asthma-recommended-article-43d-title": "Asma e clima",
    "asthma-recommended-article-43d-subtitle": "Os gatilhos climáticos comuns incluem ar frio, ar quente e húmido, e chuva/tempestades. Explore por que estes fatores podem desencadear a asma.",
    "asthma-recommended-article-43e-title": "Cheiros fortes e produtos químicos/produtos de limpeza",
    "asthma-recommended-article-43e-subtitle": "Descubra que cheiros podem desencadear a sua asma e aspetos a considerar enquanto limpa.",
    "asthma-recommended-article-43f-title": "Asma e poeira/ácaros",
    "asthma-recommended-article-43f-subtitle": "A poeira é um gatilho comum da asma, mas o motivo pelo qual é um gatilho pode surpreendê-lo!",
    "asthma-recommended-article-43g-title": "Asma e mofo",
    "asthma-recommended-article-43g-subtitle": "O mofo necessita de humidade para crescer, sendo geralmente encontrado em locais húmidos ou molhados. Saiba como prevenir o mofo na sua casa.",
    "asthma-recommended-article-43h-title": "Asma e azia",
    "asthma-recommended-article-43h-subtitle": "O que é a azia e qual a sua relação com a asma?",
    "blood-type": "Tipo Sanguíneo",
    "device-data-month-chart-no-data": "Sem dados",
    "device-data-month-chart-daily-average": "Média Diária",
    "term-information-not-found-header": "Nenhuma Informação Encontrada",
    "term-information-not-found-body": "Não foi possível encontrar qualquer informação sobre este tópico",
    "term-information-disclaimer": "<strong>AVISO:</strong> As informações fornecidas não constituem aconselhamento médico. São para ajudar a compreender melhor a sua saúde. Por favor, contacte o seu prestador de cuidados de saúde se tiver dúvidas acerca da sua condição médica.",
    "term-information-view-on-medline": "Ver no MedlinePlus",
    "type": "Tipo",
    "location": "Localização",
    "description": "Descrição",
    "performed-by": "Realizado por",
    "verified-by": "Verificado por",
    "normal-range": "Intervalo normal",
    "more": "Mais",
    "procedure": "Procedimento",
    "procedures": "Procedimentos",
    "lab-report": "Relatório de Laboratório",
    "service-performed": "Serviço Realizado",
    "services-performed": "Serviços Realizados",
    "device-data-month-chart-minutes": "Minutos",
    "device-data-month-chart-sleep": "Sono",
    "air-quality-home": "Qualidade do Ar (Casa)",
    "air-quality-work": "Qualidade do Ar (Trabalho)",
    "sedentary-time": "Tempo sedentário",
    "active-time": "Tempo ativo",
    "lightly-active-time": "Tempo ligeiramente ativo",
    "fairly-active-time": "Tempo moderadamente ativo",
    "very-active-time": "Tempo muito ativo",
    "breathing-rate": "Taxa de Respiração",
    "calories-burned": "Calorias queimadas",
    "elevated-heart-rate-time": "Tempo com frequência cardíaca elevada",
    "fat-burn-heart-rate-time": "Tempo de queima de gordura",
    "cardio-heart-rate-time": "Tempo de Cardio",
    "peak-heart-rate-time": "Tempo de frequência cardíaca máxima",
    "floors-climbed": "Andares subidos",
    "heart-rate-variability": "Variabilidade da frequência cardíaca",
    "sleep-time": "Tempo de sono",
    "light-sleep-time": "Tempo de sono leve",
    "deep-sleep-time": "Tempo de sono profundo",
    "rem-sleep-time": "Tempo de Sono REM",
    "spo2": "SpO2",
    "heart-rate-range": "Intervalo de frequência cardíaca",
    "max-heart-rate": "Frequência cardíaca máxima",
    "core-sleep-time": "Tempo de sono profundo",
    "in-bed-time": "Tempo na cama",
    "stand-time": "Tempo em pé",
    "walking-heart-rate-average": "Média da frequência cardíaca ao caminhar",
    "active-energy-burned": "Energia ativa gasta",
    "number-of-alcoholic-beverages": "Número de bebidas alcoólicas",
    "active-calories": "Calorias ativas",
    "resting-calories": "Calorias em repouso",
    "total-calories": "Calorias totais",
    "min-heart-rate": "Frequência cardíaca mínima",
    "average-heart-rate": "Frequência cardíaca média",
    "max-stress-level": "Nível máximo de stress",
    "average-stress-level": "Nível médio de stress",
    "total-stress-time": "Tempo total de stress",
    "low-stress-time": "Tempo de stress baixo",
    "medium-stress-time": "Tempo de stress médio",
    "high-stress-time": "Tempo de stress elevado",
    "awake-time": "Tempo acordado",
    "sleep-score": "Pontuação do sono",
    "bpm": "bpm",
    "hours-abbreviation": "h",
    "minutes-abbreviation": "m",
    "points-until-next-badge": "{{points}} pontos para a próxima insígnia",
    "fitbit-wear-time": "Tempo de utilização do Fitbit",
    "my-badges": "As minhas insígnias ({{badges}})",
    "new-badge-title": "Bom trabalho!",
    "new-badge-text": "Ganhou uma nova insígnia!",
    "get-badge": "Obter insígnia",
    "glucose-chart-no-data": "Sem leituras de glicose no sangue",
    "glucose-stats-range-label": "Intervalo de glicose no sangue",
    "glucose-stats-avg-label": "Média de glicose no sangue",
    "glucose-stats-steps-label": "Passos",
    "glucose-stats-sleep-label": "Sono",
    "stress-level-title": "Nível geral de stress",
    "stress-level-min-label": "Sem stress",
    "stress-level-max-label": "Extremadamente stressado",
    "meal-type-meal": "Refeição",
    "meal-type-snack": "Lanche",
    "meal-type-drink": "Bebida",
    "meal-log-title": "Registo de refeições",
    "meal-log-no-data": "Nenhuma refeição registada",
    "meal-editor-time-input-label": "Hora",
    "meal-editor-description-input-label": "Descrição",
    "meal-editor-description-optional": "Opcional",
    "meal-editor-duplicate-timestamp-error": "Duas refeições não podem ter o mesmo horário.",
    "meal-editor-add-image": "Adicionar imagem",
    "meal-editor-image-upload-error": "Ocorreu um erro ao carregar a imagem selecionada. Tente novamente, use outra imagem ou remova a imagem para salvar.",
    "glucose-view-title": "Monitorização de glicose",
    "ai-assistant-loading": "A interagir com os seus dados...",
    "ai-assistant-suggestion-avg-weekly-heart-rate": "Qual é a minha frequência cardíaca média da última semana?",
    "ai-assistant-suggestion-highest-heart-rate-week": "Qual foi a minha frequência cardíaca mais elevada esta semana?",
    "ai-assistant-suggestion-graph-daily-steps-21-days": "Crie um gráfico dos meus passos diários dos últimos 21 dias",
    "ai-assistant-suggestion-weekly-workouts-average-month": "Quantos treinos por semana fiz em média este mês?",
    "ai-assistant-suggestion-avg-monthly-blood-pressure": "Qual é a minha pressão arterial média do último mês?",
    "ai-assistant-suggestion-daily-active-minutes-month": "Qual é a minha média diária de minutos ativos este mês?",
    "ai-assistant-suggestion-resting-heart-rate-change-month": "Como mudou a minha frequência cardíaca em repouso no último mês?",
    "ai-assistant-suggestion-stand-ups-yesterday": "Quantas vezes se levantou ontem?",
    "ai-assistant-suggestion-graph-heart-rate-trends-workouts": "Poderia criar um gráfico das tendências da minha frequência cardíaca durante os treinos desta semana?",
    "ai-assistant-suggestion-sleep-7-days": "Como foi o meu sono nos últimos 7 dias?",
    "ai-assistant-suggestion-fall-asleep-time-2-weeks": "A que horas geralmente adormeceu nas últimas 2 semanas?",
    "ai-assistant-suggestion-sleep-quality-change-month": "Como mudou a qualidade do meu sono no último mês?",
    "ai-assistant-suggestion-last-tetanus-vaccine": "Quando tomou a sua última vacina contra o tétano?",
    "ai-assistant-suggestion-last-blood-test-lab-work": "Quando fez o seu último exame de sangue ou teste laboratorial?",
    "ai-assistant-suggestion-abnormal-lab-results": "Tem algum resultado laboratorial anormal?",
    "ai-assistant-suggestion-last-cbc-test": "Quando foi o seu último hemograma completo (CBC)?",
    "ai-assistant-suggestion-glucose-a1c-levels-last-test": "Quais foram os seus níveis de glicose e A1c no seu último teste?",
    "ai-assistant-suggestion-graph-cholesterol-trends": "Pode mostrar-me um gráfico de como os meus níveis de colesterol mudaram ao longo do tempo?",
    "ai-assistant-suggestion-last-metabolic-panel": "Quando foi o seu último painel metabólico?",
    "ai-assistant-suggestion-hemoglobin-levels-trend": "Qual é a tendência dos meus níveis de hemoglobina?",
    "ai-assistant-suggestion-show-files": "Mostre-me os meus ficheiros.",
    "ai-assistant-suggestion-save-graph-to-files": "Guarde o gráfico nos meus ficheiros",
    "mindful-minutes": "Minutos de Atenção Plena",
    "therapy-minutes": "Minutos de Terapia",
    "insight-matrix-no-comparison-data": "Nenhum tipo de dado de comparação configurado.",
    "allergylist-reactions": "Reações",
    "points-abbreviation": "pts",
    "no-data": "Sem dados",
    "no-data-yet": "Ainda não há dados",
    "bp-low": "Baixa",
    "bp-normal": "Normal",
    "bp-elevated": "Elevada",
    "bp-stage1": "Estágio 1",
    "bp-stage2": "Estágio 2",
    "bp-crisis": "Crise",
    "bp-unknown": "Desconhecido",
    "device-not-enabled": "@@DEVICE@@ não está activado para este projeto.",
    "download-pdf-report": "Descarregar Relatório em PDF",
    "connect-to-device": "Conectar ao @@DEVICE@@",
    "symptoms-and-treatments": "Sintomas e Tratamentos",
    "subsequent-evaluation-note": "Nota de avaliação subsequente",
    "summary": "Resumo",
    "device-activity": "Atividade do dispositivo",
    "daily": "Diário",
    "weekly": "Semanal",
    "monthly": "Mensal",
    "bonus": "Bónus",
    "syncing-data": "Sincronização de dados...",
    "health-connect-phr-sync-title": "Sincronizar com o Health Connect",
    "health-connect-phr-sync-prompt": "Escolha os registos de saúde para ler e escrever no Health Connect",
    "setup": "Configurar",
    "air-quality": "Qualidade do Ar"
};

export default strings;