let strings: { [key: string]: string } = {
    "back": "Dib",
    "done": "Dhammee",
    "close": "Xir",
    "save": "Kaydi",
    "add": "Ku dar",
    "edit": "Wax ka beddel",
    "cancel": "Jooji",
    "clear": "Tirtir",
    "settings": "Dejinta",
    "connect": "Ku xir",
    "reconnect": "Dib u xir",
    "setup": "Dejin",
    "refresh": "Cusbooneysii",
    "remove": "Ka saar",
    "help": "Caawimaad",
    "view": "Arag",
    "health-records": "Diiwaannada Caafimaadka",
    "connect-ehr-title-prefix": "Ku xir ",
    "connect-ehr-title-divider": " ama ",
    "connect-ehr-title-providers": "Bixiye",
    "connect-ehr-title-health-plans": "Qorshaha Caafimaadka",
    "connect-ehr-connected": "Waxaan helaynnaa xogtaada EHR!",
    "connect-ehr-needs-attention": "Mid ka mid ah koontadaada ayaa u baahan fiiro gaar ah.",
    "connect-ehr-text": "Ku xir bixiyahaaga ama qorshaha caafimaadka si aad u aragto natiijooyinka shaybaarka, xaaladaha, daawooyinka iyo wax badan.",
    "connect-ehr-text-connected": "Ku xir bixiye kale si aad u wadaagto xog dheeraad ah ama u maamusho xidhiidhada EHR.",
    "connect-ehr-not-enabled": "Xidhiidhka EHR looma oggolayn mashruucan.",
    "search-for-provider": "Raadi Bixiye ama Qorshaha Caafimaadka",
    "request-add": "Codso in lagu daro",
    "expired-reconnect": "Xidhiidhka wuu dhacay. Fadlan dib u xidh.",
    "connect-error-reconnect": "Khalad aan la fileyn. Fadlan dib u xidh.",
    "connected": "Waa la xidhay",
    "search": "Raadi",
    "connect-fitbit-intro": "Waxaad wadaagi kartaa xogta koontadaada Fitbit haddii aad mid leedahay. Si aad u bilowdo, guji ama taabo hoosta si aad ugu gasho aqoonsigaaga Fitbit.",
    "connect-fitbit-button": "Ku xir Fitbit",
    "received-fitbit-data": "Waxaan helaynnaa xogtaada Fitbit!",
    "connect-garmin-intro": "Waxaad wadaagi kartaa xogta koontadaada Garmin haddii aad mid leedahay. Si aad u bilowdo, guji ama taabo hoosta si aad ugu gasho aqoonsigaaga Garmin.",
    "connect-garmin-button": "Ku xir Garmin",
    "received-garmin-data": "Waxaan helaynnaa xogtaada Garmin!",
    "connect-oura-intro": "Waxaad wadaagi kartaa xogta koontadaada Oura haddii aad mid leedahay. Si aad u bilowdo, guji ama taabo hoosta si aad ugu gasho aqoonsigaaga Oura.",
    "connect-oura-button": "Ku xir Oura",
    "received-oura-data": "Waxaan helaynnaa xogtaada Oura!",
    "connect-dexcom-intro": "Waxaad wadaagi kartaa xogta koontadaada Dexcom haddii aad mid leedahay. Si aad u bilowdo, guji ama taabo hoosta si aad ugu gasho aqoonsigaaga Dexcom.",
    "connect-dexcom-button": "Ku xir Dexcom",
    "received-dexcom-data": "Waxaan helaynnaa xogtaada Dexcom!",
    "downloading-data": "Soo dejinaya xogta...",
    "downloading-data-menu": "Soo dejinaya Xogta",
    "empty-tasks-incomplete": "Ma jiraan hawlo furan oo hadda la muujiyo.",
    "empty-tasks-complete": "Hawlaha la dhammeeyay halkan ayaa lagu muujin doonaa.",
    "view-all": "Arag Dhammaan",
    "tasks": "Hawlaha",
    "incomplete-tasks": "Hawlaha aan Dhammayn",
    "completed-tasks": "Hawlaha la Dhammeeyay",
    "overdue": "Waqtigii waa dhacay",
    "due-today": "Maanta waa la bixinayaa",
    "due-tomorrow": "Berri waa la bixinayaa",
    "due": "Waa la bixinayaa",
    "due-in": "Waa la bixinayaa",
    "days": "maalmood",
    "notifications": "Ogeysiisyada",
    "support": "Taageerada",
    "all-notifications": "Dhammaan Ogeysiisyada",
    "steps": "Tallaabooyinka",
    "resting-heart-rate": "Garaaca Wadnaha Nasashada",
    "distance-traveled": "Masaafada la Socdaalay",
    "google-fit-share": "Taabo si aad u wadaagto xogta jirdhiska",
    "devices": "Qalabyada",
    "last-sync": "Markii ugu dambeysay ee la isku xidhay",
    "completed": "Waa la dhammeeyay",
    "ehr-intro-search": "Raadi adiga oo gelin magaca bixiyahaaga ama barta xubnaha ee bixiyahaaga daryeelka caafimaadka ama qorshaha caafimaadka.",
    "external-accounts-title-divider": " / ",
    "external-accounts-title-providers": "Bixiyeyaasha",
    "external-accounts-title-health-plans": "Qorshayaasha Caafimaadka",
    "external-accounts-title-devices": "Qalabyada",
    "external-accounts-error": "Mid ka mid ah koontadaada ayaa u baahan fiiro gaar ah",
    "external-accounts-loading": "Xogtaada hadda waxaa laga soo dejinayaa qorshayaasha caafimaadka iyo bixiyeyaasha aad ku xidhan tahay. Fadlan dib u fiiri daqiiqado yar si aad u aragto xogtaada.",
    "external-account-authorization-expired": "Ogolaanshaha wuu dhacay",
    "external-account-fetching-data": "Soo helaya xogta...",
    "external-account-deleting": "Ka saaraya...",
    "external-account-last-updated": "Markii ugu dambeysay ee la cusbooneysiiyay",
    "external-account-error": "Khalad aan la fileyn",
    "external-account-reconnect": "Dib u xir",
    "external-account-refresh": "Cusbooneysii",
    "external-account-remove": "Ka saar",
    "device-data-no-data": "Haddii aad ku xidhan tahay Apple Health, Google Fit, Fitbit, ama Garmin, dib u fiiri mar dambe si aad u aragto xogtaada.",
    "no-notifications-received": "Ma jiraan ogeysiisyo la helay",
    "next-button-text": "Xiga",
    "lab-results-title": "Natiijooyinka Shaybaarka",
    "medications-title": "Daawooyinka",
    "immunizations-title": "Tallaalada",
    "reports-title": "Warbixinnada",
    "allergies-title": "Xasaasiyada",
    "conditions-title": "Xaaladaha",
    "procedures-title": "Hawlgallada",
    "app-download-title": "Xiga: Soo deji App-ka",
    "app-download-subtitle": "Soo dejinta app-ka MyDataHelps waxay ka dhigeysaa mid ka sii fudud in laga qayb qaato @@PROJECT_NAME@@.",
    "app-download-google-play-link-alt": "Kala deji Google Play Store",
    "app-download-app-store-link-alt": "Kala deji Apple App Store",
    "start": "Bilow",
    "resume": "Sii wad",
    "start-survey": "Bilow Sahanka",
    "resume-survey": "Sii wad Sahanka",
    "30-day-average": "Celceliska 30 Maalmood",
    "today": "Maanta",
    "yesterday": "Shalay",
    "tap-to-log-today": "Halkan taabo si aad u diiwaangeliso astaamahaaga ama daaweyntaada!",
    "mild": "Sahlan",
    "moderate": "Dhexdhexaad",
    "severe": "Daran",
    "severe-shortened": "dar",
    "moderate-shortened": "dhex",
    "mild-shortened": "sahl",
    "log-todays-symptoms": "Diiwaangeli Astaamaha Maanta",
    "todays-log": "Diiwaanka Maanta",
    "symptoms": "Astaamaha",
    "treatments": "Daaweynta",
    "symptoms-experiencing-today": "Astaamahee ayaad dareemeysaa?",
    "symptoms-experiencing-previous": "Astaamahee ayaad dareemeysay?",
    "treatments-experiencing-today": "Daaweyntee ayaad samaysay?",
    "treatments-experiencing-previous": "Daaweyntee ayaad samaysay?",
    "feeling-overall-today": "Sidee ayaad dareemeysaa guud ahaan?",
    "feeling-overall-previous": "Sidee ayaad dareemeysay guud ahaan?",
    "additional-notes": "Faahfaahin dheeraad ah?",
    "how-severe-is": "Intee ayuu u daran yahay",
    "how-severe-was": "Intee ayuu u darnaa",
    "clear-symptom": "Tirtir Astaamaha",
    "add-notes": "Ku dar faahfaahin",
    "notes": "Faahfaahin",
    "enter-symptom-name": "Geli Magaca Astaamaha",
    "enter-treatment-name": "Geli Magaca Daaweynta",
    "severity-tracking-none": "Ha Raadin Darnaan",
    "severity-tracking-3point": "Qiimeynta Sahlan / Dhexdhexaad / Daran",
    "severity-tracking-10point": "Qiimeynta 1 - 10 Dhibcood",
    "muted": "Cod la'aan",
    "not-muted": "Cod leh",
    "delete": "Tirtir",
    "severity": "Darnaan",
    "item-delete-warning": "Digniin: Sii wadista waxay si joogto ah u tirtiri doontaa walxaha hoose iyo dhammaan xogta la xidhiidha ee diiwaannadaada. Haddii aadan rabin inaad tirtirto walxahan, dooro \"Jooji\".",
    "unsaved-changes": "Isbeddelada aan la Keydin",
    "daily-overall-experience": "Waayo-aragnimada Guud ee Maalinlaha ah",
    "average": "Celcelis",
    "include-symptoms": "Ku dar Astaamaha",
    "select-symptoms": "Dooro Astaamaha",
    "include-treatments": "Ku dar Daaweynta",
    "select-treatments": "Dooro Daaweynta",
    "download-mydatahelps": "Soo deji MyDataHelps",
    "connect-devices-title": "Ku xir Qalabyada",
    "connect-devices-text": "Wadaag xogta ka timid qalabyada la xirto, app-yada, iyo qalabyo kale.",
    "apple-health-troubleshooting-intro": "Haddii aadan oggolayn ama aad xidhtay wadaagista xogta Apple Health oo aad rabto inaad awood u yeelato, raac tallaabooyinkan:",
    "apple-health-troubleshooting-li-1": "Fur app-ka \"Settings\"",
    "apple-health-troubleshooting-li-2": "Dooro \"Privacy\"",
    "apple-health-troubleshooting-li-3": "Dooro \"Health\"",
    "apple-health-troubleshooting-li-4": "Dooro \"MyDataHelps\"",
    "apple-health-troubleshooting-li-5": "Awood u yeel qaybaha xogta ee aad rabto inaad wadaagto",
    "how-to-enable": "Sida loo awood u yeelo",
    "new-points-title": "Waa fiican!",
    "new-points-text": "Waxaa lagu siiyay dhibcood waxyaabahan soo socda:",
    "new-points-next-reward-prefix": "Hadda waxaad u baahan tahay ",
    "new-points-next-reward-suffix": " dhibcood si aad u furto abaalmarintaada xigta.",
    "new-points-done-button-text": "Dhammee",
    "systolic-average": "Celceliska Systolic",
    "diastolic-average": "Celceliska Diastolic",
    "highest-systolic": "Systolic ugu Sarreeya",
    "lowest-systolic": "Systolic ugu Hooseeya",
    "resource-default-button-text": "Fur",
    "inbox-message-completed-status": "LA ARKAY",
    "inbox-resource-completed-status": "LA ARKAY",
    "inbox-survey-completed-status": "LA DHAMMEEYAY",
    "inbox-history-view-title": "Taariikhda Sanduuqa Soo galka",
    "inbox-history-view-empty-text": "Ma lihid walxo ku jira taariikhda sanduuqa soo galkaaga.",
    "inbox-message-view-related-resources-title": "La xidhiidha",
    "inbox-view-title": "Sanduuqa Soo galka",
    "inbox-view-empty-text": "Ma lihid walxo cusub oo ku jira sanduuqa soo galkaaga.",
    "inbox-view-messages-title": "Fariimaha",
    "inbox-view-surveys-title": "Sahannada",
    "inbox-view-resources-title": "Ilaha",
    "inbox-view-recently-completed-title": "Dhowaan",
    "inbox-view-recently-completed-empty-text": "Ma lihid walxo dhowaan la dhammeeyay oo ku jira sanduuqa soo galkaaga.",
    "inbox-view-history-button-text": "Arag taariikhda sanduuqa soo galka",
    "choose-report-month": "Dooro Bishii Warbixinta",
    "include-overall-experience": "Ku dar Waayo-aragnimada Guud ee Maalinlaha ah",
    "include-notes": "Ku dar Faahfaahinta",
    "create-report": "Samee Warbixin PDF ah",
    "reports": "Warbixinnada",
    "recent-daily-data-bar-chart-subtitle": "7-kii maalmood ee la soo dhaafay",
    "recent-daily-data-bar-chart-no-data": "Xog Ma Jirto",
    "resource-list-empty-text": "Ma jiraan ilo la helay.",
    "asthma-symptom-level-none": "Ma jiraan astaamo",
    "asthma-symptom-level-mild": "Astaamo sahlan",
    "asthma-symptom-level-moderate": "Astaamo dhexdhexaad ah",
    "asthma-symptom-level-severe": "Astaamo daran",
    "asthma-symptom-difficulty-breathing": "Neefsashada oo adag",
    "asthma-symptom-wheezing": "Hinraag",
    "asthma-symptom-coughing": "Qufac",
    "asthma-symptom-chest-tightness": "Laabta oo cidhiidhi ah ama cadaadis",
    "asthma-impact-limit-daily-activity": "Xaddid hawlgalladaada maalinlaha ah",
    "asthma-impact-waking-at-night": "Habeenkii soo kicid",
    "asthma-impact-using-rescue-inhaler": "Isticmaal inhaler-kaaga badbaadinta",
    "asthma-trigger-cold-illness": "Hargab/cudur fayraska",
    "asthma-trigger-animal-exposure": "U-bannaanaanshaha xayawaanka",
    "asthma-trigger-seasonal-allergens": "Xasaasiyad xilliyeedka/boodhka",
    "asthma-trigger-exercise": "Jimicsi",
    "asthma-trigger-smoke": "Qiiq",
    "asthma-trigger-weather-changes": "Isbeddelada cimilada ee aadka u daran",
    "asthma-trigger-air-pollution": "Wasakhowga hawada",
    "asthma-trigger-strong-smells": "Urta xooggan",
    "asthma-trigger-chemicals": "Kiimikada/agabka nadiifinta",
    "asthma-trigger-dust": "Boodh",
    "asthma-trigger-mold": "Cayayaan",
    "asthma-trigger-dust-mites": "Cayayaanka boodhka",
    "asthma-trigger-rodents": "Jiirka",
    "asthma-trigger-cockroaches": "Baraanbaro",
    "asthma-trigger-nsaid": "NSAID/Aspirin",
    "asthma-trigger-beta-blocker": "Beta blocker",
    "asthma-trigger-heartburn": "Gubasho wadnaha",
    "asthma-trigger-red-wine": "Khamriga cas",
    "asthma-trigger-new-foods": "Cuntooyin cusub",
    "asthma-trigger-cooked-without-ventilation": "Karinta (aan lahayn hawo-mareen)",
    "asthma-trigger-pet-in-bed": "Xayawaan guri oo sariirtaada ku jira",
    "asthma-trigger-incense-or-candle": "Shumac/foox",
    "asthma-data-status-out-of-range": "Ka baxsan xadka",
    "asthma-data-status-in-range": "Xadka gudihiisa",
    "asthma-data-status-offline": "Aan ku xirnayn",
    "asthma-data-status-establishing": "La sameynayo",
    "asthma-data-status-not-determined": "Aasaaska lama xaqiijin",
    "asthma-data-status-not-found": "Ma jirto xog la diiwaan geliyay",
    "asthma-data-status-not-configured": "Lama habeynin",
    "asthma-control-calendar-daily-entry-missed": "Gelitaanka maalinlaha ah waa la seegay",
    "asthma-control-calendar-not-logged-yet": "Weli lama diiwaangelin",
    "asthma-control-calendar-log-entries-symptoms-label": "Astaamaha",
    "asthma-control-calendar-log-entries-impacts-label": "Saamaynta",
    "asthma-control-calendar-log-entries-triggers-label": "Sababaha",
    "asthma-control-status-header-complete-daily-entry": "Dhammaystir gelitaankaaga maalinlaha ah.",
    "asthma-control-status-header-multiple-out-of-range-p1": "Dhowr xog ayaa ",
    "asthma-control-status-header-multiple-out-of-range-p2": "ka baxsan heerkaaga caadiga ah",
    "asthma-control-status-header-abnormal-heart-rate-p1": "Garaaca wadnahaaga nasashada waa ",
    "asthma-control-status-header-abnormal-heart-rate-p2": "ka sarreeyaa heerkaaga caadiga ah",
    "asthma-control-status-header-abnormal-respiratory-rate-p1": "Heerka neefsashadaada waa ",
    "asthma-control-status-header-abnormal-respiratory-rate-p2": "ka sarreeyaa heerkaaga caadiga ah",
    "asthma-control-status-header-abnormal-steps-p1": "Dhaqdhaqaaqaaga waa ",
    "asthma-control-status-header-abnormal-steps-p2": "ka hooseeyaa heerkaaga caadiga ah",
    "asthma-control-status-header-abnormal-sleep-p1": "Carqaladeynta hurdadaada waa ",
    "asthma-control-status-header-abnormal-sleep-p2": "ka sarreeyaa heerkaaga caadiga ah",
    "asthma-control-status-header-abnormal-blood-oxygen-p1": "Heerka ogsajiinta dhiiggaaga waa ",
    "asthma-control-status-header-abnormal-blood-oxygen-p2": "ka hooseeyaa heerkaaga caadiga ah",
    "asthma-control-status-header-abnormal-home-aqi-p1": "Tusaha Tayada Hawada gurigaaga waa ",
    "asthma-control-status-header-abnormal-work-aqi-p1": "Tusaha Tayada Hawada shaqadaada waa ",
    "asthma-control-status-header-no-data": "Ku dar gelitaan maalinle ah si loo qiimeeyo xakamaynta neefta.",
    "asthma-control-status-header-no-data-caregiver": "Ku dar gelitaan maalinle ah si loo qiimeeyo xakamaynta neefta {name}.",
    "asthma-control-status-header-not-determined": "Waxaa loo baahan yahay gelitaanno maalinle ah oo dheeraad ah si loo qiimeeyo xakamaynta neeftaada.",
    "asthma-control-status-header-not-determined-caregiver": "Waxaa loo baahan yahay gelitaanno maalinle ah oo dheeraad ah si loo qiimeeyo xakamaynta neefta {name}.",
    "asthma-control-status-header-controlled": "Iyadoo ku saleysan gelitaannadaada, neeftaada waa |||la xakameeyay|||.",
    "asthma-control-status-header-controlled-caregiver": "Iyadoo ku saleysan gelitaannada, neefta {name} waa |||la xakameeyay|||.",
    "asthma-control-status-header-not-controlled": "Iyadoo ku saleysan gelitaannadaada, neeftaada |||lama xakameyn|||.",
    "asthma-control-status-header-not-controlled-caregiver": "Iyadoo ku saleysan gelitaannada, neefta {name} |||lama xakameyn|||.",
    "asthma-control-status-header-not-controlled-stat-symptom-days": "Maalmaha astaamaha",
    "asthma-control-status-header-not-controlled-stat-rescue-inhaler": "Inhaler-ka badbaadinta",
    "asthma-control-status-header-not-controlled-stat-limited-activity": "Dhaqdhaqaaqa xaddidan",
    "asthma-control-status-header-not-controlled-stat-awakenings": "Soo toosid",
    "asthma-action-plan-manager-title": "Qorshaha Ficilka Neefta",
    "asthma-action-plan-manager-instructions": "Kaydi sawir qorshaha ficilka neeftaada si fudud loogu tixraaco.",
    "asthma-action-plan-manager-instructions-caregiver": "Kaydi sawir qorshaha ficilka neefta {name} si fudud loogu tixraaco.",
    "asthma-action-plan-manager-learn-more": "Waa maxay qorshaha ficilka neefta?",
    "asthma-action-plan-manager-edit-button-text": "Wax ka beddel",
    "asthma-action-plan-manager-not-found-text": "Taabo si aad u darto sawir",
    "asthma-biometrics-title": "Caafimaadka & Dhaqdhaqaaqa",
    "asthma-biometrics-daytime-resting-heart-rate-label": "Garaaca Wadnaha Nasashada (Maalintii)",
    "asthma-biometrics-nighttime-resting-heart-rate-label": "Garaaca Wadnaha Nasashada (Habeenkii)",
    "asthma-biometrics-beats-per-minute-units": "BPM",
    "asthma-biometrics-respiratory-rate-label": "Heerka Neefsashada",
    "asthma-biometrics-breaths-per-minute-units": "BPM",
    "asthma-biometrics-steps-label": "Tallaabooyinka",
    "asthma-biometrics-daytime-blood-oxygen-level-label": "Heerka Ogsajiinta (Maalintii)",
    "asthma-biometrics-nighttime-blood-oxygen-level-label": "Heerka Ogsajiinta (Habeenkii)",
    "asthma-biometrics-percent-units": "%",
    "asthma-biometrics-sleep-disturbances-label": "Carqaladeynta Hurdada",
    "asthma-air-qualities-title": "Tayada Hawada",
    "asthma-air-qualities-setup-button-text": "+ Dejin",
    "asthma-air-qualities-home-aqi-label": "AQI (Guriga)",
    "asthma-air-qualities-work-aqi-label": "AQI (Shaqada)",
    "asthma-alert-takeover-notice-instructions": "Qaado waqti si aad u diiwaangeliso astaamaha neefta ee gelitaanka maalinlaha ah.",
    "asthma-alert-takeover-notice-add-entry-button-text": "+ Gelitaan Maalinle ah",
    "asthma-alert-takeover-notice-not-now-button-text": "Hadda Maya",
    "asthma-log-entry-details-not-editable": "Gelitaanka maalinlaha ah waa la seegay",
    "asthma-log-entry-details-not-logged-yet": "Weli lama diiwaangelin",
    "asthma-log-entry-details-edit-button-text": "Wax ka beddel",
    "asthma-log-entry-details-add-button-text": "Diiwaangeli Gelitaan",
    "asthma-log-entry-details-symptoms-label": "Astaamaha",
    "asthma-log-entry-details-impacts-label": "Saamaynta",
    "asthma-log-entry-details-triggers-label": "Sababaha",
    "asthma-log-entry-details-component-no-data-p1": "Ma jiraan ",
    "asthma-log-entry-details-component-no-data-p2": " la diiwaangeliyay",
    "asthma-log-entry-header-today-log-label": "Maanta",
    "asthma-log-entry-header-yesterday-log-label": "Shalay",
    "asthma-log-entry-header-not-logged-yet": "Weli lama diiwaangelin",
    "asthma-log-entry-header-add-button-text": "Diiwaangeli Gelitaan",
    "asthma-activity-view-title": "Dhaqdhaqaaqa",
    "asthma-activity-view-chart-title": "Tallaabooyinka",
    "asthma-activity-view-alert-message": "Dhaqdhaqaaqaaga waa ka hooseeyaa heerkaaga caadiga ah.",
    "asthma-alert-takeover-message": "Dhowr xog ayaa ka baxsan heerkaaga caadiga ah.",
    "asthma-air-quality-view-title": "Tayada Hawada",
    "asthma-air-quality-view-home-aqi-chart-title": "Tayada Hawada (Guriga)",
    "asthma-air-quality-view-home-aqi-alert-message": "Tayada Hawada gurigaaga ma caafimaad qabo.",
    "asthma-air-quality-view-work-aqi-chart-title": "Tayada Hawada (Shaqada)",
    "asthma-air-quality-view-work-aqi-alert-message": "Tayada Hawada shaqadaada ma caafimaad qabo.",
    "asthma-heart-and-lungs-view-title": "Wadnaha & Sambabada",
    "asthma-heart-and-lungs-view-dhr-chart-title": "Garaaca Wadnaha Nasashada (Maalintii)",
    "asthma-heart-and-lungs-view-dhr-alert-message": "Garaaca wadnahaaga nasashada maalintii waa ka sarreeyaa heerkaaga caadiga ah.",
    "asthma-heart-and-lungs-view-nhr-chart-title": "Garaaca Wadnaha Nasashada (Habeenkii)",
    "asthma-heart-and-lungs-view-nhr-alert-message": "Garaaca wadnahaaga nasashada habeenkii waa ka sarreeyaa heerkaaga caadiga ah.",
    "asthma-heart-and-lungs-view-rr-chart-title": "Heerka Neefsashada",
    "asthma-heart-and-lungs-view-rr-alert-message": "Heerka neefsashadaada waa ka sarreeyaa heerkaaga caadiga ah.",
    "asthma-heart-and-lungs-view-dbol-chart-title": "Ogsajiinta Dhiigga (Maalintii)",
    "asthma-heart-and-lungs-view-dbol-alert-message": "Ogsajiinta dhiiggaaga maalintii waa ka hooseeyaa heerkaaga caadiga ah.",
    "asthma-heart-and-lungs-view-nbol-chart-title": "Ogsajiinta Dhiigga (Habeenkii)",
    "asthma-heart-and-lungs-view-nbol-alert-message": "Ogsajiinta dhiiggaaga habeenkii waa ka hooseeyaa heerkaaga caadiga ah.",
    "asthma-sleep-view-title": "Hurdada",
    "asthma-sleep-view-chart-title": "Carqaladeynta Hurdada",
    "asthma-sleep-view-alert-message": "Carqaladeynta hurdadaada waa ka sarreeyaa heerkaaga caadiga ah.",
    "asthma-log-entry-editor-view-symptom-level-title": "Heerka astaamaha",
    "asthma-log-entry-editor-view-select-one-subtitle": "Dooro mid",
    "asthma-log-entry-editor-view-select-all-subtitle": "Dooro dhammaan kuwa khuseeya",
    "asthma-log-entry-editor-view-symptoms-title": "Astaamaha",
    "asthma-log-entry-editor-view-impacts-title": "Saamaynta",
    "asthma-log-entry-editor-view-triggers-title": "Sababaha",
    "asthma-air-quality-description-unhealthy": "Ma caafimaad qabo",
    "asthma-air-quality-description-very-unhealthy": "Aad uma caafimaad qabo",
    "asthma-air-quality-description-hazardous": "Khatar ah",
    "asthma-recommended-article-21-title": "Sida neeftaada loo xakameeyo",
    "asthma-recommended-article-21-subtitle": "Joog astaamo la'aan adigoo raacaya qorshahaaga daaweynta, fahamaya sababaha, iyo aqoonsiga hore ee isbeddelada xakamaynta.",
    "asthma-recommended-article-22-title": "Neeftaada ma la xakameeyay?",
    "asthma-recommended-article-22-subtitle": "4 su'aalood oo lagu qiimeeyo haddii neeftaada la xakameeyay. Haddii aad dareemayso astaamo in ka badan 2 jeer toddobaadkii ama haddii aad habeenkii ka toosayso astaamaha neefta - neeftaada lama xakameyn.",
    "asthma-recommended-article-24-title": "Ka gudubka Aagga Khatarta ah: Diyaargarowga Kororka Neefta",
    "asthma-recommended-article-24-subtitle": "Aqoonso astaamaha daran sida qufaca daran iyo neefta oo ku dhagta hore, kana faa'iidayso qorshahaaga ficilka neefta ee kuu gaar ah oo ay ku jiraan dawooyinka degdegga ah.",
    "asthma-recommended-article-25-title": "Masuuliyad ka qaadashada neeftaada",
    "asthma-recommended-article-25-subtitle": "Marka neeftaada ay dareento mid aan la maamulin, waa waqtiga dib loogu qiimeeyo habkaaga. Tallaabooyinka la qaado marka neeftaada aan la xakameyn.",
    "asthma-recommended-article-32-title": "Yaa u baahan dawo xakameynta?",
    "asthma-recommended-article-32-subtitle": "Ogaaw doorka muhiimka ah ee dawooyinka xakameynta ee joogteynta neefta oo la xakameeyay.",
    "asthma-recommended-article-33-title": "Helitaanka dawooyinka",
    "asthma-recommended-article-33-subtitle": "Marka kharashku yahay caqabad ku ah dawooyinka, baro dawooyinka bilaashka ah ama qiimaha jaban. Qaadashada dawooyinka sida loo qoray waa muhiim si loo joogteeyo xakamaynta neefta.",
    "asthma-recommended-article-34-title": "Buuxinta dawooyinka",
    "asthma-recommended-article-34-subtitle": "Ku hay dawooyinkaaga neefta xaalad wanaagsan iyada oo la adeegsanayo xeeladaha fudud ee dib u buuxinta.",
    "asthma-recommended-article-35-title": "Dhibaato xasuusashada dawooyinka",
    "asthma-recommended-article-35-subtitle": "Ogaaw xeelado fudud laakiin wax ku ool ah oo aad ku xasuusato qiyaastaada maalinlaha ah, laga bilaabo talooyin kaydinta caqliga leh ilaa adeegsiga xusuusiyeyaasha app-ka.",
    "asthma-recommended-article-36-title": "Inhaler-ka loo isticmaalo goorta",
    "asthma-recommended-article-36-subtitle": "Xakamee maaraynta neeftaada: Inhaler-ka badbaadinta wuxuu si degdeg ah u shaqeeyaa si uu u yareeyo astaamaha halka mid xakameeyaa uu yahay ka hortagga oo uu ku shaqeeyo yaraynta bararka, caadi ahaan iyada oo la qaadanayo maalin kasta.",
    "asthma-recommended-article-37a-title": "Farsamada inhaler-ka - MDI",
    "asthma-recommended-article-37a-subtitle": "Talooyin farsamada inhaler-ka qiyaasta la cabiray (MDI). Farsamada saxda ah la'aanteed, waxaa laga yaabaa inaad qaadato qayb kaliya oo ka mid ah qiyaasta.",
    "asthma-recommended-article-37b-title": "Farsamada inhaler-ka - DPI",
    "asthma-recommended-article-37b-subtitle": "Talooyin farsamada inhaler-ka budada qallalan (DPI). Farsamada saxda ah la'aanteed, waxaa laga yaabaa inaad qaadato qayb kaliya oo ka mid ah qiyaasta.",
    "asthma-recommended-article-37c-title": "Farsamada inhaler-ka - SMI",
    "asthma-recommended-article-37c-subtitle": "Talooyin farsamada inhaler-ka ceeryaanka jilicsan (SMI). Farsamada saxda ah la'aanteed, waxaa laga yaabaa inaad qaadato qayb kaliya oo ka mid ah qiyaasta.",
    "asthma-recommended-article-37d-title": "Farsamada inhaler-ka - nebulizer",
    "asthma-recommended-article-37d-subtitle": "Talooyin farsamada nebulizer-ka.",
    "asthma-recommended-article-38-title": "Maxaan u qaadanayaa daawadayda xakameynta?",
    "asthma-recommended-article-38-subtitle": "Faham doorka muhiimka ah ee dawooyinka xakameynta iyo sababta ay u yihiin tiir dhexaad u ah qorshahaaga maaraynta ee kuu gaarka ah.",
    "asthma-recommended-article-39-title": "Waxyeelada dawooyinka neefta",
    "asthma-recommended-article-39-subtitle": "Baro sida loo aqoonsado waxyeelada caadiga ah iyo kuwa aan caadiga ahayn, iyo tallaabooyinka fudud ee aad qaadi karto si aad uga fogaato waxyeelada caadiga ah - thrush (caabuqa fuudka ee afkaaga).",
    "asthma-recommended-article-39a-title": "Sidee ku ogaanayaa in dawooyinkayga neefta ay shaqeynayaan?",
    "asthma-recommended-article-39a-subtitle": "Dawooyinka xakameynta waxay qaadan karaan maalmo ilaa toddobaadyo si ay u gaadhaan saamaynta buuxda. Raad astaamahaaga maalin kasta si aad u aragto haddii ay jirto horumar iyo haddii aysan jirin, la hadal bixiyahaaga.",
    "asthma-recommended-article-41-title": "Sababaha lama filaanka ah",
    "asthma-recommended-article-41-subtitle": "Ogaaw sababaha neefta ee aan la filayn ee ku dhuumanaya noloshaada maalinlaha ah, laga bilaabo NSAIDs (sida ibuprofen) ilaa koobkaaga khamriga. Ogaanshaha waxa la raadiyo, ayaa kaa caawin kara inaad aqoonsato sababahan lama filaanka ah.",
    "asthma-recommended-article-42-title": "Neefta iyo Xasaasiyadaha Xilliyeedka/Boodhka",
    "asthma-recommended-article-42-subtitle": "Si fudud ugu gudub xilliga boodhka: Aqoonso sababaha boodhka ee kuu gaarka ah, faham qaababkooda xilliyeedka, oo baro sida loo yareeyo u-bannaanaanshaha.",
    "asthma-recommended-article-43-title": "Neefta iyo Tayada Hawada",
    "asthma-recommended-article-43-subtitle": "Faham in tayada hawada oo liita ay keeni karto neefta. Baro sida looga gudbo maalmaha AQI sare iyo waxa ay heerarka AQI ka dhigan yihiin.",
    "asthma-recommended-article-43a-title": "Neefta iyo Caabuqyada Neef-mareenka",
    "asthma-recommended-article-43a-subtitle": "Caabuqyada neef-mareenka waa sababaha caadiga ah ee neefta. Sida looga hortago iyo waxa la sameeyo marka ay dhacaan.",
    "asthma-recommended-article-43b-title": "Neefta iyo Xayawaanka",
    "asthma-recommended-article-43b-subtitle": "Xayawaanka/Xayawaanka guriga waxay noqon karaan sabab u ah neefta. Baro sida loo ogaado xasaasiyadda xayawaan/xayawaan guri iyo tallaabooyinka lagu yaraynayo saameynta.",
    "asthma-recommended-article-43c-title": "Neefta iyo Qiiqa",
    "asthma-recommended-article-43c-subtitle": "Dabka duurjoogta iyo qiiqa tubaakada waxay keeni karaan neefta. Baro tallaabooyinka aad qaadi karto si aad u yarayso u-bannaanaanshahaaga.",
    "asthma-recommended-article-43d-title": "Neefta iyo Cimilada",
    "asthma-recommended-article-43d-subtitle": "Sababaha cimilada ee caadiga ah waa hawada qabow, hawada kulul iyo qoyaanka, iyo roobka/duufaannada. Sahmi sababta ay u keeni karaan neefta.",
    "asthma-recommended-article-43e-title": "Urta Xooggan iyo Kiimikada/Agabka Nadiifinta",
    "asthma-recommended-article-43e-subtitle": "Ogaaw urta laga yaabo inay keento neeftaada iyo waxyaabaha laga fikiro inta lagu jiro nadiifinta.",
    "asthma-recommended-article-43f-title": "Neefta iyo Boodhka/Cayayaanka Boodhka",
    "asthma-recommended-article-43f-subtitle": "Boodhku waa sabab caadi ah oo keenta neefta, laakiin sababta ay u tahay sabab ayaa laga yaabaa inay ku yaab geliso!",
    "asthma-recommended-article-43g-title": "Neefta iyo Cayayaanka",
    "asthma-recommended-article-43g-subtitle": "Cayayaanku wuxuu u baahan yahay qoyaan si uu u koro, sidaas darteed caadi ahaan waxaa laga helaa meelaha qoyan ama qoyan. Baro sida looga hortago cayayaanka gurigaaga.",
    "asthma-recommended-article-43h-title": "Neefta iyo Gubasho wadnaha",
    "asthma-recommended-article-43h-subtitle": "Waa maxay gubasho wadnaha iyo maxay la xidhiidh leedahay neefta?",
    "blood-type": "Nooca Dhiigga",
    "device-data-month-chart-no-data": "Xog Ma Jirto",
    "device-data-month-chart-daily-average": "Celceliska Maalinlaha ah",
    "term-information-not-found-header": "Ma Jirto Macluumaad La Helay",
    "term-information-not-found-body": "Waa la awoodi waayay in la helo wax macluumaad ah oo ku saabsan mawduucan",
    "term-information-disclaimer": "<strong>OGEYSIIS:</strong> Macluumaadka la bixiyay ma ahan talo caafimaad. Waxay tahay inay kaa caawiso inaad si fiican u fahanto caafimaadkaaga. Fadlan la xidhiidh bixiyahaaga daryeelka caafimaadka haddii aad qabtid su'aalo ku saabsan xaaladaada caafimaad.",
    "term-information-view-on-medline": "Ku arag MedlinePlus",
    "type": "Nooc",
    "location": "Goob",
    "description": "Sharaxaad",
    "performed-by": "Fuliyay",
    "verified-by": "Xaqiijiyay",
    "normal-range": "Xadka Caadiga ah",
    "more": "Wax badan",
    "procedure": "Hawlgal",
    "procedures": "Hawlgallada",
    "lab-report": "Warbixinta Shaybaadha",
    "service-performed": "Adeegga la Fuliyay",
    "services-performed": "Adeegyada la Fuliyay",
    "device-data-month-chart-minutes": "Daqiiqado",
    "device-data-month-chart-sleep": "Hurdo",
    "air-quality": "Tayada Hawada",
    "air-quality-home": "Tayada Hawada (Guriga)",
    "air-quality-work": "Tayada Hawada (Shaqada)",
    "sedentary-time": "Waqtiga Fadhiga",
    "active-time": "Waqtiga Firfircoon",
    "lightly-active-time": "Waqtiga Firfircoonida Fudud",
    "fairly-active-time": "Waqtiga Firfircoonida Caddaalad ah",
    "very-active-time": "Waqtiga Aad u Firfircoon",
    "breathing-rate": "Heerka Neefsashada",
    "calories-burned": "Kalooriyo la Gubay",
    "elevated-heart-rate-time": "Waqtiga Garaaca Wadnaha Sare",
    "fat-burn-heart-rate-time": "Waqtiga Gubista Dufanka",
    "cardio-heart-rate-time": "Waqtiga Cardio",
    "peak-heart-rate-time": "Waqtiga Ugu Sarreeya",
    "floors-climbed": "Dabaqa la Fuulay",
    "heart-rate-variability": "Isbeddelka Garaaca Wadnaha",
    "sleep-time": "Waqtiga Hurdada",
    "light-sleep-time": "Waqtiga Hurdada Fudud",
    "deep-sleep-time": "Waqtiga Hurdada Qoto dheer",
    "rem-sleep-time": "Waqtiga Hurdada REM",
    "spo2": "SpO2",
    "heart-rate-range": "Xadka Garaaca Wadnaha",
    "max-heart-rate": "Garaaca Wadnaha Ugu Badan",
    "core-sleep-time": "Waqtiga Hurdada Muhiimka ah",
    "in-bed-time": "Waqtiga Sariirta",
    "stand-time": "Waqtiga Taagnaanshaha",
    "walking-heart-rate-average": "Celceliska Garaaca Wadnaha Socodka",
    "active-energy-burned": "Tamarta Firfircoon ee la Gubay",
    "number-of-alcoholic-beverages": "Tirada Cabbitaannada Khamriga ah",
    "active-calories": "Kalooriyo Firfircoon",
    "resting-calories": "Kalooriyo Nasashada",
    "total-calories": "Wadarta Kalooriyo",
    "min-heart-rate": "Garaaca Wadnaha Ugu Yar",
    "average-heart-rate": "Celceliska Garaaca Wadnaha",
    "max-stress-level": "Heerka Walaaca Ugu Sarreeya",
    "average-stress-level": "Celceliska Heerka Walaaca",
    "total-stress-time": "Wadarta Waqtiga Walaaca",
    "low-stress-time": "Waqtiga Walaaca Hoose",
    "medium-stress-time": "Waqtiga Walaaca Dhexe",
    "high-stress-time": "Waqtiga Walaaca Sare",
    "awake-time": "Waqtiga Soo Jeedka",
    "sleep-score": "Qiimaynta Hurdada",
    "bpm": "bpm",
    "hours-abbreviation": "s",
    "minutes-abbreviation": "d",
    "points-until-next-badge": "{{points}} dhibcood ilaa shaambadda xigta",
    "fitbit-wear-time": "Waqtiga Xidhnida Fitbit",
    "my-badges": "Shaambadahayga ({{badges}})",
    "new-badge-title": "Shaqo wanaagsan!",
    "new-badge-text": "Waxaad heshay shaambad cusub!",
    "get-badge": "Hel Shaambad",
    "glucose-chart-no-data": "Ma jiraan akhriska sonkorowga dhiigga",
    "glucose-stats-range-label": "Xadka Sonkorowga Dhiigga",
    "glucose-stats-avg-label": "Celceliska Sonkorowga Dhiigga",
    "glucose-stats-steps-label": "Tallaabooyinka",
    "glucose-stats-sleep-label": "Hurdada",
    "stress-level-title": "Walaaca Guud",
    "stress-level-min-label": "Walaac Ma Jiro",
    "stress-level-max-label": "Aad u Walaacsan",
    "meal-type-meal": "Cunto",
    "meal-type-snack": "Cunto fudud",
    "meal-type-drink": "Cabbitaan",
    "meal-log-title": "Diiwaanka Cuntada",
    "meal-log-no-data": "Ma jiraan cuntooyinka la diiwaangeliyay",
    "meal-editor-time-input-label": "Waqti",
    "meal-editor-description-input-label": "Sharaxaad",
    "meal-editor-description-optional": "Ikhtiyaari",
    "meal-editor-duplicate-timestamp-error": "Laba cunto ma yeelan karaan isla waqti.",
    "meal-editor-add-image": "Ku dar Sawir",
    "meal-editor-image-upload-error": "Khalad ayaa dhacay inta lagu guda jiray soo gelinta sawirka la doortay. Fadlan isku day mar kale, isticmaal sawir kale, ama ka saar sawirka si aad u kaydsato.",
    "glucose-view-title": "Kormeerka Sonkorowga",
    "ai-assistant-loading": "La falgalaya xogtaada...",
    "ai-assistant-suggestion-avg-weekly-heart-rate": "Waa maxay celceliska garaaca wadnahayga toddobaadkii la soo dhaafay?",
    "ai-assistant-suggestion-highest-heart-rate-week": "Waa maxay garaaca wadnahayga ugu sarreeyay toddobaadkan?",
    "ai-assistant-suggestion-graph-daily-steps-21-days": "Samee jaantuska tallaabooyinkayga maalinlaha ah 21-kii maalmood ee la soo dhaafay",
    "ai-assistant-suggestion-weekly-workouts-average-month": "Imisa jimicsi toddobaadkii ayaan celcelis ahaan sameeyay bishaan?",
    "ai-assistant-suggestion-avg-monthly-blood-pressure": "Waa maxay celceliska cadaadiska dhiiggayga bishii la soo dhaafay?",
    "ai-assistant-suggestion-daily-active-minutes-month": "Waa maxay celceliskayga maalinlaha ah ee daqiiqadaha firfircoon bishaan?",
    "ai-assistant-suggestion-resting-heart-rate-change-month": "Sidee ayuu u isbedelay garaaca wadnahayga nasashada bishii la soo dhaafay?",
    "ai-assistant-suggestion-stand-ups-yesterday": "Intee jeer ayaan istaagay shalay?",
    "ai-assistant-suggestion-graph-heart-rate-trends-workouts": "Ma ii sameeyn kartaa jaantus isbedelka garaaca wadnahayga inta lagu jiro jimicsiga toddobaadkan?",
    "ai-assistant-suggestion-sleep-7-days": "Sidee ayay ahayd hurdadaydu 7-dii maalmood ee la soo dhaafay?",
    "ai-assistant-suggestion-fall-asleep-time-2-weeks": "Waqtigee ayaan caadi ahaan seexday 2-dii toddobaad ee la soo dhaafay?",
    "ai-assistant-suggestion-sleep-quality-change-month": "Sidee ayay u isbedeshay tayada hurdadayda bishii la soo dhaafay?",
    "ai-assistant-suggestion-last-tetanus-vaccine": "Goorma ayaa ahaa tallaalkaygii ugu dambeeyay ee teetanada?",
    "ai-assistant-suggestion-last-blood-test-lab-work": "Goorma ayaa ahaa baadhitaankayga dhiigga ama shaqada shaybaadha ee ugu dambeeyay?",
    "ai-assistant-suggestion-abnormal-lab-results": "Ma leeyahay wax natiijooyinka shaybaadha ah oo aan caadi ahayn?",
    "ai-assistant-suggestion-last-cbc-test": "Goorma ayaa ahaa tirada dhiiggayga dhammaystiran (CBC) ee ugu dambeeyay?",
    "ai-assistant-suggestion-glucose-a1c-levels-last-test": "Waa maxay heerarka sonkorowga iyo A1c ee baadhitaankayga ugu dambeeyay?",
    "ai-assistant-suggestion-graph-cholesterol-trends": "Ma i tusi kartaa jaantus muujinaya sida heerarka kolesteroolkayga u isbedeleen waqti ka dib?",
    "ai-assistant-suggestion-last-metabolic-panel": "Goorma ayaa la sameeyay baadhitaankayga metabolic-ka ee ugu dambeeyay?",
    "ai-assistant-suggestion-hemoglobin-levels-trend": "Waa maxay isbedelka heerarka hemoglobin-kayga?",
    "ai-assistant-suggestion-show-files": "I tus faylashayda.",
    "ai-assistant-suggestion-save-graph-to-files": "Ku kaydi jaantuska faylashayda",
    "mindful-minutes": "Daqiiqadaha Feejignaanta",
    "therapy-minutes": "Daqiiqadaha Daaweynta",
    "insight-matrix-no-comparison-data": "Ma jiraan noocyada xogta isbarbardhigga ee la habeeyay.",
    "allergylist-reactions": "Falcelinta",
    "points-abbreviation": "dhbc",
    "no-data": "Xog Ma Jirto",
    "no-data-yet": "Weli xog ma jirto",
    "bp-low": "Hoose",
    "bp-normal": "Caadi",
    "bp-elevated": "Kor u kacay",
    "bp-stage1": "Heerka 1",
    "bp-stage2": "Heerka 2",
    "bp-crisis": "Xaalad degdeg ah",
    "bp-unknown": "Aan la garanayn",
    "device-not-enabled": "@@DEVICE@@ looma oggolaan mashruucan.",
    "download-pdf-report": "Soo dejiso Warbixinta PDF",
    "connect-to-device": "Ku xidh @@DEVICE@@",
    "symptoms-and-treatments": "Astaamaha & Daaweynta",
    "subsequent-evaluation-note": "Qoraalka qiimaynta xigta",
    "summary": "Khulaasa",
    "device-activity": "Dhaqdhaqaaqa Qalabka",
    "daily": "Maalinle",
    "weekly": "Toddobaadle",
    "monthly": "Bile",
    "bonus": "Dheeraad",
    "syncing-data": "Xogta la isku xidhayo...",
    "health-connect-phr-sync-title": "La xidhiidh Health Connect",
    "health-connect-phr-sync-prompt": "Dooro diiwaannada caafimaadka ee laga akhriyo oo loo qoro Health Connect"
};

export default strings;




