let strings: { [key: string]: string } = {
    "back": "Voltar",
    "done": "Concluído",
    "close": "Fechar",
    "save": "Salvar",
    "add": "Adicionar",
    "edit": "Editar",
    "cancel": "Cancelar",
    "clear": "limpar",
    "settings": "Configurações",
    "connect": "Conectar",
    "reconnect": "Reconectar",
    "refresh": "Atualizar",
    "setup" : "Configuração",
    "remove": "Remover",
    "help": "Ajuda",
    "view": "Visualizar",
    "health-records": "Registros de Saúde",
    "connect-ehr-title-prefix": "Conectar ",
    "connect-ehr-title-divider": " ou ",
    "connect-ehr-title-providers": "Fornecedor",
    "connect-ehr-title-health-plans": "Plano de Saúde",
    "connect-ehr-connected": "Estamos recebendo seus dados do EHR!",
    "connect-ehr-needs-attention": "Uma de suas contas requer atenção.",
    "connect-ehr-text": "Conecte seu provedor ou plano de saúde para visualizar seus resultados de exames, condições, medicamentos e muito mais.",
    "connect-ehr-text-connected": "Conecte outro provedor para compartilhar mais dados ou gerenciar suas conexões de EHR.",
    "connect-ehr-not-enabled": "A vinculação do EHR não está ativada para este projeto.",
    "search-for-provider": "Pesquisar por Fornecedor ou Plano de Saúde",
    "request-add": "Solicitação para adicionar",
    "expired-reconnect": "Conexão expirada. Por favor, reconecte.",
    "connect-error-reconnect": "Erro inesperado. Por favor, reconecte.",
    "connected": "Conectado",
    "search": "Pesquisar",
    "connect-fitbit-intro": "Você pode compartilhar dados de sua conta Fitbit se tiver uma. Para começar, clique ou toque abaixo para fazer login com suas credenciais do Fitbit.",
    "connect-fitbit-button": "Conectar Fitbit",
    "received-fitbit-data": "Estamos recebendo seus dados da Fitbit!",
    "connect-garmin-intro": "Você pode compartilhar dados de sua conta Garmin se tiver uma. Para começar, clique ou toque abaixo para fazer login com suas credenciais do Garmin.",
    "connect-garmin-button": "Conectar Garmin",
    "received-garmin-data": "Estamos recebendo seus dados da Garmin!",
    "connect-oura-intro": "Você pode compartilhar dados de sua conta Oura se tiver uma. Para começar, clique ou toque abaixo para fazer login com suas credenciais do Oura.",
    "connect-oura-button": "Conectar Oura",
    "received-oura-data": "Estamos recebendo seus dados da Oura!",
    "connect-dexcom-intro": "Você pode compartilhar dados de sua conta Dexcom se tiver uma. Para começar, clique ou toque abaixo para fazer login com suas credenciais do Dexcom.",
    "connect-dexcom-button": "Conectar Dexcom",
    "received-dexcom-data": "Estamos recebendo seus dados da Dexcom!",
    "downloading-data": "Baixando dados...",
    "downloading-data-menu": "Baixando Dados",
    "empty-tasks-incomplete": "Nenhuma tarefa em aberto para mostrar no momento.",
    "empty-tasks-complete": "Tarefas concluídas serão mostradas aqui.",
    "view-all": "Ver tudo",
    "tasks": "Tarefas",
    "incomplete-tasks": "Tarefas incompletas",
    "completed-tasks": "Tarefas concluídas",
    "overdue": "Atrasado",
    "due-today": "Vencimento hoje",
    "due-tomorrow": "Vencimento amanhã",
    "due": "Vencimento",
    "due-in": "Vencimento em",
    "days": "dias",
    "notifications": "Notificações",
    "support": "Suporte",
    "all-notifications": "Todas as Notificações",
    "steps": "Passos",
    "resting-heart-rate": "Frequência cardíaca em repouso",
    "distance-traveled": "Distância percorrida",
    "google-fit-share": "Toque para compartilhar dados de condicionamento físico",
    "devices": "Dispositivos",
    "last-sync": "Última sincronização",
    "completed": "Concluído",
    "ehr-intro-search": "Pesquise digitando o nome do seu provedor ou portal de membros do seu provedor de saúde ou plano de saúde.",
    "external-accounts-title-divider": " / ",
    "external-accounts-title-providers": "Provedores",
    "external-accounts-title-health-plans": "Planos de Saúde",
    "external-accounts-title-devices": "Dispositivos",
    "external-accounts-error": "Uma de suas contas requer atenção",
    "external-accounts-loading": "Seus dados estão sendo baixados de seus planos de saúde e provedores vinculados. Por favor, verifique novamente em alguns momentos para visualizar seus dados.",
    "external-account-authorization-expired": "Autorização expirada",
    "external-account-fetching-data": "Recuperando dados...",
    "external-account-deleting": "Removendo...",
    "external-account-last-updated": "Última atualização",
    "external-account-error": "Erro inesperado",
    "external-account-reconnect": "Reconectar",
    "external-account-refresh": "Atualizar",
    "external-account-remove": "Remover",
    "device-data-no-data": "Se você conectou o Apple Health, Google Fit, Fitbit ou Garmin, volte mais tarde para ver seus dados.",
    "no-notifications-received": "Nenhuma notificação recebida",
    "next-button-text": "Próximo",
    "lab-results-title": "Resultados de laboratório",
    "medications-title": "Medicamentos",
    "immunizations-title": "Imunizações",
    "reports-title": "Relatórios",
    "allergies-title": "Alergias",
    "conditions-title": "Condições",
    "procedures-title": "Procedimentos",
    "app-download-title": "Próximo passo: Baixe o aplicativo",
    "app-download-subtitle": "Baixar o aplicativo MyDataHelps torna ainda mais fácil participar do @@PROJECT_NAME@@.",
    "app-download-google-play-link-alt": "Baixar na Google Play Store",
    "app-download-app-store-link-alt": "Baixar na App Store da Apple",
    "start": "Iniciar",
    "resume": "Continuar",
    "start-survey": "Iniciar pesquisa",
    "resume-survey": "Continuar pesquisa",
    "30-day-average": "Média de 30 dias",
    "today": "Hoje",
    "yesterday": "Ontem",
    "tap-to-log-today": "Toque aqui para registrar seus sintomas ou tratamentos hoje!",
    "mild": "Leve",
    "moderate": "Moderado",
    "severe": "Grave",
    "severe-shortened": "grav",
    "moderate-shortened": "mod",
    "mild-shortened": "leve",
    "log-todays-symptoms": "Registrar os sintomas de hoje",
    "todays-log": "Registro de hoje",
    "symptoms": "Sintomas",
    "treatments": "Tratamentos",
    "symptoms-experiencing-today": "Quais sintomas você está sentindo?",
    "symptoms-experiencing-previous": "Quais sintomas você estava sentindo?",
    "treatments-experiencing-today": "Quais tratamentos você realizou?",
    "treatments-experiencing-previous": "Quais tratamentos você realizou?",
    "feeling-overall-today": "Como você se sente no geral hoje?",
    "feeling-overall-previous": "Como você estava se sentindo no geral?",
    "additional-notes": "Alguma observação adicional?",
    "how-severe-is": "Quão grave é o seu",
    "how-severe-was": "Quão grave era o seu",
    "clear-symptom": "Limpar sintoma",
    "add-notes": "Adicionar notas",
    "notes": "Notas",
    "enter-symptom-name": "Digite o nome do sintoma",
    "enter-treatment-name": "Digite o nome do tratamento",
    "severity-tracking-none": "Não rastrear gravidade",
    "severity-tracking-3point": "Avaliação Leve / Moderada / Grave",
    "severity-tracking-10point": "Avaliação de 1 a 10 pontos",
    "muted": "Silenciado",
    "not-muted": "Não Silenciado",
    "delete": "Excluir",
    "severity": "Gravidade",
    "item-delete-warning": "Aviso: Continuar excluirá permanentemente os itens abaixo e todos os dados associados de seus registros. Se você não deseja excluir esses itens, selecione \"Cancelar\".",
    "unsaved-changes": "Alterações não salvas",
    "daily-overall-experience": "Experiência geral diária",
    "average": "Média",
    "include-symptoms": "Incluir sintomas",
    "select-symptoms": "Selecionar sintomas",
    "include-treatments": "Incluir tratamentos",
    "select-treatments": "Selecionar tratamentos",
    "download-mydatahelps": "Baixar MyDataHelps",
    "connect-devices-title": "Conectar dispositivos",
    "connect-devices-text": "Compartilhe dados de seus dispositivos vestíveis, aplicativos e outros dispositivos.",
    "apple-health-troubleshooting-intro": "Se você não aprovou ou desativou o compartilhamento de seus dados do Apple Health e gostaria de ativá-lo, siga estas etapas:",
    "apple-health-troubleshooting-li-1": "Abra o aplicativo \"Ajustes\"",
    "apple-health-troubleshooting-li-2": "Selecione \"Privacidade\"",
    "apple-health-troubleshooting-li-3": "Selecione \"Saúde\"",
    "apple-health-troubleshooting-li-4": "Selecione \"MyDataHelps\"",
    "apple-health-troubleshooting-li-5": "Ative as categorias de dados que deseja compartilhar",
    "how-to-enable": "Como ativar",
    "new-points-title": "Bem feito!",
    "new-points-text": "Você recebeu pontos pelos seguintes itens:",
    "new-points-next-reward-prefix": "Agora você precisa de ",
    "new-points-next-reward-suffix": " pontos para desbloquear sua próxima recompensa.",
    "new-points-done-button-text": "Concluído",
    "systolic-average": "Média sistólica",
    "diastolic-average": "Média diastólica",
    "highest-systolic": "Sistólica mais alta",
    "lowest-systolic": "Sistólica mais baixa",
    "resource-default-button-text": "Abrir",
    "inbox-message-completed-status": "VISTO",
    "inbox-resource-completed-status": "VISTO",
    "inbox-survey-completed-status": "COMPLETADO",
    "inbox-history-view-title": "Histórico da Caixa de Entrada",
    "inbox-history-view-empty-text": "Você não tem itens no histórico da caixa de entrada.",
    "inbox-message-view-related-resources-title": "Relacionado",
    "inbox-view-title": "Caixa de Entrada",
    "inbox-view-empty-text": "Você não tem novos itens na sua caixa de entrada.",
    "inbox-view-messages-title": "Mensagens",
    "inbox-view-surveys-title": "Pesquisas",
    "inbox-view-resources-title": "Recursos",
    "inbox-view-recently-completed-title": "Recente",
    "inbox-view-recently-completed-empty-text": "Você não tem itens recentemente concluídos na sua caixa de entrada.",
    "inbox-view-history-button-text": "Ver histórico da caixa de entrada",
    "choose-report-month": "Escolher Mês do Relatório",
    "include-overall-experience": "Incluir Experiência Geral Diária",
    "include-notes": "Incluir Notas",
    "create-report": "Criar Relatório em PDF",
    "reports": "Relatórios",
    "recent-daily-data-bar-chart-subtitle": "Últimos 7 dias",
    "recent-daily-data-bar-chart-no-data": "Sem Dados",
    "resource-list-empty-text": "Nenhum recurso encontrado.",
    "asthma-symptom-level-none": "Sem sintomas",
    "asthma-symptom-level-mild": "Sintomas leves",
    "asthma-symptom-level-moderate": "Sintomas moderados",
    "asthma-symptom-level-severe": "Sintomas graves",
    "asthma-symptom-difficulty-breathing": "Dificuldade para respirar",
    "asthma-symptom-wheezing": "Chiado",
    "asthma-symptom-coughing": "Tosse",
    "asthma-symptom-chest-tightness": "Aperto ou pressão no peito",
    "asthma-impact-limit-daily-activity": "Limitar sua atividade diária",
    "asthma-impact-waking-at-night": "Acordar à noite",
    "asthma-impact-using-rescue-inhaler": "Usar seu inalador de resgate",
    "asthma-trigger-cold-illness": "Doença fria/viral",
    "asthma-trigger-animal-exposure": "Exposição a animais",
    "asthma-trigger-seasonal-allergens": "Alergenos sazonais/pólen",
    "asthma-trigger-exercise": "Exercício",
    "asthma-trigger-smoke": "Fumaça",
    "asthma-trigger-weather-changes": "Mudanças climáticas extremas",
    "asthma-trigger-air-pollution": "Poluição do ar",
    "asthma-trigger-strong-smells": "Cheiros fortes",
    "asthma-trigger-chemicals": "Produtos químicos/produtos de limpeza",
    "asthma-trigger-dust": "Poeira",
    "asthma-trigger-mold": "Mofo",
    "asthma-trigger-dust-mites": "Ácaros",
    "asthma-trigger-rodents": "Roedores",
    "asthma-trigger-cockroaches": "Baratas",
    "asthma-trigger-nsaid": "Anti-inflamatórios não esteroidais/Aspirina",
    "asthma-trigger-beta-blocker": "Betabloqueador",
    "asthma-trigger-heartburn": "Azia",
    "asthma-trigger-red-wine": "Vinho tinto",
    "asthma-trigger-new-foods": "Alimentos novos",
    "asthma-trigger-cooked-without-ventilation": "Cozinhar (sem ventilação)",
    "asthma-trigger-pet-in-bed": "Animal de estimação na sua cama",
    "asthma-trigger-incense-or-candle": "Vela/Incenso",
    "asthma-data-status-out-of-range": "Fora do alcance",
    "asthma-data-status-in-range": "Dentro do alcance",
    "asthma-data-status-offline": "Offline",
    "asthma-data-status-establishing": "Estabelecendo",
    "asthma-data-status-not-determined": "Linha de base não estabelecida",
    "asthma-data-status-not-found": "Nenhum dado registrado",
    "asthma-data-status-not-configured": "Não configurado",
    "asthma-control-calendar-daily-entry-missed": "Inserção diária perdida",
    "asthma-control-calendar-not-logged-yet": "Ainda não registrado",
    "asthma-control-calendar-log-entries-symptoms-label": "Sintomas",
    "asthma-control-calendar-log-entries-impacts-label": "Impactos",
    "asthma-control-calendar-log-entries-triggers-label": "Desencadeadores",
    "asthma-control-status-header-multiple-out-of-range-p1": "Múltiplos pontos de dados estão ",
    "asthma-control-status-header-multiple-out-of-range-p2": "fora dos seus níveis normais",
    "asthma-control-status-header-multiple-out-of-range-p3": ". Complete sua inserção diária.",
    "asthma-control-status-header-abnormal-heart-rate-p1": "Sua frequência cardíaca de repouso está ",
    "asthma-control-status-header-abnormal-heart-rate-p2": "acima do seu nível normal",
    "asthma-control-status-header-abnormal-heart-rate-p3": ". Complete sua inserção diária.",
    "asthma-control-status-header-abnormal-respiratory-rate-p1": "Sua frequência respiratória está ",
    "asthma-control-status-header-abnormal-respiratory-rate-p2": "acima do seu nível normal",
    "asthma-control-status-header-abnormal-respiratory-rate-p3": ". Complete sua inserção diária.",
    "asthma-control-status-header-abnormal-steps-p1": "Sua atividade está ",
    "asthma-control-status-header-abnormal-steps-p2": "abaixo dos seus níveis normais",
    "asthma-control-status-header-abnormal-steps-p3": ". Complete sua inserção diária.",
    "asthma-control-status-header-abnormal-sleep-p1": "Suas perturbações do sono estão ",
    "asthma-control-status-header-abnormal-sleep-p2": "acima do seu nível normal",
    "asthma-control-status-header-abnormal-sleep-p3": ". Complete sua inserção diária.",
    "asthma-control-status-header-abnormal-blood-oxygen-p1": "Seu nível de oxigênio no sangue está ",
    "asthma-control-status-header-abnormal-blood-oxygen-p2": "abaixo do seu nível normal",
    "asthma-control-status-header-abnormal-blood-oxygen-p3": ". Complete sua inserção diária.",
    "asthma-control-status-header-abnormal-home-aqi-p1": "O Índice de Qualidade do Ar em sua casa é ",
    "asthma-control-status-header-abnormal-home-aqi-p2": ". Complete sua inserção diária.",
    "asthma-control-status-header-abnormal-work-aqi-p1": "O Índice de Qualidade do Ar no seu trabalho é ",
    "asthma-control-status-header-abnormal-work-aqi-p2": ". Complete sua inserção diária.",
    "asthma-control-status-header-no-data": "Adicione uma inserção diária para avaliar o controle da sua asma.",
    "asthma-control-status-header-no-data-caregiver": "Adicione uma entrada diária para avaliar o controle da asma de {name}.",
    "asthma-control-status-header-not-determined": "Mais inserções diárias são necessárias para avaliar o controle da sua asma.",
    "asthma-control-status-header-not-determined-caregiver": "São necessárias mais entradas diárias para avaliar o controle da asma de {name}.",
    "asthma-control-status-header-controlled-p1": "Com base nas suas inserções, sua asma está ",
    "asthma-control-status-header-controlled-p1-caregiver": "Com base nas entradas, a asma de {name} está ",
    "asthma-control-status-header-controlled-p2": "sob controle.",
    "asthma-control-status-header-not-controlled-p1": "Com base nas suas inserções, sua asma está ",
    "asthma-control-status-header-not-controlled-p1-caregiver": "Com base nas entradas, a asma de {name} está ",
    "asthma-control-status-header-not-controlled-p2": "não está sob controle.",
    "asthma-control-status-header-not-controlled-stat-symptom-days": "Dias de sintomas",
    "asthma-control-status-header-not-controlled-stat-rescue-inhaler": "Inalador de resgate",
    "asthma-control-status-header-not-controlled-stat-limited-activity": "Atividade limitada",
    "asthma-control-status-header-not-controlled-stat-awakenings": "Acordares",
    "asthma-action-plan-manager-title": "Plano de Ação para Asma",
    "asthma-action-plan-manager-instructions": "Salve uma foto do seu plano de ação para asma para referência fácil.",
    "asthma-action-plan-manager-instructions-caregiver": "Salve uma foto do plano de ação para a asma de {name} para fácil referência.",
    "asthma-action-plan-manager-learn-more": "O que é um plano de ação para asma?",
    "asthma-action-plan-manager-edit-button-text": "Editar",
    "asthma-action-plan-manager-not-found-text": "Toque para adicionar uma foto",
    "asthma-biometrics-title": "Saúde e Atividade",
    "asthma-biometrics-daytime-resting-heart-rate-label": "FC de Repouso (Dia)",
    "asthma-biometrics-nighttime-resting-heart-rate-label": "FC de Repouso (Noite)",
    "asthma-biometrics-beats-per-minute-units": "BPM",
    "asthma-biometrics-respiratory-rate-label": "Frequência Respiratória",
    "asthma-biometrics-breaths-per-minute-units": "BPM",
    "asthma-biometrics-steps-label": "Passos",
    "asthma-biometrics-daytime-blood-oxygen-level-label": "Saturação de Oxigênio (Dia)",
    "asthma-biometrics-nighttime-blood-oxygen-level-label": "Saturação de Oxigênio (Noite)",
    "asthma-biometrics-percent-units": "%",
    "asthma-biometrics-sleep-disturbances-label": "Distúrbios do Sono",
    "asthma-air-qualities-title": "Qualidade do Ar",
    "asthma-air-qualities-setup-button-text": "+ Configuração",
    "asthma-air-qualities-home-aqi-label": "IAQ (Casa)",
    "asthma-air-qualities-work-aqi-label": "IAQ (Trabalho)",
    "asthma-alert-takeover-notice-instructions": "Tire um momento para registrar qualquer sintoma de asma em uma inserção diária.",
    "asthma-alert-takeover-notice-add-entry-button-text": "+ Inserção Diária",
    "asthma-alert-takeover-notice-not-now-button-text": "Agora não",
    "asthma-log-entry-details-not-editable": "Inserção diária perdida",
    "asthma-log-entry-details-not-logged-yet": "Ainda não registrado",
    "asthma-log-entry-details-edit-button-text": "Editar",
    "asthma-log-entry-details-add-button-text": "Inserir",
    "asthma-log-entry-details-symptoms-label": "Sintomas",
    "asthma-log-entry-details-impacts-label": "Impactos",
    "asthma-log-entry-details-triggers-label": "Desencadeadores",
    "asthma-log-entry-details-component-no-data-p1": "Nenhum ",
    "asthma-log-entry-details-component-no-data-p2": " registrado",
    "asthma-log-entry-header-today-log-label": "Hoje",
    "asthma-log-entry-header-yesterday-log-label": "Ontem",
    "asthma-log-entry-header-not-logged-yet": "Ainda não registrado",
    "asthma-log-entry-header-add-button-text": "Inserir",
    "asthma-activity-view-title": "Atividade",
    "asthma-activity-view-chart-title": "Passos",
    "asthma-activity-view-alert-message": "Sua atividade está abaixo do seu nível normal.",
    "asthma-alert-takeover-message": "Múltiplos pontos de dados estão fora dos seus níveis normais.",
    "asthma-air-quality-view-title": "Qualidade do Ar",
    "asthma-air-quality-view-home-aqi-chart-title": "Qualidade do Ar (Casa)",
    "asthma-air-quality-view-home-aqi-alert-message": "A IAQ da sua casa está insalubre.",
    "asthma-air-quality-view-work-aqi-chart-title": "Qualidade do Ar (Trabalho)",
    "asthma-air-quality-view-work-aqi-alert-message": "A IAQ do seu trabalho está insalubre.",
    "asthma-heart-and-lungs-view-title": "Coração e Pulmões",
    "asthma-heart-and-lungs-view-dhr-chart-title": "Frequência Cardíaca de Repouso (Dia)",
    "asthma-heart-and-lungs-view-dhr-alert-message": "Sua frequência cardíaca de repouso diurna está acima do seu nível normal.",
    "asthma-heart-and-lungs-view-nhr-chart-title": "Frequência Cardíaca de Repouso (Noite)",
    "asthma-heart-and-lungs-view-nhr-alert-message": "Sua frequência cardíaca de repouso noturna está acima do seu nível normal.",
    "asthma-heart-and-lungs-view-rr-chart-title": "Frequência Respiratória",
    "asthma-heart-and-lungs-view-rr-alert-message": "Sua frequência respiratória está acima do seu nível normal.",
    "asthma-heart-and-lungs-view-dbol-chart-title": "Oxigênio no Sangue (Dia)",
    "asthma-heart-and-lungs-view-dbol-alert-message": "Seu nível de oxigênio no sangue diurno está abaixo do seu nível normal.",
    "asthma-heart-and-lungs-view-nbol-chart-title": "Oxigênio no Sangue (Noite)",
    "asthma-heart-and-lungs-view-nbol-alert-message": "Seu nível de oxigênio no sangue noturno está abaixo do seu nível normal.",
    "asthma-sleep-view-title": "Sono",
    "asthma-sleep-view-chart-title": "Distúrbios do Sono",
    "asthma-sleep-view-alert-message": "Seus distúrbios do sono estão acima do seu nível normal.",
    "asthma-log-entry-editor-view-symptom-level-title": "Nível de Sintomas",
    "asthma-log-entry-editor-view-select-one-subtitle": "Selecione um",
    "asthma-log-entry-editor-view-select-all-subtitle": "Selecione todos que se aplicam",
    "asthma-log-entry-editor-view-symptoms-title": "Sintomas",
    "asthma-log-entry-editor-view-impacts-title": "Impactos",
    "asthma-log-entry-editor-view-triggers-title": "Desencadeadores",
    "asthma-air-quality-description-unhealthy": "Insalubre",
    "asthma-air-quality-description-very-unhealthy": "Muito insalubre",
    "asthma-air-quality-description-hazardous": "Perigoso",
    "asthma-recommended-article-21-title": "Como manter sua asma sob controle",
    "asthma-recommended-article-21-subtitle": "Permaneça sem sintomas seguindo seu plano de tratamento, entendendo os gatilhos e reconhecendo precocemente mudanças no controle.",
    "asthma-recommended-article-22-title": "Sua asma está sob controle?",
    "asthma-recommended-article-22-subtitle": "4 perguntas para avaliar se sua asma está sob controle. Se você está experienciando sintomas mais de 2 vezes por semana ou se está acordando à noite com sintomas de asma, sua asma não está sob controle.",
    "asthma-recommended-article-24-title": "Navegando pela Zona de Perigo: Preparação para Crises de Asma",
    "asthma-recommended-article-24-subtitle": "Reconheça sintomas graves como tosse intensa e falta de ar cedo, e ative seu plano de ação personalizado para asma, incluindo medicamentos imediatos.",
    "asthma-recommended-article-25-title": "Assumindo o controle da sua asma",
    "asthma-recommended-article-25-subtitle": "Quando sua asma parece incontrolável, é hora de reavaliar sua abordagem. Passos a serem tomados quando sua asma não está sob controle.",
    "asthma-recommended-article-32-title": "Quem precisa de medicação controladora?",
    "asthma-recommended-article-32-subtitle": "Descubra o papel crucial das medicações controladoras na manutenção da asma sob controle.",
    "asthma-recommended-article-33-title": "Acesso a medicamentos",
    "asthma-recommended-article-33-subtitle": "Quando o custo é uma barreira para os medicamentos, aprenda sobre medicamentos gratuitos ou de baixo custo. Tomar os medicamentos conforme prescrito é importante para manter o controle da asma.",
    "asthma-recommended-article-34-title": "Reabastecimento de medicamentos",
    "asthma-recommended-article-34-subtitle": "Mantenha-se em dia com seus medicamentos para asma com estratégias fáceis de reabastecimento.",
    "asthma-recommended-article-35-title": "Dificuldade em lembrar de tomar os medicamentos",
    "asthma-recommended-article-35-subtitle": "Descubra estratégias simples, mas eficazes, para lembrar suas doses diárias, desde dicas de armazenamento inteligente até o uso de lembretes em aplicativos.",
    "asthma-recommended-article-36-title": "Qual inalador usar quando",
    "asthma-recommended-article-36-subtitle": "Domine o gerenciamento da sua asma: o inalador de resgate age rapidamente para aliviar os sintomas, enquanto o controlador é preventivo e atua reduzindo a inflamação, geralmente sendo tomado diariamente.",
    "asthma-recommended-article-37a-title": "Técnica do inalador - MDI",
    "asthma-recommended-article-37a-subtitle": "Dicas para a técnica do inalador de dose medida (MDI). Sem a técnica correta, você pode estar recebendo apenas parte da dose.",
    "asthma-recommended-article-37b-title": "Técnica do inalador - DPI",
    "asthma-recommended-article-37b-subtitle": "Dicas para a técnica do inalador de pó seco (DPI). Sem a técnica correta, você pode estar recebendo apenas parte da dose.",
    "asthma-recommended-article-37c-title": "Técnica do inalador - SMI",
    "asthma-recommended-article-37c-subtitle": "Dicas para a técnica do inalador de névoa suave (SMI). Sem a técnica correta, você pode estar recebendo apenas parte da dose.",
    "asthma-recommended-article-37d-title": "Técnica do inalador - nebulizador",
    "asthma-recommended-article-37d-subtitle": "Dicas para a técnica do nebulizador.",
    "asthma-recommended-article-38-title": "Por que devo tomar meu controlador?",
    "asthma-recommended-article-38-subtitle": "Entenda o papel crítico das medicações controladoras e por que elas são a base do seu plano de manejo personalizado.",
    "asthma-recommended-article-39-title": "Efeitos colaterais dos medicamentos para asma",
    "asthma-recommended-article-39-subtitle": "Saiba como identificar efeitos colaterais comuns e incomuns, e as etapas simples que você pode tomar para evitar o efeito colateral comum - candidíase (infecção fúngica na boca).",
    "asthma-recommended-article-39a-title": "Como sei se meus medicamentos para asma estão funcionando?",
    "asthma-recommended-article-39a-subtitle": "Medicações controladoras podem levar dias a semanas para alcançar o impacto total. Acompanhe seus sintomas diariamente para ver se há uma melhora e, se não houver, converse com seu médico.",
    "asthma-recommended-article-41-title": "Gatilhos inesperados",
    "asthma-recommended-article-41-subtitle": "Descubra gatilhos inesperados de asma que podem estar no seu dia a dia, desde AINEs (como ibuprofeno) até seu copo de vinho. Saber o que procurar pode ajudá-lo a identificar esses gatilhos inesperados.",
    "asthma-recommended-article-42-title": "Asma e alérgenos/pólenes sazonais",
    "asthma-recommended-article-42-subtitle": "Navegue pelo período de pólen com facilidade: identifique seus gatilhos específicos de pólen, entenda seus padrões sazonais e aprenda como minimizar a exposição.",
    "asthma-recommended-article-43-title": "Asma e qualidade do ar",
    "asthma-recommended-article-43-subtitle": "Entenda que a má qualidade do ar pode desencadear asma. Aprenda como lidar com dias de alto AQI e o que os níveis de AQI significam.",
    "asthma-recommended-article-43a-title": "Asma e infecções respiratórias",
    "asthma-recommended-article-43a-subtitle": "Infecções respiratórias são gatilhos comuns de asma. Como preveni-las e o que fazer quando ocorrem.",
    "asthma-recommended-article-43b-title": "Asma e animais",
    "asthma-recommended-article-43b-subtitle": "Animais/pets podem ser um gatilho para a asma. Saiba como diagnosticar uma alergia a animais/pets e as etapas para reduzir o impacto.",
    "asthma-recommended-article-43c-title": "Asma e fumaça",
    "asthma-recommended-article-43c-subtitle": "Incêndios florestais e fumaça de tabaco podem desencadear asma. Aprenda quais medidas você pode tomar para reduzir sua exposição.",
    "asthma-recommended-article-43d-title": "Asma e clima",
    "asthma-recommended-article-43d-subtitle": "Gatilhos climáticos comuns são ar frio, ar quente e úmido e chuva/tempestades. Explore por que esses fatores podem desencadear asma.",
    "asthma-recommended-article-43e-title": "Cheiros fortes e produtos químicos/produtos de limpeza",
    "asthma-recommended-article-43e-subtitle": "Descubra quais cheiros podem desencadear sua asma e coisas a considerar enquanto limpa.",
    "asthma-recommended-article-43f-title": "Asma e poeira/ácaros",
    "asthma-recommended-article-43f-subtitle": "A poeira é um gatilho comum de asma, mas o motivo pelo qual é um gatilho pode surpreendê-lo!",
    "asthma-recommended-article-43g-title": "Asma e mofo",
    "asthma-recommended-article-43g-subtitle": "O mofo precisa de umidade para crescer, portanto, geralmente é encontrado em locais úmidos ou molhados. Aprenda como prevenir o mofo em sua casa.",
    "asthma-recommended-article-43h-title": "Asma e azia",
    "asthma-recommended-article-43h-subtitle": "O que é azia e qual a sua relação com a asma?",
    "blood-type": "Tipo Sanguíneo",
    "device-data-month-chart-no-data": "Sem Dados",
    "device-data-month-chart-daily-average": "Média Diária",
    "term-information-not-found-header": "Nenhuma Informação Encontrada",
    "term-information-not-found-body": "Não foi possível encontrar nenhuma informação sobre este tópico",
    "term-information-disclaimer": "<strong>AVISO:</strong> As informações fornecidas não são aconselhamento médico. Elas são para ajudá-lo a entender melhor sua saúde. Por favor, contate seu prestador de cuidados de saúde se tiver dúvidas sobre sua condição médica.",
    "term-information-view-on-medline": "Ver no MedlinePlus",
    "type": "Tipo",
    "location": "Localização",
    "description": "Descrição",
    "performed-by": "Realizado por",
    "verified-by": "Verificado por",
    "normal-range": "Faixa normal",
    "more": "Mais",
    "procedure": "Procedimento",
    "procedures": "Procedimentos",
    "lab-report": "Relatório de Laboratório",
    "service-performed": "Serviço Realizado",
    "services-performed": "Serviços Realizados",
    "device-data-month-chart-minutes": "Minutos",
    "device-data-month-chart-sleep": "Sono",
    "air-quality": "Qualidade do Ar",
    "air-quality-home": "Qualidade do Ar (Casa)",
    "air-quality-work": "Qualidade do Ar (Trabalho)",
    "sedentary-time": "Tempo Sedentário",
    "active-time": "Tempo Ativo",
    "lightly-active-time": "Tempo Levemente Ativo",
    "fairly-active-time": "Tempo Moderadamente Ativo",
    "very-active-time": "Tempo Muito Ativo",
    "breathing-rate": "Taxa de Respiração",
    "calories-burned": "Calorias Queimadas",
    "elevated-heart-rate-time": "Tempo com Frequência Cardíaca Elevada",
    "fat-burn-heart-rate-time": "Tempo de Queima de Gordura",
    "cardio-heart-rate-time": "Tempo de Cardio",
    "peak-heart-rate-time": "Tempo de Frequência Cardíaca Máxima",
    "floors-climbed": "Pisos Subidos",
    "heart-rate-variability": "Variabilidade da Frequência Cardíaca",
    "sleep-time": "Tempo de Sono",
    "light-sleep-time": "Tempo de Sono Leve",
    "deep-sleep-time": "Tempo de Sono Profundo",
    "rem-sleep-time": "Tempo de Sono REM",
    "spo2": "SpO2",
    "heart-rate-range": "Faixa de Frequência Cardíaca",
    "max-heart-rate": "Frequência Cardíaca Máxima",
    "core-sleep-time": "Tempo de Sono Profundo",
    "in-bed-time": "Tempo na Cama",
    "stand-time": "Tempo em Pé",
    "walking-heart-rate-average": "Média da Frequência Cardíaca ao Caminhar",
    "active-energy-burned": "Energia Ativa Queimada",
    "number-of-alcoholic-beverages": "Número de bebidas alcoólicas",
    "active-calories": "Calorias Ativas",
    "resting-calories": "Calorias em Repouso",
    "total-calories": "Calorias Totais",
    "min-heart-rate": "Frequência Cardíaca Mínima",
    "average-heart-rate": "Frequência Cardíaca Média",
    "max-stress-level": "Nível Máximo de Estresse",
    "average-stress-level": "Nível Médio de Estresse",
    "total-stress-time": "Tempo Total de Estresse",
    "low-stress-time": "Tempo de Baixo Estresse",
    "medium-stress-time": "Tempo de Estresse Médio",
    "high-stress-time": "Tempo de Alto Estresse",
    "awake-time": "Tempo Acordado",
    "sleep-score": "Pontuação do Sono",
    "bpm": "bpm",
    "hours-abbreviation": "h",
    "minutes-abbreviation": "m",
    "points-until-next-badge": "{{points}} pontos para a próxima badge",
    "fitbit-wear-time": "Tempo de uso do Fitbit",
    "my-badges": "Minhas badges ({{badges}})",
    "new-badge-title": "Bom trabalho!",
    "new-badge-text": "Você ganhou uma nova badge!",
    "get-badge": "Obter badge",
    "glucose-chart-no-data": "Sem leituras de glicose no sangue",
    "glucose-stats-range-label": "Faixa de glicose no sangue",
    "glucose-stats-avg-label": "Média de glicose no sangue",
    "glucose-stats-steps-label": "Passos",
    "glucose-stats-sleep-label": "Sono",
    "stress-level-title": "Nível geral de estresse",
    "stress-level-min-label": "Sem estresse",
    "stress-level-max-label": "Extremamente estressado",
    "meal-type-meal": "Refeição",
    "meal-type-snack": "Lanche",
    "meal-type-drink": "Bebida",
    "meal-log-title": "Registro de refeições",
    "meal-log-no-data": "Nenhuma refeição registrada",
    "meal-editor-time-input-label": "Hora",
    "meal-editor-description-input-label": "Descrição",
    "meal-editor-description-optional": "Opcional",
    "meal-editor-duplicate-timestamp-error": "Duas refeições não podem ter o mesmo horário.",
    "meal-editor-add-image": "Adicionar imagem",
    "meal-editor-image-upload-error": "Ocorreu um erro ao fazer upload da imagem selecionada. Tente novamente, use outra imagem ou remova a imagem para salvar.",
    "glucose-view-title": "Monitoramento de glicose",
    "ai-assistant-loading": "Interagindo com seus dados...",
    "ai-assistant-suggestion-avg-weekly-heart-rate": "Qual é minha frequência cardíaca média da última semana?",
    "ai-assistant-suggestion-highest-heart-rate-week": "Qual foi minha frequência cardíaca mais alta esta semana?",
    "ai-assistant-suggestion-graph-daily-steps-21-days": "Crie um gráfico dos meus passos diários dos últimos 21 dias",
    "ai-assistant-suggestion-weekly-workouts-average-month": "Quantos treinos por semana fiz em média este mês?",
    "ai-assistant-suggestion-avg-monthly-blood-pressure": "Qual é minha pressão arterial média do último mês?",
    "ai-assistant-suggestion-daily-active-minutes-month": "Qual é minha média diária de minutos ativos este mês?",
    "ai-assistant-suggestion-resting-heart-rate-change-month": "Como mudou minha frequência cardíaca em repouso no último mês?",
    "ai-assistant-suggestion-stand-ups-yesterday": "Quantas vezes me levantei ontem?",
    "ai-assistant-suggestion-graph-heart-rate-trends-workouts": "Poderia fazer um gráfico das tendências da minha frequência cardíaca durante os treinos desta semana?",
    "ai-assistant-suggestion-sleep-7-days": "Como foi meu sono nos últimos 7 dias?",
    "ai-assistant-suggestion-fall-asleep-time-2-weeks": "A que horas geralmente adormeci nas últimas 2 semanas?",
    "ai-assistant-suggestion-sleep-quality-change-month": "Como mudou a qualidade do meu sono no último mês?",
    "ai-assistant-suggestion-last-tetanus-vaccine": "Quando tomei minha última vacina contra o tétano?",
    "ai-assistant-suggestion-last-blood-test-lab-work": "Quando fiz meu último exame de sangue ou teste laboratorial?",
    "ai-assistant-suggestion-abnormal-lab-results": "Tenho algum resultado laboratorial anormal?",
    "ai-assistant-suggestion-last-cbc-test": "Quando foi meu último hemograma completo (CBC)?",
    "ai-assistant-suggestion-glucose-a1c-levels-last-test": "Quais foram meus níveis de glicose e A1c no meu último teste?",
    "ai-assistant-suggestion-graph-cholesterol-trends": "Você pode me mostrar um gráfico de como meus níveis de colesterol mudaram ao longo do tempo?",
    "ai-assistant-suggestion-last-metabolic-panel": "Quando foi meu último painel metabólico?",
    "ai-assistant-suggestion-hemoglobin-levels-trend": "Qual é a tendência dos meus níveis de hemoglobina?",
    "ai-assistant-suggestion-show-files": "Mostre-me meus arquivos.",
    "ai-assistant-suggestion-save-graph-to-files": "Salve o gráfico nos meus arquivos",
    "mindful-minutes": "Minutos de Atenção Plena",
    "therapy-minutes": "Minutos de Terapia",
    "insight-matrix-no-comparison-data": "Nenhum tipo de dado de comparação configurado.",
    "allergylist-reactions": "Reações",
    "points-abbreviation": "pts",
    "no-data": "Sem Dados",
    "no-data-yet": "Nenhum dado ainda",
    "bp-low": "Baixa",
    "bp-normal": "Normal",
    "bp-elevated": "Elevada",
    "bp-stage1": "Estágio 1",
    "bp-stage2": "Estágio 2",
    "bp-crisis": "Crise",
    "bp-unknown": "Desconhecido",
    "device-not-enabled": "@@DEVICE@@ não está habilitado para este projeto.",
    "download-pdf-report": "Baixar Relatório em PDF",
    "connect-to-device": "Conectar ao @@DEVICE@@",
    "symptoms-and-treatments": "Sintomas e Tratamentos",
    "subsequent-evaluation-note": "Nota de avaliação subsequente",
    "summary": "Resumo",
    "device-activity": "Atividade do dispositivo",
    "daily": "Diário",
    "weekly": "Semanal",
    "monthly": "Mensal",
    "syncing-data": "Sincronizando dados...",
    "health-connect-phr-sync-title": "Sincronizar com Health Connect",
    "health-connect-phr-sync-prompt": "Escolha os registros de saúde para ler e escrever no Health Connect",
    "bonus": "Bônus"
};

export default strings;