let strings: { [key: string]: string } = {
    "back": "Terug",
    "done": "Klaar",
    "close": "Sluiten",
    "save": "Opslaan",
    "add": "Toevoegen",
    "settings": "Instellingen",
    "connect": "Verbinden",
    "reconnect": "Opnieuw verbinden",
    "refresh": "Vernieuwen",
    "remove": "Verwijderen",
    "help": "Help",
    "view": "Bekijken",
    "health-records": "Medische Dossiers",
    "connect-ehr-title-prefix": "Verbinden met ",
    "connect-ehr-title-divider": " of ",
    "connect-ehr-title-providers": "Provider",
    "connect-ehr-title-health-plans": "Zorgverzekering",
    "connect-ehr-connected": "We ontvangen uw EHR-gegevens!",
    "connect-ehr-needs-attention": "Eén van uw accounts heeft aandacht nodig.",
    "connect-ehr-text": "Uw elektronische medische dossiers zijn een belangrijke bron van informatie. Ze kunnen onderzoekers helpen nieuwe ontdekkingen te doen. Verbind uw provider of zorgverzekering (bijv. Medicare) met @@PROJECT_NAME@@.",
    "connect-ehr-text-connected": "Bedankt voor het delen van uw EHR-gegevens met @@PROJECT_NAME@@. Verbind een andere provider om meer gegevens te delen of beheer uw EHR-verbindingen.",
    "connect-ehr-not-enabled": "EHR-koppeling is niet ingeschakeld voor dit project.",
    "search-for-provider": "Zoek naar Provider of Zorgverzekering",
    "expired-reconnect": "Verbinding verlopen. Maak opnieuw verbinding a.u.b.",
    "connect-error-reconnect": "Onverwachte fout. Maak opnieuw verbinding a.u.b.",
    "connected": "Verbonden",
    "search": "Zoeken",
    "connect-fitbit-intro": "U kunt gegevens delen vanuit uw Fitbit-account als u er een heeft. Klik hieronder om in te loggen met uw Fitbit-inloggegevens.",
    "connect-fitbit-button": "Verbind met Fitbit",
    "received-fitbit-data": "We ontvangen uw Fitbit-gegevens!",
    "connect-garmin-intro": "U kunt gegevens delen vanuit uw Garmin-account als u er een heeft. Klik hieronder om in te loggen met uw Garmin-inloggegevens.",
    "connect-garmin-button": "Verbind met Garmin",
    "received-garmin-data": "We ontvangen uw Garmin-gegevens!",
    "downloading-data": "Gegevens downloaden...",
    "downloading-data-menu": "Gegevens downloaden",
    "all-tasks-complete": "Alle taken voltooid!",
    "view-all": "Alles bekijken",
    "tasks": "Taken",
    "incomplete-tasks": "Onvoltooide taken",
    "completed-tasks": "Voltooide taken",
    "overdue": "Te laat",
    "due-today": "Vandaag vervallen",
    "due-tomorrow": "Morgen vervallen",
    "due": "Vervallen",
    "due-in": "Vervalt over",
    "days": "dagen",
    "notifications": "Meldingen",
    "support": "Ondersteuning",
    "all-notifications": "Alle meldingen",
    "steps": "Stappen",
    "resting-heart-rate": "Rusthartslag",
    "distance-traveled": "Afstand afgelegd",
    "google-fit-share": "Tik om fitnessgegevens te delen",
    "devices": "Apparaten",
    "last-sync": "Laatst gesynchroniseerd",
    "completed": "Voltooid",
    "ehr-intro": "Uw elektronische medische dossiers (EHR) zijn een belangrijke informatiebron. Als u ons helpt uw EHR te verzamelen, zullen onderzoekers deze gegevens gebruiken om ontdekkingen te doen.",
    "external-accounts-title-divider": " / ",
    "external-accounts-title-providers": "Providers",
    "external-accounts-title-health-plans": "Zorgverzekeringen",
    "external-accounts-title-devices": "Apparaten",
    "external-accounts-error": "Eén van uw accounts vereist aandacht",
    "external-accounts-loading": "Uw gegevens worden momenteel gedownload van uw gekoppelde zorgverzekeringen en providers. Controleer over een paar momenten opnieuw om uw gegevens te bekijken.",
    "external-account-authorization-expired": "Autorisatie verlopen",
    "external-account-fetching-data": "Gegevens ophalen...",
    "external-account-deleting": "Verwijderen...",
    "external-account-last-updated": "Laatst bijgewerkt",
    "external-account-error": "Onverwachte fout",
    "external-account-reconnect": "Opnieuw verbinden",
    "external-account-refresh": "Vernieuwen",
    "external-account-remove": "Verwijderen",
    "device-data-no-data": "Als u Apple Health, Google Fit, Fitbit of Garmin hebt aangesloten, kom dan later terug om uw gegevens te bekijken.",
    "no-notifications-received": "Geen meldingen ontvangen",
    "next-button-text": "Volgende",
    "lab-results-title": "Laboratoriumresultaten",
    "medications-title": "Medicijnen",
    "immunizations-title": "Immunisaties",
    "reports-title": "Rapporten",
    "allergies-title": "Allergieën",
    "conditions-title": "Aandoeningen",
    "procedures-title": "Procedures",
    "app-download-title": "Volgende: Download de App",
    "app-download-subtitle": "Het downloaden van de MyDataHelps-app maakt het nog eenvoudiger om deel te nemen aan @@PROJECT_NAME@@.",
    "app-download-google-play-link-alt": "Downloaden via Google Play Store",
    "app-download-app-store-link-alt": "Downloaden via Apple App Store",
    "start": "Start",
    "resume": "Hervat",
    "start-survey": "Start enquête",
    "resume-survey": "Enquête hervatten",
    "30-day-average": "Gemiddelde van 30 dagen",
    "today": "Vandaag",
    "yesterday": "Gisteren",
    "tap-to-log-today": "Tik hier om uw symptomen of behandelingen te registreren!",
    "mild": "Mild",
    "moderate": "Matig",
    "severe": "Ernstig",
    "severe-shortened": "ernstig",
    "moderate-shortened": "matig",
    "mild-shortened": "mild",
    "log-todays-symptoms": "Registreer de symptomen van vandaag",
    "todays-log": "Logboek van vandaag",
    "symptoms": "Symptomen",
    "treatments": "Behandelingen",
    "symptoms-experiencing-today": "Welke symptomen ervaart u vandaag?",
    "symptoms-experiencing-previous": "Welke symptomen ervaarde u?",
    "treatments-experiencing-today": "Welke behandelingen heeft u uitgevoerd?",
    "treatments-experiencing-previous": "Welke behandelingen heeft u uitgevoerd?",
    "feeling-overall-today": "Hoe voelt u zich over het algemeen vandaag?",
    "feeling-overall-previous": "Hoe voelde u zich over het algemeen?",
    "additional-notes": "Eventuele aanvullende opmerkingen?",
    "how-severe-is": "Hoe ernstig is uw",
    "how-severe-was": "Hoe ernstig was uw",
    "clear-symptom": "Symptoom wissen",
    "add-notes": "Notities toevoegen",
    "notes": "Notities",
    "enter-symptom-name": "Voer symptoomnaam in",
    "enter-treatment-name": "Voer behandelingsnaam in",
    "severity-tracking-none": "Geen ernstregistratie",
    "severity-tracking-3point": "Milde / Matige / Ernstige beoordeling",
    "severity-tracking-10point": "1 - 10 Puntbeoordeling",
    "muted": "Gedempt",
    "not-muted": "Niet gedempt",
    "delete": "Verwijderen",
    "severity": "Ernst",
    "item-delete-warning": "Waarschuwing: Als u doorgaat, worden de onderstaande items permanent verwijderd, samen met alle bijbehorende gegevens uit uw logboeken. Als u deze items niet wilt verwijderen, selecteer dan \"Annuleren\".",
    "unsaved-changes": "Niet-opgeslagen wijzigingen",
    "daily-overall-experience": "Dagelijkse algehele ervaring",
    "average": "Gemiddelde",
    "include-symptoms": "Symptomen opnemen",
    "select-symptoms": "Symptomen selecteren",
    "include-treatments": "Behandelingen opnemen",
    "select-treatments": "Behandelingen selecteren",
    "download-mydatahelps": "Download MyDataHelps",
    "connect-devices-title": "Verbind apparaten",
    "connect-devices-text": "Deel gegevens van uw wearables, apps en andere apparaten.",
    "apple-health-troubleshooting-intro": "Als u de deling van uw Apple Health-gegevens niet heeft goedgekeurd of heeft uitgeschakeld en dit wilt inschakelen, volgt u deze stappen:",
    "apple-health-troubleshooting-li-1": "Open de app \"Instellingen\"",
    "apple-health-troubleshooting-li-2": "Selecteer \"Privacy\"",
    "apple-health-troubleshooting-li-3": "Selecteer \"Gezondheid\"",
    "apple-health-troubleshooting-li-4": "Selecteer \"MyDataHelps\"",
    "apple-health-troubleshooting-li-5": "Schakel de categorieën gegevens in die u wilt delen",
    "how-to-enable": "Hoe inschakelen",
    "new-points-title": "Goed gedaan!",
    "new-points-text": "Je hebt punten verdiend voor het volgende:",
    "new-points-next-reward-prefix": "Je hebt nu ",
    "new-points-next-reward-suffix": " punten nodig om je volgende beloning te ontgrendelen.",
    "new-points-done-button-text": "Klaar",
    "systolic-average": "Gemiddelde systolische waarde",
    "diastolic-average": "Gemiddelde diastolische waarde",
    "highest-systolic": "Hoogste systolische waarde",
    "lowest-systolic": "Laagste systolische waarde",
    "resource-default-button-text": "Openen",
    "inbox-message-completed-status": "BEKEKEN",
    "inbox-resource-completed-status": "BEKEKEN",
    "inbox-survey-completed-status": "VOLTOOID",
    "inbox-history-view-title": "Inboxgeschiedenis",
    "inbox-history-view-empty-text": "U heeft geen items in uw inboxgeschiedenis.",
    "inbox-message-view-related-resources-title": "Gerelateerd",
    "inbox-view-title": "Inbox",
    "inbox-view-empty-text": "U heeft geen nieuwe items in uw inbox.",
    "inbox-view-messages-title": "Berichten",
    "inbox-view-surveys-title": "Enquêtes",
    "inbox-view-resources-title": "Bronnen",
    "inbox-view-recently-completed-title": "Recent",
    "inbox-view-recently-completed-empty-text": "U heeft geen recent voltooide items in uw inbox.",
    "inbox-view-history-button-text": "Inboxgeschiedenis bekijken",
    "choose-report-month": "Kies Rapportmaand",
    "include-overall-experience": "Inclusief dagelijkse algehele ervaring",
    "include-notes": "Notities opnemen",
    "create-report": "PDF-rapport maken",
    "reports": "Rapporten",
    "recent-daily-data-bar-chart-subtitle": "Afgelopen 7 dagen",
    "recent-daily-data-bar-chart-no-data": "Geen gegevens",
    "resource-list-empty-text": "Geen bronnen gevonden.",
    "asthma-symptom-level-none": "Geen symptomen",
    "asthma-symptom-level-mild": "Lichte symptomen",
    "asthma-symptom-level-moderate": "Matige symptomen",
    "asthma-symptom-level-severe": "Ernstige symptomen",
    "asthma-symptom-difficulty-breathing": "Ademhalingsmoeilijkheden",
    "asthma-symptom-wheezing": "Piepende ademhaling",
    "asthma-symptom-coughing": "Hoesten",
    "asthma-symptom-chest-tightness": "Beklemmend gevoel op de borst",
    "asthma-impact-limit-daily-activity": "Beperk uw dagelijkse activiteit",
    "asthma-impact-waking-at-night": "Word 's nachts wakker",
    "asthma-impact-using-rescue-inhaler": "Gebruik uw noodinhalator",
    "asthma-trigger-cold-illness": "Koude/virale ziekte",
    "asthma-trigger-animal-exposure": "Blootstelling aan dieren",
    "asthma-trigger-seasonal-allergens": "Seizoensgebonden allergenen/pollen",
    "asthma-trigger-smoke": "Rook",
    "asthma-trigger-weather-changes": "Extreme weersveranderingen",
    "asthma-trigger-air-pollution": "Luchtvervuiling",
    "asthma-trigger-strong-smells": "Sterke geuren",
    "asthma-trigger-chemicals": "Chemicaliën/schoonmaakmiddelen",
    "asthma-trigger-dust": "Stof",
    "asthma-trigger-mold": "Schimmel",
    "asthma-trigger-dust-mites": "Huisstofmijt",
    "asthma-trigger-rodents": "Knaagdieren",
    "asthma-trigger-cockroaches": "Kakkerlakken",
    "asthma-trigger-nsaid": "NSAID/Aspirine",
    "asthma-trigger-beta-blocker": "Bètablokker",
    "asthma-trigger-heartburn": "Brandend maagzuur",
    "asthma-trigger-red-wine": "Rode wijn",
    "asthma-trigger-new-foods": "Nieuwe voedingsmiddelen",
    "asthma-trigger-cooked-without-ventilation": "Koken (zonder ventilatie)",
    "asthma-trigger-pet-in-bed": "Huisdier in uw bed",
    "asthma-trigger-incense-or-candle": "Kaars/wierook",
    "asthma-data-status-out-of-range": "Buiten bereik",
    "asthma-data-status-in-range": "Binnen bereik",
    "asthma-data-status-offline": "Offline",
    "asthma-data-status-establishing": "Wordt vastgesteld",
    "asthma-data-status-not-determined": "Basislijn niet vastgesteld",
    "asthma-data-status-not-found": "Geen gegevens vastgelegd",
    "asthma-data-status-not-configured": "Niet geconfigureerd",
    "asthma-control-calendar-daily-entry-missed": "Dagelijkse invoer gemist",
    "asthma-control-calendar-not-logged-yet": "Nog niet ingelogd",
    "asthma-control-calendar-log-entries-symptoms-label": "Symptomen",
    "asthma-control-calendar-log-entries-impacts-label": "Effecten",
    "asthma-control-calendar-log-entries-triggers-label": "Triggers",
    "asthma-control-status-header-multiple-out-of-range-p1": "Meerdere gegevenspunten zijn ",
    "asthma-control-status-header-multiple-out-of-range-p2": "buiten uw normale niveaus",
    "asthma-control-status-header-multiple-out-of-range-p3": ". Voltooi uw dagelijkse invoer.",
    "asthma-control-status-header-abnormal-heart-rate-p1": "Uw rusthartslag is ",
    "asthma-control-status-header-abnormal-heart-rate-p2": "boven uw normale niveau",
    "asthma-control-status-header-abnormal-heart-rate-p3": ". Voltooi uw dagelijkse invoer.",
    "asthma-control-status-header-abnormal-respiratory-rate-p1": "Uw ademhalingsfrequentie is ",
    "asthma-control-status-header-abnormal-respiratory-rate-p2": "boven uw normale niveau",
    "asthma-control-status-header-abnormal-respiratory-rate-p3": ". Voltooi uw dagelijkse invoer.",
    "asthma-control-status-header-abnormal-steps-p1": "Uw activiteit is ",
    "asthma-control-status-header-abnormal-steps-p2": "onder uw normale niveau",
    "asthma-control-status-header-abnormal-steps-p3": ". Voltooi uw dagelijkse invoer.",
    "asthma-control-status-header-abnormal-sleep-p1": "Uw slaapverstoringen zijn ",
    "asthma-control-status-header-abnormal-sleep-p2": "boven uw normale niveau",
    "asthma-control-status-header-abnormal-sleep-p3": ". Voltooi uw dagelijkse invoer.",
    "asthma-control-status-header-abnormal-blood-oxygen-p1": "Uw bloedzuurstofniveau is ",
    "asthma-control-status-header-abnormal-blood-oxygen-p2": "onder uw normale niveau",
    "asthma-control-status-header-abnormal-blood-oxygen-p3": ". Voltooi uw dagelijkse invoer.",
    "asthma-control-status-header-abnormal-home-aqi-p1": "Uw Air Quality Index thuis is ",
    "asthma-control-status-header-abnormal-home-aqi-p2": ". Voltooi uw dagelijkse invoer.",
    "asthma-control-status-header-abnormal-work-aqi-p1": "Uw Air Quality Index op het werk is ",
    "asthma-control-status-header-abnormal-work-aqi-p2": ". Voltooi uw dagelijkse invoer.",
    "asthma-control-status-header-no-data": "Voeg een dagelijkse invoer toe om uw astmacontrole te beoordelen.",
    "asthma-control-status-header-not-determined": "Meer dagelijkse invoeren nodig om uw astmacontrole te beoordelen.",
    "asthma-control-status-header-controlled-p1": "Op basis van uw invoer is uw astma ",
    "asthma-control-status-header-controlled-p2": "onder controle.",
    "asthma-control-status-header-not-controlled-p1": "Op basis van uw invoer is uw astma ",
    "asthma-control-status-header-not-controlled-p2": "niet onder controle.",
    "asthma-control-status-header-not-controlled-stat-symptom-days": "Dagen met symptomen",
    "asthma-control-status-header-not-controlled-stat-rescue-inhaler": "Noodinhalator",
    "asthma-control-status-header-not-controlled-stat-limited-activity": "Beperkte activiteit",
    "asthma-control-status-header-not-controlled-stat-awakenings": "Ontwakingen",
    "asthma-action-plan-manager-title": "Actieplan astma",
    "asthma-action-plan-manager-instructions": "Sla een foto op van uw astma-actieplan voor eenvoudige referentie.",
    "asthma-action-plan-manager-learn-more": "Wat is een astma-actieplan?",
    "asthma-action-plan-manager-edit-button-text": "Bewerken",
    "asthma-action-plan-manager-not-found-text": "Tik om foto toe te voegen",
    "asthma-biometrics-title": "Gezondheid & Activiteit",
    "asthma-biometrics-daytime-resting-heart-rate-label": "Rusthartslag (Dag)",
    "asthma-biometrics-nighttime-resting-heart-rate-label": "Rusthartslag (Nacht)",
    "asthma-biometrics-beats-per-minute-units": "BPM",
    "asthma-biometrics-respiratory-rate-label": "Ademhalingsfrequentie",
    "asthma-biometrics-breaths-per-minute-units": "BPM",
    "asthma-biometrics-steps-label": "Stappen",
    "asthma-biometrics-daytime-blood-oxygen-level-label": "Zuurstofsaturatie (Dag)",
    "asthma-biometrics-nighttime-blood-oxygen-level-label": "Zuurstofsaturatie (Nacht)",
    "asthma-biometrics-percent-units": "%",
    "asthma-biometrics-sleep-disturbances-label": "Slaapverstoringen",
    "asthma-air-qualities-title": "Luchtkwaliteit",
    "asthma-air-qualities-setup-button-text": "+ Instellen",
    "asthma-air-qualities-home-aqi-label": "LKI (Thuis)",
    "asthma-air-qualities-work-aqi-label": "LKI (Werk)",
    "asthma-alert-takeover-notice-instructions": "Neem een moment om eventuele astmasymptomen in een dagelijkse invoer te registreren.",
    "asthma-alert-takeover-notice-add-entry-button-text": "+ Dagelijkse Invoer",
    "asthma-alert-takeover-notice-not-now-button-text": "Nu niet",
    "asthma-log-entry-details-not-editable": "Dagelijkse invoer gemist",
    "asthma-log-entry-details-not-logged-yet": "Nog niet ingelogd",
    "asthma-log-entry-details-edit-button-text": "Bewerken",
    "asthma-log-entry-details-add-button-text": "Invoer Loggen",
    "asthma-log-entry-details-symptoms-label": "Symptomen",
    "asthma-log-entry-details-impacts-label": "Effecten",
    "asthma-log-entry-details-triggers-label": "Triggers",
    "asthma-log-entry-details-component-no-data-p1": "Geen ",
    "asthma-log-entry-details-component-no-data-p2": " gelogd",
    "asthma-log-entry-header-today-log-label": "Vandaag",
    "asthma-log-entry-header-yesterday-log-label": "Gisteren",
    "asthma-log-entry-header-not-logged-yet": "Nog niet ingelogd",
    "asthma-log-entry-header-add-button-text": "Invoer Loggen",
    "asthma-activity-view-title": "Activiteit",
    "asthma-activity-view-chart-title": "Stappen",
    "asthma-activity-view-alert-message": "Uw activiteit is onder uw normale niveau.",
    "asthma-alert-takeover-message": "Meerdere gegevenspunten zijn buiten uw normale niveaus.",
    "asthma-air-quality-view-title": "Luchtkwaliteit",
    "asthma-air-quality-view-home-aqi-chart-title": "Luchtkwaliteit (Thuis)",
    "asthma-air-quality-view-home-aqi-alert-message": "Uw thuis LKI is ongezond.",
    "asthma-air-quality-view-work-aqi-chart-title": "Luchtkwaliteit (Werk)",
    "asthma-air-quality-view-work-aqi-alert-message": "Uw werk LKI is ongezond.",
    "asthma-heart-and-lungs-view-title": "Hart & Longen",
    "asthma-heart-and-lungs-view-dhr-chart-title": "Rusthartslag (Dag)",
    "asthma-heart-and-lungs-view-dhr-alert-message": "Uw rusthartslag overdag is boven uw normale niveau.",
    "asthma-heart-and-lungs-view-nhr-chart-title": "Rusthartslag (Nacht)",
    "asthma-heart-and-lungs-view-nhr-alert-message": "Uw rusthartslag 's nachts is boven uw normale niveau.",
    "asthma-heart-and-lungs-view-rr-chart-title": "Ademhalingsfrequentie",
    "asthma-heart-and-lungs-view-rr-alert-message": "Uw ademhalingsfrequentie is boven uw normale niveau.",
    "asthma-heart-and-lungs-view-dbol-chart-title": "Zuurstofgehalte in het bloed (Dag)",
    "asthma-heart-and-lungs-view-dbol-alert-message": "Uw zuurstofgehalte in het bloed overdag is onder uw normale niveau.",
    "asthma-heart-and-lungs-view-nbol-chart-title": "Zuurstofgehalte in het bloed (Nacht)",
    "asthma-heart-and-lungs-view-nbol-alert-message": "Uw zuurstofgehalte in het bloed 's nachts is onder uw normale niveau.",
    "asthma-sleep-view-title": "Slaap",
    "asthma-sleep-view-chart-title": "Slaapverstoringen",
    "asthma-sleep-view-alert-message": "Uw slaapverstoringen zijn boven uw normale niveau.",
    "asthma-log-entry-editor-view-symptom-level-title": "Symptoomniveau",
    "asthma-log-entry-editor-view-select-one-subtitle": "Selecteer één",
    "asthma-log-entry-editor-view-select-all-subtitle": "Selecteer alle die van toepassing zijn",
    "asthma-log-entry-editor-view-symptoms-title": "Symptomen",
    "asthma-log-entry-editor-view-impacts-title": "Effecten",
    "asthma-log-entry-editor-view-triggers-title": "Triggers",
    "asthma-air-quality-description-unhealthy": "Ongezond",
    "asthma-air-quality-description-very-unhealthy": "Zeer ongezond",
    "asthma-air-quality-description-hazardous": "Gevaarlijk",
    "blood-type": "Bloedgroep",
    "device-data-month-chart-no-data": "Geen Gegevens",
    "device-data-month-chart-daily-average": "Dagelijks Gemiddelde",
    "term-information-not-found-header": "Geen Informatie Gevonden",
    "term-information-not-found-body": "Geen informatie gevonden over dit onderwerp",
    "term-information-disclaimer": "<strong>DISCLAIMER:</strong> De verstrekte informatie is geen medisch advies. Het is bedoeld om u te helpen uw gezondheid beter te begrijpen. Neem contact op met uw zorgverlener als u vragen heeft over uw medische toestand.",
    "term-information-view-on-medline": "Bekijk op MedlinePlus",
    "type": "Type",
    "location": "Locatie",
    "description": "Beschrijving",
    "performed-by": "Uitgevoerd door",
    "verified-by": "Gecontroleerd door",
    "normal-range": "Normaal bereik",
    "more": "Meer",
    "procedure": "Procedure",
    "procedures": "Procedures",
    "lab-report": "Laboratoriumrapport",
    "service-performed": "Uitgevoerde Dienst",
    "services-performed": "Uitgevoerde Diensten",
    "device-data-month-chart-minutes": "Minuten",
    "device-data-month-chart-sleep": "Slaap",
    "air-quality-home": "Luchtkwaliteit (Thuis)",
    "air-quality-work": "Luchtkwaliteit (Werk)",
    "sedentary-time": "Zittende Tijd",
    "active-time": "Actieve Tijd",
    "lightly-active-time": "Licht Actieve Tijd",
    "fairly-active-time": "Redelijk Actieve Tijd",
    "very-active-time": "Zeer Actieve Tijd",
    "breathing-rate": "Ademhalingsfrequentie",
    "calories-burned": "Verbrande Calorieën",
    "elevated-heart-rate-time": "Tijd met Verhoogde Hartslag",
    "fat-burn-heart-rate-time": "Tijd voor Vetverbranding",
    "cardio-heart-rate-time": "Cardio Tijd",
    "peak-heart-rate-time": "Tijd op Piekniveau Hartslag",
    "floors-climbed": "Geklommen Trappen",
    "heart-rate-variability": "Hartslagvariabiliteit",
    "sleep-time": "Slaaptijd",
    "light-sleep-time": "Lichte Slaaptijd",
    "deep-sleep-time": "Diepe Slaaptijd",
    "rem-sleep-time": "REM Slaaptijd",
    "spo2": "SpO2",
    "heart-rate-range": "Hartslagbereik",
    "max-heart-rate": "Maximale Hartslag",
    "core-sleep-time": "Kern Slaaptijd",
    "in-bed-time": "Tijd in Bed",
    "stand-time": "Sta-tijd",
    "walking-heart-rate-average": "Gemiddelde Hartslag tijdens het Wandelen",
    "active-energy-burned": "Verbruikte Actieve Energie",
    "active-calories": "Actieve Calorieën",
    "resting-calories": "Rustende Calorieën",
    "total-calories": "Totaal Calorieën",
    "min-heart-rate": "Minimale Hartslag",
    "average-heart-rate": "Gemiddelde Hartslag",
    "max-stress-level": "Maximaal Stressniveau",
    "average-stress-level": "Gemiddeld Stressniveau",
    "total-stress-time": "Totale Stress Tijd",
    "low-stress-time": "Lage Stress Tijd",
    "medium-stress-time": "Gemiddelde Stress Tijd",
    "high-stress-time": "Hoge Stress Tijd",
    "awake-time": "Wakkere Tijd",
    "sleep-score": "Slaapscore",
    "bpm": "bpm",
    "hours-abbreviation": "u",
    "minutes-abbreviation": "m",
    "points-until-next-badge": "{{points}} punten tot de volgende badge",
    "fitbit-wear-time": "Fitbit Draagtijd",
    "my-badges": "Mijn badges ({{badges}})",
    "new-badge-title": "Goed gedaan!",
    "new-badge-text": "Je hebt een nieuwe badge gekregen!",
    "get-badge": "Badge krijgen"
};

export default strings;