let strings: { [key: string]: string } = {
    "back": "Rudi",
    "done": "Imekamilika",
    "close": "Funga",
    "save": "Hifadhi",
    "add": "Ongeza",
    "edit": "Hariri",
    "cancel": "Ghairi",
    "clear": "futa",
    "settings": "Mipangilio",
    "connect": "Unganisha",
    "reconnect": "Unganisha tena",
    "setup": "Sanidi",
    "refresh": "Onyesha upya",
    "remove": "Ondoa",
    "help": "Msaada",
    "view": "Tazama",
    "health-records": "Rekodi za Afya",
    "connect-ehr-title-prefix": "Unganisha ",
    "connect-ehr-title-divider": " au ",
    "connect-ehr-title-providers": "Mtoa Huduma",
    "connect-ehr-title-health-plans": "Mpango wa Afya",
    "connect-ehr-connected": "Tunapokea data yako ya EHR!",
    "connect-ehr-needs-attention": "Mojawapo ya akaunti zako inahitaji umakini.",
    "connect-ehr-text": "Unganisha mtoa huduma wako au mpango wa afya ili kuona matokeo ya maabara, hali, dawa na zaidi.",
    "connect-ehr-text-connected": "Unganisha mtoa huduma mwingine ili kushiriki data zaidi au kusimamia unganisho wako wa EHR.",
    "connect-ehr-not-enabled": "Uunganishaji wa EHR haujaruhusiwa kwa mradi huu.",
    "search-for-provider": "Tafuta Mtoa Huduma au Mpango wa Afya",
    "request-add": "Omba kuongeza",
    "expired-reconnect": "Muunganisho umeisha. Tafadhali unganisha tena.",
    "connect-error-reconnect": "Hitilafu isiyotarajiwa. Tafadhali unganisha tena.",
    "connected": "Imeunganishwa",
    "search": "Tafuta",
    "connect-fitbit-intro": "Unaweza kushiriki data kutoka kwa akaunti yako ya Fitbit ikiwa unayo. Ili kuanza, bofya au gusa hapa chini ili kuingia kwa kutumia hati tambulishi zako za Fitbit.",
    "connect-fitbit-button": "Unganisha Fitbit",
    "received-fitbit-data": "Tunapokea data yako ya Fitbit!",
    "connect-garmin-intro": "Unaweza kushiriki data kutoka kwa akaunti yako ya Garmin ikiwa unayo. Ili kuanza, bofya au gusa hapa chini ili kuingia kwa kutumia hati tambulishi zako za Garmin.",
    "connect-garmin-button": "Unganisha Garmin",
    "received-garmin-data": "Tunapokea data yako ya Garmin!",
    "connect-oura-intro": "Unaweza kushiriki data kutoka kwa akaunti yako ya Oura ikiwa unayo. Ili kuanza, bofya au gusa hapa chini ili kuingia kwa kutumia hati tambulishi zako za Oura.",
    "connect-oura-button": "Unganisha Oura",
    "received-oura-data": "Tunapokea data yako ya Oura!",
    "connect-dexcom-intro": "Unaweza kushiriki data kutoka kwa akaunti yako ya Dexcom ikiwa unayo. Ili kuanza, bofya au gusa hapa chini ili kuingia kwa kutumia hati tambulishi zako za Dexcom.",
    "connect-dexcom-button": "Unganisha Dexcom",
    "received-dexcom-data": "Tunapokea data yako ya Dexcom!",
    "downloading-data": "Inapakua data...",
    "downloading-data-menu": "Inapakua Data",
    "empty-tasks-incomplete": "Hakuna kazi zilizo wazi za kuonyesha kwa sasa.",
    "empty-tasks-complete": "Kazi zilizokamilika zitaonyeshwa hapa.",
    "view-all": "Tazama Zote",
    "tasks": "Kazi",
    "incomplete-tasks": "Kazi Zisizokamilika",
    "completed-tasks": "Kazi Zilizokamilika",
    "overdue": "Zimechelewa",
    "due-today": "Zinadaiwa Leo",
    "due-tomorrow": "Zinadaiwa Kesho",
    "due": "Inadaiwa",
    "due-in": "Inadaiwa kwa",
    "days": "siku",
    "notifications": "Arifa",
    "support": "Msaada",
    "all-notifications": "Arifa Zote",
    "steps": "Hatua",
    "resting-heart-rate": "Kiwango cha Mapigo ya Moyo Wakati wa Kupumzika",
    "distance-traveled": "Umbali Uliosafiri",
    "google-fit-share": "Gusa ili kushiriki data ya afya",
    "devices": "Vifaa",
    "last-sync": "Ilisawazishwa mwisho",
    "completed": "Imekamilika",
    "ehr-intro-search": "Tafuta kwa kuingiza jina la mtoa huduma wako au tovuti ya mwanachama kwa mtoa huduma wako wa afya au mpango wa afya.",
    "external-accounts-title-divider": " / ",
    "external-accounts-title-providers": "Watoa Huduma",
    "external-accounts-title-health-plans": "Mipango ya Afya",
    "external-accounts-title-devices": "Vifaa",
    "external-accounts-error": "Mojawapo ya akaunti zako inahitaji umakini",
    "external-accounts-loading": "Data yako inapakuliwa kwa sasa kutoka kwa mipango ya afya na watoa huduma ulioungana nao. Tafadhali angalia tena baada ya muda mfupi ili kuona data yako.",
    "external-account-authorization-expired": "Idhini imeisha",
    "external-account-fetching-data": "Inapata data...",
    "external-account-deleting": "Inaondoa...",
    "external-account-last-updated": "Ilisasishwa mwisho",
    "external-account-error": "Hitilafu isiyotarajiwa",
    "external-account-reconnect": "Unganisha tena",
    "external-account-refresh": "Onyesha upya",
    "external-account-remove": "Ondoa",
    "device-data-no-data": "Ikiwa umeunganisha Apple Health, Google Fit, Fitbit, au Garmin, angalia tena baadaye ili kuona data yako.",
    "no-notifications-received": "Hakuna arifa zilizopokelewa",
    "next-button-text": "Inayofuata",
    "lab-results-title": "Matokeo ya Maabara",
    "medications-title": "Dawa",
    "immunizations-title": "Chanjo",
    "reports-title": "Ripoti",
    "allergies-title": "Mzio",
    "conditions-title": "Hali",
    "procedures-title": "Taratibu",
    "app-download-title": "Inayofuata: Pakua Programu",
    "app-download-subtitle": "Kupakua programu ya MyDataHelps inafanya iwe rahisi zaidi kushiriki katika @@PROJECT_NAME@@.",
    "app-download-google-play-link-alt": "Pakua kwenye Duka la Google Play",
    "app-download-app-store-link-alt": "Pakua kwenye Duka la Apple App",
    "start": "Anza",
    "resume": "Endelea",
    "start-survey": "Anza Utafiti",
    "resume-survey": "Endelea na Utafiti",
    "30-day-average": "Wastani wa Siku 30",
    "today": "Leo",
    "yesterday": "Jana",
    "tap-to-log-today": "Gusa hapa ili kurekodi dalili au matibabu yako!",
    "mild": "Kidogo",
    "moderate": "Wastani",
    "severe": "Kali",
    "severe-shortened": "kali",
    "moderate-shortened": "was",
    "mild-shortened": "kid",
    "log-todays-symptoms": "Rekodi Dalili za Leo",
    "todays-log": "Rekodi ya Leo",
    "symptoms": "Dalili",
    "treatments": "Matibabu",
    "symptoms-experiencing-today": "Ni dalili gani unazopata?",
    "symptoms-experiencing-previous": "Ni dalili gani ulizokuwa unapata?",
    "treatments-experiencing-today": "Ni matibabu gani umefanya?",
    "treatments-experiencing-previous": "Ni matibabu gani ulifanya?",
    "feeling-overall-today": "Unajisikiaje kwa ujumla?",
    "feeling-overall-previous": "Ulijisikiaje kwa ujumla?",
    "additional-notes": "Maelezo yoyote ya ziada?",
    "how-severe-is": "Ni kali kiasi gani",
    "how-severe-was": "Ilikuwa kali kiasi gani",
    "clear-symptom": "Futa Dalili",
    "add-notes": "Ongeza maelezo",
    "notes": "Maelezo",
    "enter-symptom-name": "Ingiza Jina la Dalili",
    "enter-treatment-name": "Ingiza Jina la Matibabu",
    "severity-tracking-none": "Usifuatilie Ukali",
    "severity-tracking-3point": "Tathmini ya Kidogo / Wastani / Kali",
    "severity-tracking-10point": "Tathmini ya Alama 1 - 10",
    "muted": "Kimenywa",
    "not-muted": "Hakijanyamazishwa",
    "delete": "Futa",
    "severity": "Ukali",
    "item-delete-warning": "Onyo: Kuendelea kutafuta vipengele vilivyo hapa chini na data zote zinazohusiana kutoka kwa rekodi zako. Ikiwa hutaki kufuta vipengele hivi, chagua \"Ghairi\".",
    "unsaved-changes": "Mabadiliko Ambayo Hayajahifadhiwa",
    "daily-overall-experience": "Uzoefu wa Jumla wa Kila Siku",
    "average": "Wastani",
    "include-symptoms": "Jumuisha Dalili",
    "select-symptoms": "Chagua Dalili",
    "include-treatments": "Jumuisha Matibabu",
    "select-treatments": "Chagua Matibabu",
    "download-mydatahelps": "Pakua MyDataHelps",
    "connect-devices-title": "Unganisha Vifaa",
    "connect-devices-text": "Shiriki data kutoka kwa vifaa vyako vya kuvaa, programu, na vifaa vingine.",
    "apple-health-troubleshooting-intro": "Ikiwa hukuidhinisha au umezima kushiriki data yako ya Apple Health na ungependa kuiwezesha, fuata hatua hizi:",
    "apple-health-troubleshooting-li-1": "Fungua programu ya \"Mipangilio\"",
    "apple-health-troubleshooting-li-2": "Chagua \"Faragha\"",
    "apple-health-troubleshooting-li-3": "Chagua \"Afya\"",
    "apple-health-troubleshooting-li-4": "Chagua \"MyDataHelps\"",
    "apple-health-troubleshooting-li-5": "Wezesha aina za data unazotaka kushiriki",
    "how-to-enable": "Jinsi ya kuwezesha",
    "new-points-title": "Umefanya Vizuri!",
    "new-points-text": "Umepewa pointi kwa yafuatayo:",
    "new-points-next-reward-prefix": "Sasa unahitaji ",
    "new-points-next-reward-suffix": " pointi ili kufungua tuzo yako inayofuata.",
    "new-points-done-button-text": "Imekamilika",
    "systolic-average": "Wastani wa Systolic",
    "diastolic-average": "Wastani wa Diastolic",
    "highest-systolic": "Systolic ya Juu Zaidi",
    "lowest-systolic": "Systolic ya Chini Zaidi",
    "resource-default-button-text": "Fungua",
    "inbox-message-completed-status": "IMEANGALIWA",
    "inbox-resource-completed-status": "IMEANGALIWA",
    "inbox-survey-completed-status": "IMEKAMILIKA",
    "inbox-history-view-title": "Historia ya Inbox",
    "inbox-history-view-empty-text": "Huna vipengele katika historia yako ya inbox.",
    "inbox-message-view-related-resources-title": "Zinazohusiana",
    "inbox-view-title": "Inbox",
    "inbox-view-empty-text": "Huna vipengele vipya katika inbox yako.",
    "inbox-view-messages-title": "Ujumbe",
    "inbox-view-surveys-title": "Tafiti",
    "inbox-view-resources-title": "Rasilimali",
    "inbox-view-recently-completed-title": "Hivi Karibuni",
    "inbox-view-recently-completed-empty-text": "Huna vipengele vilivyokamilika hivi karibuni katika inbox yako.",
    "inbox-view-history-button-text": "Tazama historia ya inbox",
    "choose-report-month": "Chagua Mwezi wa Ripoti",
    "include-overall-experience": "Jumuisha Uzoefu wa Jumla wa Kila Siku",
    "include-notes": "Jumuisha Maelezo",
    "create-report": "Tengeneza Ripoti ya PDF",
    "reports": "Ripoti",
    "recent-daily-data-bar-chart-subtitle": "Siku 7 zilizopita",
    "recent-daily-data-bar-chart-no-data": "Hakuna Data",
    "resource-list-empty-text": "Hakuna rasilimali zilizopatikana.",
    "asthma-symptom-level-none": "Hakuna dalili",
    "asthma-symptom-level-mild": "Dalili kidogo",
    "asthma-symptom-level-moderate": "Dalili za wastani",
    "asthma-symptom-level-severe": "Dalili kali",
    "asthma-symptom-difficulty-breathing": "Ugumu wa kupumua",
    "asthma-symptom-wheezing": "Kupumua kwa mlio",
    "asthma-symptom-coughing": "Kukohoa",
    "asthma-symptom-chest-tightness": "Kifua kufungana au shinikizo",
    "asthma-impact-limit-daily-activity": "Kupunguza shughuli zako za kila siku",
    "asthma-impact-waking-at-night": "Kuamka usiku",
    "asthma-impact-using-rescue-inhaler": "Kutumia inhaler ya dharura",
    "asthma-trigger-cold-illness": "Mafua/ugonjwa wa virusi",
    "asthma-trigger-animal-exposure": "Kuwa karibu na wanyama",
    "asthma-trigger-seasonal-allergens": "Vitu vya msimu vinavyosababisha mzio/poleni",
    "asthma-trigger-exercise": "Mazoezi",
    "asthma-trigger-smoke": "Moshi",
    "asthma-trigger-weather-changes": "Mabadiliko makali ya hali ya hewa",
    "asthma-trigger-air-pollution": "Uchafuzi wa hewa",
    "asthma-trigger-strong-smells": "Harufu kali",
    "asthma-trigger-chemicals": "Kemikali/vifaa vya usafi",
    "asthma-trigger-dust": "Vumbi",
    "asthma-trigger-mold": "Kuvu",
    "asthma-trigger-dust-mites": "Wadudu wa vumbi",
    "asthma-trigger-rodents": "Panya",
    "asthma-trigger-cockroaches": "Mende",
    "asthma-trigger-nsaid": "NSAID/Aspirin",
    "asthma-trigger-beta-blocker": "Beta blocker",
    "asthma-trigger-heartburn": "Kichomi",
    "asthma-trigger-red-wine": "Divai nyekundu",
    "asthma-trigger-new-foods": "Vyakula vipya",
    "asthma-trigger-cooked-without-ventilation": "Kupika (bila hewa)",
    "asthma-trigger-pet-in-bed": "Mnyama wa nyumbani kitandani kwako",
    "asthma-trigger-incense-or-candle": "Mshumaa/ubani",
    "asthma-data-status-out-of-range": "Nje ya kiwango",
    "asthma-data-status-in-range": "Ndani ya kiwango",
    "asthma-data-status-offline": "Nje ya mtandao",
    "asthma-data-status-establishing": "Inaanzisha",
    "asthma-data-status-not-determined": "Msingi haujaanzishwa",
    "asthma-data-status-not-found": "Hakuna data iliyorekodiwa",
    "asthma-data-status-not-configured": "Haijasanidiwa",
    "asthma-control-calendar-daily-entry-missed": "Ingizo la kila siku limekosekana",
    "asthma-control-calendar-not-logged-yet": "Bado haijaingizwa",
    "asthma-control-calendar-log-entries-symptoms-label": "Dalili",
    "asthma-control-calendar-log-entries-impacts-label": "Athari",
    "asthma-control-calendar-log-entries-triggers-label": "Visababishi",
    "asthma-control-status-header-complete-daily-entry": "Kamilisha ingizo lako la kila siku.",
    "asthma-control-status-header-multiple-out-of-range": "Pointi nyingi za data ziko |||nje ya viwango vyako vya kawaida|||.",
    "asthma-control-status-header-abnormal-heart-rate": "Kiwango chako cha mapigo ya moyo wakati wa kupumzika kiko |||juu ya kiwango chako cha kawaida|||.",
    "asthma-control-status-header-abnormal-respiratory-rate": "Kiwango chako cha upumuaji kiko |||juu ya kiwango chako cha kawaida|||.",
    "asthma-control-status-header-abnormal-steps": "Shughuli zako ziko |||chini ya viwango vyako vya kawaida|||.",
    "asthma-control-status-header-abnormal-sleep": "Usumbufu wako wa usingizi uko |||juu ya kiwango chako cha kawaida|||.",
    "asthma-control-status-header-abnormal-blood-oxygen": "Kiwango chako cha oksijeni katika damu kiko |||chini ya kiwango chako cha kawaida|||.",
    "asthma-control-status-header-abnormal-home-aqi": "Kiwango cha Ubora wa Hewa nyumbani kwako ni |||{aqi}|||.",
    "asthma-control-status-header-abnormal-work-aqi": "Kiwango cha Ubora wa Hewa kazini kwako ni |||{aqi}|||.",
    "asthma-control-status-header-no-data": "Ongeza ingizo la kila siku ili kutathmini udhibiti wa pumu yako.",
    "asthma-control-status-header-no-data-caregiver": "Ongeza ingizo la kila siku ili kutathmini udhibiti wa pumu ya {name}.",
    "asthma-control-status-header-not-determined": "Maingizo zaidi ya kila siku yanahitajika ili kutathmini udhibiti wa pumu yako.",
    "asthma-control-status-header-not-determined-caregiver": "Maingizo zaidi ya kila siku yanahitajika ili kutathmini udhibiti wa pumu ya {name}.",
    "asthma-control-status-header-controlled": "Kulingana na maingizo yako, pumu yako iko |||chini ya udhibiti|||.",
    "asthma-control-status-header-controlled-caregiver": "Kulingana na maingizo, pumu ya {name} iko |||chini ya udhibiti|||.",
    "asthma-control-status-header-not-controlled": "Kulingana na maingizo yako, pumu yako haiko |||chini ya udhibiti|||.",
    "asthma-control-status-header-not-controlled-caregiver": "Kulingana na maingizo, pumu ya {name} haiko |||chini ya udhibiti|||.",
    "asthma-control-status-header-not-controlled-stat-symptom-days": "Siku za dalili",
    "asthma-control-status-header-not-controlled-stat-rescue-inhaler": "Inhaler ya dharura",
    "asthma-control-status-header-not-controlled-stat-limited-activity": "Shughuli zilizopunguzwa",
    "asthma-control-status-header-not-controlled-stat-awakenings": "Kuamka",
    "asthma-action-plan-manager-title": "Mpango wa Hatua za Pumu",
    "asthma-action-plan-manager-instructions": "Hifadhi picha ya mpango wako wa hatua za pumu kwa ajili ya marejeleo rahisi.",
    "asthma-action-plan-manager-instructions-caregiver": "Hifadhi picha ya mpango wa hatua za pumu wa {name} kwa ajili ya marejeleo rahisi.",
    "asthma-action-plan-manager-learn-more": "Mpango wa hatua za pumu ni nini?",
    "asthma-action-plan-manager-edit-button-text": "Hariri",
    "asthma-action-plan-manager-not-found-text": "Gusa ili kuongeza picha",
    "asthma-biometrics-title": "Afya & Shughuli",
    "asthma-biometrics-daytime-resting-heart-rate-label": "Mapigo ya Moyo Wakati wa Kupumzika (Mchana)",
    "asthma-biometrics-nighttime-resting-heart-rate-label": "Mapigo ya Moyo Wakati wa Kupumzika (Usiku)",
    "asthma-biometrics-beats-per-minute-units": "BPM",
    "asthma-biometrics-respiratory-rate-label": "Kiwango cha Upumuaji",
    "asthma-biometrics-breaths-per-minute-units": "BPM",
    "asthma-biometrics-steps-label": "Hatua",
    "asthma-biometrics-daytime-blood-oxygen-level-label": "Kiwango cha Oksijeni (Mchana)",
    "asthma-biometrics-nighttime-blood-oxygen-level-label": "Kiwango cha Oksijeni (Usiku)",
    "asthma-biometrics-percent-units": "%",
    "asthma-biometrics-sleep-disturbances-label": "Usumbufu wa Usingizi",
    "asthma-air-qualities-title": "Ubora wa Hewa",
    "asthma-air-qualities-setup-button-text": "+ Sanidi",
    "asthma-air-qualities-home-aqi-label": "AQI (Nyumbani)",
    "asthma-air-qualities-work-aqi-label": "AQI (Kazini)",
    "asthma-alert-takeover-notice-instructions": "Chukua muda kurekodi dalili zozote za pumu katika ingizo la kila siku.",
    "asthma-alert-takeover-notice-add-entry-button-text": "+ Ingizo la Kila Siku",
    "asthma-alert-takeover-notice-not-now-button-text": "Sio Sasa",
    "asthma-log-entry-details-not-editable": "Ingizo la kila siku limekosekana",
    "asthma-log-entry-details-not-logged-yet": "Bado haijaingizwa",
    "asthma-log-entry-details-edit-button-text": "Hariri",
    "asthma-log-entry-details-add-button-text": "Ingiza Ingizo",
    "asthma-log-entry-details-symptoms-label": "Dalili",
    "asthma-log-entry-details-impacts-label": "Athari",
    "asthma-log-entry-details-triggers-label": "Visababishi",
    "asthma-log-entry-details-component-no-data-p1": "Hakuna ",
    "asthma-log-entry-details-component-no-data-p2": " iliyoingizwa",
    "asthma-log-entry-header-today-log-label": "Leo",
    "asthma-log-entry-header-yesterday-log-label": "Jana",
    "asthma-log-entry-header-not-logged-yet": "Bado haijaingizwa",
    "asthma-log-entry-header-add-button-text": "Ingiza Ingizo",
    "asthma-activity-view-title": "Shughuli",
    "asthma-activity-view-chart-title": "Hatua",
    "asthma-activity-view-alert-message": "Shughuli zako ziko chini ya kiwango chako cha kawaida.",
    "asthma-alert-takeover-message": "Pointi nyingi za data ziko nje ya viwango vyako vya kawaida.",
    "asthma-air-quality-view-title": "Ubora wa Hewa",
    "asthma-air-quality-view-home-aqi-chart-title": "Ubora wa Hewa (Nyumbani)",
    "asthma-air-quality-view-home-aqi-alert-message": "AQI ya nyumbani kwako si nzuri kwa afya.",
    "asthma-air-quality-view-work-aqi-chart-title": "Ubora wa Hewa (Kazini)",
    "asthma-air-quality-view-work-aqi-alert-message": "AQI ya kazini kwako si nzuri kwa afya.",
    "asthma-heart-and-lungs-view-title": "Moyo & Mapafu",
    "asthma-heart-and-lungs-view-dhr-chart-title": "Mapigo ya Moyo Wakati wa Kupumzika (Mchana)",
    "asthma-heart-and-lungs-view-dhr-alert-message": "Mapigo ya moyo wakati wa kupumzika mchana yako juu ya kiwango chako cha kawaida.",
    "asthma-heart-and-lungs-view-nhr-chart-title": "Mapigo ya Moyo Wakati wa Kupumzika (Usiku)",
    "asthma-heart-and-lungs-view-nhr-alert-message": "Mapigo ya moyo wakati wa kupumzika usiku yako juu ya kiwango chako cha kawaida.",
    "asthma-heart-and-lungs-view-rr-chart-title": "Kiwango cha Upumuaji",
    "asthma-heart-and-lungs-view-rr-alert-message": "Kiwango chako cha upumuaji kiko juu ya kiwango chako cha kawaida.",
    "asthma-heart-and-lungs-view-dbol-chart-title": "Oksijeni katika Damu (Mchana)",
    "asthma-heart-and-lungs-view-dbol-alert-message": "Kiwango cha oksijeni katika damu mchana kiko chini ya kiwango chako cha kawaida.",
    "asthma-heart-and-lungs-view-nbol-chart-title": "Oksijeni katika Damu (Usiku)",
    "asthma-heart-and-lungs-view-nbol-alert-message": "Kiwango cha oksijeni katika damu usiku kiko chini ya kiwango chako cha kawaida.",
    "asthma-sleep-view-title": "Usingizi",
    "asthma-sleep-view-chart-title": "Usumbufu wa Usingizi",
    "asthma-sleep-view-alert-message": "Usumbufu wako wa usingizi uko juu ya kiwango chako cha kawaida.",
    "asthma-log-entry-editor-view-symptom-level-title": "Kiwango cha dalili",
    "asthma-log-entry-editor-view-select-one-subtitle": "Chagua moja",
    "asthma-log-entry-editor-view-select-all-subtitle": "Chagua zote zinazohusika",
    "asthma-log-entry-editor-view-symptoms-title": "Dalili",
    "asthma-log-entry-editor-view-impacts-title": "Athari",
    "asthma-log-entry-editor-view-triggers-title": "Visababishi",
    "asthma-air-quality-description-unhealthy": "Si nzuri kwa afya",
    "asthma-air-quality-description-very-unhealthy": "Si nzuri kabisa kwa afya",
    "asthma-air-quality-description-hazardous": "Hatari",
    "asthma-recommended-article-21-title": "Jinsi ya kudhibiti pumu yako",
    "asthma-recommended-article-21-subtitle": "Kaa bila dalili kwa kufuata mpango wako wa matibabu, kuelewa visababishi, na kutambua mapema mabadiliko katika udhibiti.",
    "asthma-recommended-article-22-title": "Je, pumu yako iko chini ya udhibiti?",
    "asthma-recommended-article-22-subtitle": "Maswali 4 ya kutathmini kama pumu yako iko chini ya udhibiti. Ikiwa unapata dalili zaidi ya mara 2 kwa wiki au ikiwa unaamka usiku kutokana na dalili za pumu - pumu yako haiko chini ya udhibiti.",
    "asthma-recommended-article-24-title": "Kupitia Eneo la Hatari: Utayari kwa Kuongezeka kwa Pumu",
    "asthma-recommended-article-24-subtitle": "Tambua dalili kali kama vile kukohoa kwa nguvu na kupumua kwa shida mapema, na anzisha mpango wako wa hatua za pumu ikijumuisha dawa za haraka.",
    "asthma-recommended-article-25-title": "Kuchukua hatua kwa pumu yako",
    "asthma-recommended-article-25-subtitle": "Wakati pumu yako inahisi haiwezi kudhibitiwa, ni wakati wa kutathmini upya mbinu yako. Hatua za kuchukua wakati pumu yako haiko chini ya udhibiti.",
    "asthma-recommended-article-32-title": "Nani anahitaji dawa ya kudhibiti?",
    "asthma-recommended-article-32-subtitle": "Gundua jukumu muhimu la dawa za kudhibiti katika kudumisha pumu chini ya udhibiti.",
    "asthma-recommended-article-33-title": "Upatikanaji wa dawa",
    "asthma-recommended-article-33-subtitle": "Kwa wakati ambapo gharama ni kikwazo kwa dawa, jifunze kuhusu dawa za bure au za gharama nafuu. Kutumia dawa kama ilivyoagizwa ni muhimu kwa kudumisha udhibiti wa pumu.",
    "asthma-recommended-article-34-title": "Kujaza upya dawa",
    "asthma-recommended-article-34-subtitle": "Endelea kuwa na dawa yako ya pumu kwa mikakati rahisi ya kujaza upya.",
    "asthma-recommended-article-35-title": "Shida ya kukumbuka dawa",
    "asthma-recommended-article-35-subtitle": "Gundua mikakati rahisi lakini yenye ufanisi ya kukumbuka dozi zako za kila siku, kutoka kwa vidokezo vya kuhifadhi kwa busara hadi kutumia vikumbusho vya programu.",
    "asthma-recommended-article-36-title": "Inhaler gani ya kutumia wakati gani",
    "asthma-recommended-article-36-subtitle": "Kuwa mtaalamu wa usimamizi wa pumu yako: Inhaler ya dharura inafanya kazi haraka kuondoa dalili wakati inhaler ya kudhibiti ni ya kuzuia na inafanya kazi kwa kupunguza uvimbe, kwa kawaida kwa kuchukuliwa kila siku.",
    "asthma-recommended-article-37a-title": "Mbinu ya inhaler - MDI",
    "asthma-recommended-article-37a-subtitle": "Vidokezo vya mbinu ya inhaler ya kipimo kilichopimwa (MDI). Bila mbinu sahihi, unaweza kupata sehemu tu ya dozi.",
    "asthma-recommended-article-37b-title": "Mbinu ya inhaler - DPI",
    "asthma-recommended-article-37b-subtitle": "Vidokezo vya mbinu ya inhaler ya unga mkavu (DPI). Bila mbinu sahihi, unaweza kupata sehemu tu ya dozi.",
    "asthma-recommended-article-37c-title": "Mbinu ya inhaler - SMI",
    "asthma-recommended-article-37c-subtitle": "Vidokezo vya mbinu ya Inhaler ya Ukungu Laini (SMI). Bila mbinu sahihi, unaweza kupata sehemu tu ya dozi.",
    "asthma-recommended-article-37d-title": "Mbinu ya inhaler - nebulizer",
    "asthma-recommended-article-37d-subtitle": "Vidokezo vya mbinu ya nebulizer.",
    "asthma-recommended-article-38-title": "Kwa nini ninapaswa kutumia dawa yangu ya kudhibiti?",
    "asthma-recommended-article-38-subtitle": "Elewa jukumu muhimu la dawa za kudhibiti na kwa nini ni nguzo ya mpango wako wa usimamizi wa kibinafsi.",
    "asthma-recommended-article-39-title": "Madhara ya dawa za pumu",
    "asthma-recommended-article-39-subtitle": "Jifunze jinsi ya kutambua madhara ya kawaida na yasiyo ya kawaida, na hatua rahisi unazoweza kuchukua ili kuepuka madhara ya kawaida - thrush (maambukizi ya fangasi katika kinywa chako).",
    "asthma-recommended-article-39a-title": "Ninajuaje kama dawa zangu za pumu zinafanya kazi?",
    "asthma-recommended-article-39a-subtitle": "Dawa za kudhibiti zinaweza kuchukua siku hadi wiki kufika athari kamili. Fuatilia dalili zako kila siku ili kuona kama kuna uboreshaji na kama hakuna, zungumza na mtoa huduma wako.",
    "asthma-recommended-article-41-title": "Visababishi vya kushangaza",
    "asthma-recommended-article-41-subtitle": "Gundua visababishi visivyotarajiwa vya pumu vilivyojificha katika maisha yako ya kila siku, kutoka kwa NSAIDs (kama ibuprofen) hadi glasi yako ya divai. Kujua cha kutafuta, kunaweza kukusaidia kutambua visababishi hivi vya kushangaza.",
    "asthma-recommended-article-42-title": "Pumu na Vitu vya Msimu Vinavyosababisha Mzio/Poleni",
    "asthma-recommended-article-42-subtitle": "Pitia msimu wa poleni kwa urahisi: Tambua visababishi vyako mahususi vya poleni, elewa mifumo yao ya msimu, na jifunze jinsi ya kupunguza kuwa karibu navyo.",
    "asthma-recommended-article-43-title": "Pumu na Ubora wa Hewa",
    "asthma-recommended-article-43-subtitle": "Elewa kwamba ubora mbaya wa hewa unaweza kusababisha pumu. Jifunze jinsi ya kupitia siku za AQI ya juu na viwango vya AQI vinamaanisha nini.",
    "asthma-recommended-article-43a-title": "Pumu na Maambukizi ya Kupumua",
    "asthma-recommended-article-43a-subtitle": "Maambukizi ya kupumua ni visababishi vya kawaida vya pumu. Jinsi ya kuzuia na nini cha kufanya wakati yanatokea.",
    "asthma-recommended-article-43b-title": "Pumu na Wanyama",
    "asthma-recommended-article-43b-subtitle": "Wanyama/Wanyama wa nyumbani wanaweza kuwa kisababishi cha pumu. Jifunze jinsi ya kutambua mzio wa mnyama/mnyama wa nyumbani na hatua za kupunguza athari.",
    "asthma-recommended-article-43c-title": "Pumu na Moshi",
    "asthma-recommended-article-43c-subtitle": "Moto wa msitu na moshi wa tumbaku unaweza kusababisha pumu. Jifunze kuhusu hatua unazoweza kuchukua kupunguza kuwa karibu nao.",
    "asthma-recommended-article-43d-title": "Pumu na Hali ya Hewa",
    "asthma-recommended-article-43d-subtitle": "Visababishi vya kawaida vya hali ya hewa ni hewa baridi, hewa ya joto na unyevu, na mvua/dhoruba za radi. Chunguza kwa nini hizi zinaweza kusababisha pumu.",
    "asthma-recommended-article-43e-title": "Harufu Kali na Kemikali/Vifaa vya Usafi",
    "asthma-recommended-article-43e-subtitle": "Gundua harufu gani zinaweza kusababisha pumu yako na mambo ya kufikiria wakati wa kusafisha.",
    "asthma-recommended-article-43f-title": "Pumu na Vumbi/Wadudu wa Vumbi",
    "asthma-recommended-article-43f-subtitle": "Vumbi ni kisababishi cha kawaida cha pumu, lakini sababu inayofanya iwe kisababishi inaweza kukushangaza!",
    "asthma-recommended-article-43g-title": "Pumu na Kuvu",
    "asthma-recommended-article-43g-subtitle": "Kuvu inahitaji unyevu ili kukua, kwa hiyo kwa kawaida hupatikana katika maeneo yenye unyevu au yaliyolowa. Jifunze jinsi ya kuzuia kuvu nyumbani kwako.",
    "asthma-recommended-article-43h-title": "Pumu na Kichomi",
    "asthma-recommended-article-43h-subtitle": "Kichomi ni nini na kina uhusiano gani na pumu?",
    "blood-type": "Aina ya Damu",
    "device-data-month-chart-no-data": "Hakuna Data",
    "device-data-month-chart-daily-average": "Wastani wa Kila Siku",
    "term-information-not-found-header": "Hakuna Taarifa Zilizopatikana",
    "term-information-not-found-body": "Imeshindwa kupata taarifa zozote kuhusu mada hii",
    "term-information-disclaimer": "<strong>ANGALIZO:</strong> Taarifa zilizotolewa si ushauri wa matibabu. Ni kukusaidia kuelewa afya yako vizuri. Tafadhali wasiliana na mtoa huduma wako wa afya ikiwa una maswali kuhusu hali yako ya matibabu.",
    "term-information-view-on-medline": "Tazama kwenye MedlinePlus",
    "type": "Aina",
    "location": "Mahali",
    "description": "Maelezo",
    "performed-by": "Imefanywa Na",
    "verified-by": "Imethibitishwa Na",
    "normal-range": "Kiwango cha Kawaida",
    "more": "Zaidi",
    "procedure": "Utaratibu",
    "procedures": "Taratibu",
    "lab-report": "Ripoti ya Maabara",
    "service-performed": "Huduma Iliyotolewa",
    "services-performed": "Huduma Zilizotolewa",
    "device-data-month-chart-minutes": "Dakika",
    "device-data-month-chart-sleep": "Usingizi",
    "air-quality": "Ubora wa Hewa",
    "air-quality-home": "Ubora wa Hewa (Nyumbani)",
    "air-quality-work": "Ubora wa Hewa (Kazini)",
    "sedentary-time": "Muda wa Kukaa",
    "active-time": "Muda wa Shughuli",
    "lightly-active-time": "Muda wa Shughuli Nyepesi",
    "fairly-active-time": "Muda wa Shughuli za Wastani",
    "very-active-time": "Muda wa Shughuli Nyingi",
    "breathing-rate": "Kiwango cha Kupumua",
    "calories-burned": "Kalori Zilizochomwa",
    "elevated-heart-rate-time": "Muda wa Mapigo ya Moyo Yaliyopanda",
    "fat-burn-heart-rate-time": "Muda wa Kuchoma Mafuta",
    "cardio-heart-rate-time": "Muda wa Cardio",
    "peak-heart-rate-time": "Muda wa Kilele",
    "floors-climbed": "Sakafu Zilizopandwa",
    "heart-rate-variability": "Mabadiliko ya Mapigo ya Moyo",
    "sleep-time": "Muda wa Usingizi",
    "light-sleep-time": "Muda wa Usingizi Mwepesi",
    "deep-sleep-time": "Muda wa Usingizi Mzito",
    "rem-sleep-time": "Muda wa Usingizi wa REM",
    "spo2": "SpO2",
    "heart-rate-range": "Kiwango cha Mapigo ya Moyo",
    "max-heart-rate": "Mapigo ya Moyo ya Juu Zaidi",
    "core-sleep-time": "Muda wa Usingizi wa Msingi",
    "in-bed-time": "Muda Kitandani",
    "stand-time": "Muda wa Kusimama",
    "walking-heart-rate-average": "Wastani wa Mapigo ya Moyo Wakati wa Kutembea",
    "active-energy-burned": "Nishati ya Shughuli Iliyochomwa",
    "number-of-alcoholic-beverages": "Idadi ya Vinywaji vya Pombe",
    "active-calories": "Kalori za Shughuli",
    "resting-calories": "Kalori za Kupumzika",
    "total-calories": "Jumla ya Kalori",
    "min-heart-rate": "Mapigo ya Moyo ya Chini Zaidi",
    "average-heart-rate": "Wastani wa Mapigo ya Moyo",
    "max-stress-level": "Kiwango cha Juu Zaidi cha Msongo",
    "average-stress-level": "Wastani wa Kiwango cha Msongo",
    "total-stress-time": "Jumla ya Muda wa Msongo",
    "low-stress-time": "Muda wa Msongo Mdogo",
    "medium-stress-time": "Muda wa Msongo wa Wastani",
    "high-stress-time": "Muda wa Msongo Mkubwa",
    "awake-time": "Muda wa Kuamka",
    "sleep-score": "Alama ya Usingizi",
    "bpm": "bpm",
    "hours-abbreviation": "h",
    "minutes-abbreviation": "m",
    "points-until-next-badge": "Pointi {points} hadi beji inayofuata",
    "fitbit-wear-time": "Muda wa Kuvaa Fitbit",
    "my-badges": "Beji Zangu ({badges})",
    "new-badge-title": "Kazi nzuri!",
    "new-badge-text": "Umepata beji mpya!",
    "get-badge": "Pata Beji",
    "glucose-chart-no-data": "Hakuna vipimo vya sukari katika damu",
    "glucose-stats-range-label": "Kiwango cha Sukari katika Damu",
    "glucose-stats-avg-label": "Wastani wa Sukari katika Damu",
    "glucose-stats-steps-label": "Hatua",
    "glucose-stats-sleep-label": "Usingizi",
    "stress-level-title": "Msongo wa Jumla",
    "stress-level-min-label": "Hakuna Msongo",
    "stress-level-max-label": "Msongo Mkubwa Sana",
    "meal-type-meal": "Mlo",
    "meal-type-snack": "Vitafunio",
    "meal-type-drink": "Kinywaji",
    "meal-log-title": "Kumbukumbu ya Mlo",
    "meal-log-no-data": "Hakuna milo iliyorekodiwa",
    "meal-editor-time-input-label": "Wakati",
    "meal-editor-description-input-label": "Maelezo",
    "meal-editor-description-optional": "Hiari",
    "meal-editor-duplicate-timestamp-error": "Milo miwili hayawezi kuwa na wakati sawa.",
    "meal-editor-add-image": "Ongeza Picha",
    "meal-editor-image-upload-error": "Hitilafu imetokea wakati wa kupakia picha iliyochaguliwa. Tafadhali jaribu tena, tumia picha tofauti, au ondoa picha ili kuhifadhi.",
    "glucose-view-title": "Ufuatiliaji wa Sukari",
    "ai-assistant-loading": "Inashirikiana na data yako...",
    "ai-assistant-suggestion-avg-weekly-heart-rate": "Wastani wa mapigo ya moyo yangu kwa wiki iliyopita ni nini?",
    "ai-assistant-suggestion-highest-heart-rate-week": "Mapigo ya moyo yangu ya juu zaidi wiki hii yalikuwa yapi?",
    "ai-assistant-suggestion-graph-daily-steps-21-days": "Tengeneza grafu ya hatua zangu za kila siku kwa siku 21 zilizopita",
    "ai-assistant-suggestion-weekly-workouts-average-month": "Mazoezi mangapi kwa wiki nilipatia wastani mwezi huu?",
    "ai-assistant-suggestion-avg-monthly-blood-pressure": "Wastani wa shinikizo langu la damu kwa mwezi uliopita ni nini?",
    "ai-assistant-suggestion-daily-active-minutes-month": "Wastani wangu wa kila siku wa dakika za shughuli mwezi huu ni nini?",
    "ai-assistant-suggestion-resting-heart-rate-change-month": "Mapigo ya moyo yangu wakati wa kupumzika yamebadilika vipi katika mwezi uliopita?",
    "ai-assistant-suggestion-stand-ups-yesterday": "Nilisimama mara ngapi jana?",
    "ai-assistant-suggestion-graph-heart-rate-trends-workouts": "Unaweza kuchora grafu ya mwenendo wa mapigo ya moyo yangu wakati wa mazoezi wiki hii?",
    "ai-assistant-suggestion-sleep-7-days": "Usingizi wangu umekuwaje kwa siku 7 zilizopita?",
    "ai-assistant-suggestion-fall-asleep-time-2-weeks": "Kwa kawaida nililala saa ngapi katika wiki 2 zilizopita?",
    "ai-assistant-suggestion-sleep-quality-change-month": "Ubora wa usingizi wangu umebadilika vipi katika mwezi uliopita?",
    "ai-assistant-suggestion-last-tetanus-vaccine": "Chanjo yangu ya mwisho ya pepopunda ilikuwa lini?",
    "ai-assistant-suggestion-last-blood-test-lab-work": "Kipimo changu cha mwisho cha damu au kazi ya maabara ilikuwa lini?",
    "ai-assistant-suggestion-abnormal-lab-results": "Je, nina matokeo yoyote ya maabara yasiyo ya kawaida?",
    "ai-assistant-suggestion-last-cbc-test": "Kipimo changu cha mwisho cha idadi kamili ya damu (CBC) kilikuwa lini?",
    "ai-assistant-suggestion-glucose-a1c-levels-last-test": "Viwango vyangu vya sukari na A1c katika kipimo changu cha mwisho vilikuwa vipi?",
    "ai-assistant-suggestion-graph-cholesterol-trends": "Unaweza kunionyesha grafu ya jinsi viwango vyangu vya kolesteroli vimebadilika kwa muda?",
    "ai-assistant-suggestion-last-metabolic-panel": "Kipimo changu cha mwisho cha metaboliki kilifanywa lini?",
    "ai-assistant-suggestion-hemoglobin-levels-trend": "Mwenendo wa viwango vyangu vya hemoglobini ni upi?",
    "ai-assistant-suggestion-show-files": "Nionyeshe faili zangu.",
    "ai-assistant-suggestion-save-graph-to-files": "Hifadhi grafu kwenye faili zangu",
    "mindful-minutes": "Dakika za Utulivu",
    "therapy-minutes": "Dakika za Tiba",
    "insight-matrix-no-comparison-data": "Hakuna aina za data za kulinganisha zilizosanidiwa.",
    "allergylist-reactions": "Mizio",
    "points-abbreviation": "pts",
    "no-data": "Hakuna Data",
    "no-data-yet": "Bado hakuna data",
    "bp-low": "Chini",
    "bp-normal": "Kawaida",
    "bp-elevated": "Imepanda",
    "bp-stage1": "Hatua ya 1",
    "bp-stage2": "Hatua ya 2",
    "bp-crisis": "Dharura",
    "bp-unknown": "Haijulikani",
    "device-not-enabled": "@@DEVICE@@ haijawezeshwa kwa mradi huu.",
    "download-pdf-report": "Pakua Ripoti ya PDF",
    "connect-to-device": "Unganisha na @@DEVICE@@",
    "symptoms-and-treatments": "Dalili & Matibabu",
    "subsequent-evaluation-note": "Maelezo ya tathmini inayofuata",
    "summary": "Muhtasari",
    "device-activity": "Shughuli za Kifaa",
    "daily": "Kila Siku",
    "weekly": "Kila Wiki",
    "monthly": "Kila Mwezi",
    "bonus": "Bonasi",
    "syncing-data": "Inasawazisha data...",
    "health-connect-phr-sync-title": "Unganisha na Health Connect",
    "health-connect-phr-sync-prompt": "Chagua rekodi za afya za kusoma kutoka na kuandika kwenye Health Connect"
};

export default strings;


