let strings: { [key: string]: string } = {
    "back": "Atrás",
    "done": "Aceptar",
    "close": "Cerrar",
    "save": "Ahorrar",
    "add": "Agregar",
    "settings": "Configuración",
    "connect": "Conectar",
    "reconnect": "Volver a conectar",
    "refresh": "Actualizar",
    "remove": "Eliminar",
    "help": "Ayuda",
    "view": "Ver",
    "health-records": "Registros de salud",
    "connect-ehr-title-prefix": "Conectar ",
    "connect-ehr-title-divider": " o ",
    "connect-ehr-title-providers": "proveedor",
    "connect-ehr-title-health-plans": "plan de salud",
    "connect-ehr-connected": "¡Estamos recibiendo su información de EHR!",
    "connect-ehr-needs-attention": "Una de tus cuentas requiere atención.",
    "connect-ehr-text": "Sus registros electrónicos de salud son una fuente de información importante. Con ellos, usted podría ayudar a los investigadores de la salud a realizar nuevos descubrimientos. Conecte a su proveedor o a su plan de salud (por ejemplo: Medicare) con @@PROJECT_NAME@@.",
    "connect-ehr-text-connected": "Gracias por compartir tus datos de EHR con @@PROJECT_NAME@@. Conecta a otro proveedor para compartir más datos o administrar tus conexiones de EHR.",
    "connect-ehr-not-enabled": "EHR enlacando no está habilitado para este proyecto.",
    "search-for-provider": "Encontrar a mi Proveedor",
    "expired-reconnect": "Volver a conectar",
    "connected": "Conectado",
    "search": "Buscar",
    "connect-fitbit-intro": "Si ya tiene una cuenta Fitbit, puede compartir información desde allí. Para empezar, presione el siguiente botón para ingresar a su cuenta de Fitbit:",
    "connect-fitbit-button": "Conectar a Fitbit",
    "received-fitbit-data": "¡Estamos recibiendo su información de Fitbit!",
    "connect-garmin-intro": "Si ya tiene una cuenta Garmin, puede compartir información desde allí. Para empezar, presione el siguiente botón para ingresar a su cuenta de Garmin:",
    "connect-garmin-button": "Conectar a Garmin",
    "received-garmin-data": "¡Estamos recibiendo su información de Garmin!",
    "downloading-data": "Descargando datos...",
    "downloading-data-menu": "Descargando Datos",
    "all-tasks-complete": "¡Todas las tareas terminadas!",
    "view-all": "Ver todo",
    "tasks": "Tareas",
    "incomplete-tasks": "Tareas incompletas",
    "completed-tasks": "Tareas completadas",
    "overdue": "Vencidos",
    "due-today": "Vence hoy",
    "due-tomorrow": "Vence mañana",
    "due": "Vence",
    "due-in": "Vencido en",
    "days": "dias",
    "notifications": "Notificaciones",
    "support": "Soporte",
    "all-notifications": "Todas las notificaciones",
    "steps": "Pasos",
    "resting-heart-rate": "Ritmo cardíaco en reposo",
    "distance-traveled": "Distancia Viajada",
    "google-fit-share": "Toca para compartir datos de condición físic",
    "devices": "Dispositivos",
    "last-sync": "Última sincronización",
    "completed": "Completadas",
    "ehr-intro": "Sus registros de salud electrónicos son fuentes importantes de información. Pueden ayudar a investigadores hacer nuevos descubrimientos.",
    "external-accounts-title-divider": " / ",
    "external-accounts-title-providers": "Proveedores",
    "external-accounts-title-health-plans": "Planes de Salud",
    "external-accounts-title-devices": "Dispositivos",
    "external-accounts-error": "Una de tus cuentas requiere atención",
    "external-accounts-loading": "Actualmente tus datos se están descargando de tus planes de salud y proveedores vinculados. Por favor, vuelve a consultar en unos momentos para ver tus datos.",
    "external-account-authorization-expired": "Venció la autorización",
    "external-account-fetching-data": "Recuperando datos",
    "external-account-deleting": "Eliminando...",
    "external-account-last-updated": "Última actualización",
    "external-account-error": "Error imprevisto",
    "external-account-reconnect": "Volver a conectar",
    "external-account-refresh": "Actualizar",
    "external-account-remove": "Eliminar",
    "device-data-no-data": "Si ha conectado Apple Health, Google Fit, Fitbit o Garmin, vuelva más tarde para ver sus datos.",
    "no-notifications-received": "No se recibieron notificaciones.",
    "next-button-text": "Siguiente",
    "lab-results-title": "Resultados de laboratorio",
    "medications-title": "Medicamentos",
    "immunizations-title": "Vacunas",
    "reports-title": "Informes",
    "allergies-title": "Alergias",
    "conditions-title": "Enfermedades",
    "procedures-title": "Procedimientos",
    "app-download-title": "Siguiente: Descarga la aplicación",
    "app-download-subtitle": "La descarga de la aplicación MyDataHelps hace que sea aún más fácil participar en @@PROJECT_NAME@@.",
    "app-download-google-play-link-alt": "Descargar en Google Play Store",
    "app-download-app-store-link-alt": "Descargar en la tienda de aplicaciones de Apple",
    "start": "Inicio",
    "resume": "Continuar",
    "start-survey": "Iniciar encuesta",
    "resume-survey": "Reanudar encuesta",
    "30-day-average": "Promedio de 30 días",
    "today": "Hoy",
    "yesterday": "Ayer",
    "tap-to-log-today": "Pulse aquí para registrar sus síntomas o tratamientos.",
    "mild": "Leve",
    "moderate": "Moderado",
    "severe": "Grave",
    "severe-shortened": "graves",
    "moderate-shortened": "mod",
    "mild-shortened": "leves",
    "log-todays-symptoms": "Registra los síntomas de hoy",
    "todays-log": "Registro de hoy",
    "symptoms": "Síntomas",
    "treatments": "Tratamientos",
    "symptoms-experiencing-today": "¿Qué síntomas está experimentando?",
    "symptoms-experiencing-previous": "¿Qué síntomas estaba experimentando?",
    "treatments-experiencing-today": "¿Qué tratamientos ha hecho?",
    "treatments-experiencing-previous": "¿Qué tratamientos hizo?",
    "feeling-overall-today": "¿Cómo se siente en general?",
    "feeling-overall-previous": "¿Cómo se sentía en general?",
    "additional-notes": "¿Alguna nota adicional?",
    "how-severe-is": "¿Cuál es la gravedad de su",
    "how-severe-was": "¿Cuál era la gravedad de su",
    "clear-symptom": "Eliminar síntomas",
    "add-notes": "Agregar notas",
    "notes": "Notas",
    "enter-symptom-name": "Ingresar el nombre del síntoma",
    "enter-treatment-name": "Ingresar el nombre del tratamiento",
    "severity-tracking-none": "No hacer un seguimiento de la gravedad",
    "severity-tracking-3point": "Calificación leve/moderado/grave",
    "severity-tracking-10point": "Calificación de 1 a 10 puntos",
    "muted": "Silenciado",
    "not-muted": "No silenciado",
    "delete": "Eliminar",
    "severity": "Gravedad",
    "item-delete-warning": "Advertencia: Si continúa, se eliminarán de forma permanente los siguientes elementos y todos los datos asociados de sus registros. Si no desea eliminar estos elementos, seleccione \"Cancelar\".",
    "unsaved-changes": "Cambios no guardados",
    "daily-overall-experience": "Experiencia general diaria",
    "average": "Promedio",
    "include-symptoms": "Incluir síntomas",
    "select-symptoms": "Seleccionar síntomas",
    "include-treatments": "Incluir tratamientos",
    "select-treatments": "Seleccionar tratamientos",
    "download-mydatahelps": "Descargar MyDataHelps",
    "apple-health-troubleshooting-intro": "Si no aprobó o ha desactivado el uso compartido de sus datos de Apple Health y desea habilitarlo, siga estos pasos:",
    "apple-health-troubleshooting-li-1": "Abra la aplicación \"Ajustes\"",
    "apple-health-troubleshooting-li-2": "Seleccione \"Privacidad\"",
    "apple-health-troubleshooting-li-3": "Seleccione \"Salud\"",
    "apple-health-troubleshooting-li-4": "Seleccione \"MyDataHelps\"",
    "apple-health-troubleshooting-li-5": "Habilite las categorías de datos que le gustaría compartir",
    "connect-devices-title": "Conectar aparatos",
    "connect-devices-subtitle": "Comparta datos de sus dispositivos portátiles, aplicaciones y otros aparatos.",
    "how-to-enable": "Cómo activar",
    "new-points-title": "¡Bien hecho!",
    "new-points-text": "Se le han otorgado puntos por lo siguiente:",
    "new-points-next-reward-prefix": "Ahora necesitas ",
    "new-points-next-reward-suffix": " puntos para desbloquear tu próxima recompensa.",
    "new-points-done-button-text": "Hecho",
    "resource-default-button-text": "Abierto",
    "inbox-message-completed-status": "VISTO",
    "inbox-resource-completed-status": "VISTO",
    "inbox-survey-completed-status": "TERMINADO",
    "inbox-history-view-title": "Historial de Bandeja de Entrada",
    "inbox-history-view-empty-text": "No tienes elementos en el historial de bandeja de entrada.",
    "inbox-message-view-related-resources-title": "Relacionado",
    "inbox-view-title": "Bandeja de Entrada",
    "inbox-view-empty-text": "No tienes nuevos elementos en tu bandeja de entrada.",
    "inbox-view-messages-title": "Mensajes",
    "inbox-view-surveys-title": "Encuestas",
    "inbox-view-resources-title": "Recursos",
    "inbox-view-recently-completed-title": "Reciente",
    "inbox-view-recently-completed-empty-text": "No tienes elementos recientemente completados en tu bandeja de entrada.",
    "inbox-view-history-button-text": "Ver historial de bandeja de entrada",
    "recent-daily-data-bar-chart-subtitle": "Últimos 7 días",
    "recent-daily-data-bar-chart-no-data": "Sin datos",
    "resource-list-empty-text": "No se encontraron recursos.",
    "asthma-symptom-level-none": "Sin síntomas",
    "asthma-symptom-level-mild": "Síntomas leves",
    "asthma-symptom-level-moderate": "Síntomas moderados",
    "asthma-symptom-level-severe": "Síntomas graves",
    "asthma-control-calendar-daily-entry-missed": "Entrada diaria omitida",
    "asthma-control-calendar-not-logged-yet": "No ingresado todavía",
    "asthma-control-calendar-log-entries-symptoms-label": "Síntomas",
    "asthma-control-calendar-log-entries-impacts-label": "Impactos",
    "asthma-control-calendar-log-entries-triggers-label": "Disparadores"
};

export default strings;