let strings: { [key: string]: string } = {
    "back": "Quay lại",
    "done": "Hoàn thành",
    "close": "Đóng",
    "save": "Lưu",
    "add": "Thêm",
    "edit": "Chỉnh sửa",
    "cancel": "Hủy",
    "clear": "Xóa",
    "settings": "Cài đặt",
    "connect": "Kết nối",
    "reconnect": "Kết nối lại",
    "setup": "Thiết lập",
    "refresh": "Làm mới",
    "remove": "Xóa",
    "help": "Trợ giúp",
    "view": "Xem",
    "health-records": "Hồ sơ sức khỏe",
    "connect-ehr-title-prefix": "Kết nối ",
    "connect-ehr-title-divider": " hoặc ",
    "connect-ehr-title-providers": "Nhà cung cấp",
    "connect-ehr-title-health-plans": "Kế hoạch sức khỏe",
    "connect-ehr-connected": "Chúng tôi đang nhận dữ liệu EHR của bạn!",
    "connect-ehr-needs-attention": "Một trong các tài khoản của bạn cần được chú ý.",
    "connect-ehr-text": "Kết nối nhà cung cấp hoặc kế hoạch sức khỏe của bạn để xem kết quả xét nghiệm, tình trạng, thuốc và nhiều thông tin khác.",
    "connect-ehr-text-connected": "Kết nối với nhà cung cấp khác để chia sẻ thêm dữ liệu hoặc quản lý kết nối EHR của bạn.",
    "connect-ehr-not-enabled": "Liên kết EHR không được kích hoạt cho dự án này.",
    "search-for-provider": "Tìm kiếm nhà cung cấp hoặc kế hoạch sức khỏe",
    "request-add": "Yêu cầu thêm",
    "expired-reconnect": "Kết nối đã hết hạn. Vui lòng kết nối lại.",
    "connect-error-reconnect": "Lỗi không mong muốn. Vui lòng kết nối lại.",
    "connected": "Đã kết nối",
    "search": "Tìm kiếm",
    "connect-fitbit-intro": "Bạn có thể chia sẻ dữ liệu từ tài khoản Fitbit nếu bạn có. Để bắt đầu, nhấp hoặc chạm vào bên dưới để đăng nhập bằng thông tin đăng nhập Fitbit của bạn.",
    "connect-fitbit-button": "Kết nối Fitbit",
    "received-fitbit-data": "Chúng tôi đang nhận dữ liệu Fitbit của bạn!",
    "connect-garmin-intro": "Bạn có thể chia sẻ dữ liệu từ tài khoản Garmin nếu bạn có. Để bắt đầu, nhấp hoặc chạm vào bên dưới để đăng nhập bằng thông tin đăng nhập Garmin của bạn.",
    "connect-garmin-button": "Kết nối Garmin",
    "received-garmin-data": "Chúng tôi đang nhận dữ liệu Garmin của bạn!",
    "connect-oura-intro": "Bạn có thể chia sẻ dữ liệu từ tài khoản Oura nếu bạn có. Để bắt đầu, nhấp hoặc chạm vào bên dưới để đăng nhập bằng thông tin đăng nhập Oura của bạn.",
    "connect-oura-button": "Kết nối Oura",
    "received-oura-data": "Chúng tôi đang nhận dữ liệu Oura của bạn!",
    "connect-dexcom-intro": "Bạn có thể chia sẻ dữ liệu từ tài khoản Dexcom nếu bạn có. Để bắt đầu, nhấp hoặc chạm vào bên dưới để đăng nhập bằng thông tin đăng nhập Dexcom của bạn.",
    "connect-dexcom-button": "Kết nối Dexcom",
    "received-dexcom-data": "Chúng tôi đang nhận dữ liệu Dexcom của bạn!",
    "downloading-data": "Đang tải dữ liệu...",
    "downloading-data-menu": "Đang tải dữ liệu",
    "empty-tasks-incomplete": "Hiện không có nhiệm vụ mở nào để hiển thị.",
    "empty-tasks-complete": "Các nhiệm vụ đã hoàn thành sẽ được hiển thị ở đây.",
    "view-all": "Xem tất cả",
    "tasks": "Nhiệm vụ",
    "incomplete-tasks": "Nhiệm vụ chưa hoàn thành",
    "completed-tasks": "Nhiệm vụ đã hoàn thành",
    "overdue": "Quá hạn",
    "due-today": "Đến hạn hôm nay",
    "due-tomorrow": "Đến hạn ngày mai",
    "due": "Đến hạn",
    "due-in": "Đến hạn trong",
    "days": "ngày",
    "notifications": "Thông báo",
    "support": "Hỗ trợ",
    "all-notifications": "Tất cả thông báo",
    "steps": "Bước",
    "resting-heart-rate": "Nhịp tim lúc nghỉ",
    "distance-traveled": "Khoảng cách đã đi",
    "google-fit-share": "Chạm để chia sẻ dữ liệu thể dục",
    "devices": "Thiết bị",
    "last-sync": "Đồng bộ lần cuối",
    "completed": "Đã hoàn thành",
    "ehr-intro-search": "Tìm kiếm bằng cách nhập tên nhà cung cấp hoặc cổng thành viên cho nhà cung cấp dịch vụ chăm sóc sức khỏe hoặc kế hoạch sức khỏe của bạn.",
    "external-accounts-title-divider": " / ",
    "external-accounts-title-providers": "Nhà cung cấp",
    "external-accounts-title-health-plans": "Kế hoạch sức khỏe",
    "external-accounts-title-devices": "Thiết bị",
    "external-accounts-error": "Một trong các tài khoản của bạn cần được chú ý",
    "external-accounts-loading": "Dữ liệu của bạn hiện đang được tải xuống từ các kế hoạch sức khỏe và nhà cung cấp đã liên kết. Vui lòng kiểm tra lại sau vài phút để xem dữ liệu của bạn.",
    "external-account-authorization-expired": "Ủy quyền đã hết hạn",
    "external-account-fetching-data": "Đang truy xuất dữ liệu...",
    "external-account-deleting": "Đang xóa...",
    "external-account-last-updated": "Cập nhật lần cuối",
    "external-account-error": "Lỗi không mong muốn",
    "external-account-reconnect": "Kết nối lại",
    "external-account-refresh": "Làm mới",
    "external-account-remove": "Xóa",
    "device-data-no-data": "Nếu bạn đã kết nối Apple Health, Google Fit, Fitbit hoặc Garmin, hãy kiểm tra lại sau để xem dữ liệu của bạn.",
    "no-notifications-received": "Không có thông báo nào nhận được",
    "next-button-text": "Tiếp theo",
    "lab-results-title": "Kết quả xét nghiệm",
    "medications-title": "Thuốc",
    "immunizations-title": "Tiêm chủng",
    "reports-title": "Báo cáo",
    "allergies-title": "Dị ứng",
    "conditions-title": "Tình trạng",
    "procedures-title": "Thủ tục",
    "app-download-title": "Tiếp theo: Tải ứng dụng",
    "app-download-subtitle": "Tải ứng dụng MyDataHelps giúp bạn dễ dàng tham gia vào @@PROJECT_NAME@@ hơn.",
    "app-download-google-play-link-alt": "Tải xuống trên Google Play Store",
    "app-download-app-store-link-alt": "Tải xuống trên Apple App Store",
    "start": "Bắt đầu",
    "resume": "Tiếp tục",
    "start-survey": "Bắt đầu khảo sát",
    "resume-survey": "Tiếp tục khảo sát",
    "30-day-average": "Trung bình 30 ngày",
    "today": "Hôm nay",
    "yesterday": "Hôm qua",
    "tap-to-log-today": "Chạm vào đây để ghi lại các triệu chứng hoặc điều trị của bạn!",
    "mild": "Nhẹ",
    "moderate": "Trung bình",
    "severe": "Nặng",
    "severe-shortened": "nặng",
    "moderate-shortened": "t.bình",
    "mild-shortened": "nhẹ",
    "log-todays-symptoms": "Ghi lại triệu chứng hôm nay",
    "todays-log": "Nhật ký hôm nay",
    "symptoms": "Triệu chứng",
    "treatments": "Điều trị",
    "symptoms-experiencing-today": "Bạn đang gặp những triệu chứng gì?",
    "symptoms-experiencing-previous": "Bạn đã gặp những triệu chứng gì?",
    "treatments-experiencing-today": "Bạn đã thực hiện những điều trị nào?",
    "treatments-experiencing-previous": "Bạn đã thực hiện những điều trị nào?",
    "feeling-overall-today": "Nhìn chung bạn cảm thấy thế nào?",
    "feeling-overall-previous": "Nhìn chung bạn đã cảm thấy thế nào?",
    "additional-notes": "Ghi chú bổ sung?",
    "how-severe-is": "Mức độ nghiêm trọng của",
    "how-severe-was": "Mức độ nghiêm trọng của",
    "clear-symptom": "Xóa triệu chứng",
    "add-notes": "Thêm ghi chú",
    "notes": "Ghi chú",
    "enter-symptom-name": "Nhập tên triệu chứng",
    "enter-treatment-name": "Nhập tên điều trị",
    "severity-tracking-none": "Không theo dõi mức độ nghiêm trọng",
    "severity-tracking-3point": "Đánh giá Nhẹ / Trung bình / Nặng",
    "severity-tracking-10point": "Đánh giá 1 - 10 điểm",
    "muted": "Đã tắt tiếng",
    "not-muted": "Không tắt tiếng",
    "delete": "Xóa",
    "severity": "Mức độ nghiêm trọng",
    "item-delete-warning": "Cảnh báo: Tiếp tục sẽ xóa vĩnh viễn các mục bên dưới và tất cả dữ liệu liên quan khỏi nhật ký của bạn. Nếu bạn không muốn xóa các mục này, hãy chọn \"Hủy\".",
    "unsaved-changes": "Thay đổi chưa lưu",
    "daily-overall-experience": "Trải nghiệm tổng thể hàng ngày",
    "average": "Trung bình",
    "include-symptoms": "Bao gồm triệu chứng",
    "select-symptoms": "Chọn triệu chứng",
    "include-treatments": "Bao gồm điều trị",
    "select-treatments": "Chọn điều trị",
    "download-mydatahelps": "Tải MyDataHelps",
    "connect-devices-title": "Kết nối thiết bị",
    "connect-devices-text": "Chia sẻ dữ liệu từ thiết bị đeo, ứng dụng và các thiết bị khác của bạn.",
    "apple-health-troubleshooting-intro": "Nếu bạn chưa phê duyệt hoặc đã tắt chia sẻ dữ liệu Apple Health và muốn bật nó, hãy làm theo các bước sau:",
    "apple-health-troubleshooting-li-1": "Mở ứng dụng \"Cài đặt\"",
    "apple-health-troubleshooting-li-2": "Chọn \"Quyền riêng tư\"",
    "apple-health-troubleshooting-li-3": "Chọn \"Sức khỏe\"",
    "apple-health-troubleshooting-li-4": "Chọn \"MyDataHelps\"",
    "apple-health-troubleshooting-li-5": "Bật các danh mục dữ liệu bạn muốn chia sẻ",
    "how-to-enable": "Cách bật",
    "new-points-title": "Làm tốt lắm!",
    "new-points-text": "Bạn đã được trao điểm cho những điều sau:",
    "new-points-next-reward-prefix": "Bây giờ bạn cần ",
    "new-points-next-reward-suffix": " điểm để mở khóa phần thưởng tiếp theo của bạn.",
    "new-points-done-button-text": "Hoàn thành",
    "systolic-average": "Trung bình tâm thu",
    "diastolic-average": "Trung bình tâm trương",
    "highest-systolic": "Tâm thu cao nhất",
    "lowest-systolic": "Tâm thu thấp nhất",
    "resource-default-button-text": "Mở",
    "inbox-message-completed-status": "ĐÃ XEM",
    "inbox-resource-completed-status": "ĐÃ XEM",
    "inbox-survey-completed-status": "ĐÃ HOÀN THÀNH",
    "inbox-history-view-title": "Lịch sử hộp thư đến",
    "inbox-history-view-empty-text": "Bạn không có mục nào trong lịch sử hộp thư đến.",
    "inbox-message-view-related-resources-title": "Liên quan",
    "inbox-view-title": "Hộp thư đến",
    "inbox-view-empty-text": "Bạn không có mục mới nào trong hộp thư đến.",
    "inbox-view-messages-title": "Tin nhắn",
    "inbox-view-surveys-title": "Khảo sát",
    "inbox-view-resources-title": "Tài nguyên",
    "inbox-view-recently-completed-title": "Gần đây",
    "inbox-view-recently-completed-empty-text": "Bạn không có mục nào đã hoàn thành gần đây trong hộp thư đến.",
    "inbox-view-history-button-text": "Xem lịch sử hộp thư đến",
    "choose-report-month": "Chọn tháng báo cáo",
    "include-overall-experience": "Bao gồm trải nghiệm tổng thể hàng ngày",
    "include-notes": "Bao gồm ghi chú",
    "create-report": "Tạo báo cáo PDF",
    "reports": "Báo cáo",
    "recent-daily-data-bar-chart-subtitle": "7 ngày qua",
    "recent-daily-data-bar-chart-no-data": "Không có dữ liệu",
    "resource-list-empty-text": "Không tìm thấy tài nguyên nào.",
    "asthma-symptom-level-none": "Không có triệu chứng",
    "asthma-symptom-level-mild": "Triệu chứng nhẹ",
    "asthma-symptom-level-moderate": "Triệu chứng trung bình",
    "asthma-symptom-level-severe": "Triệu chứng nặng",
    "asthma-symptom-difficulty-breathing": "Khó thở",
    "asthma-symptom-wheezing": "Thở khò khè",
    "asthma-symptom-coughing": "Ho",
    "asthma-symptom-chest-tightness": "Tức ngực hoặc áp lực",
    "asthma-impact-limit-daily-activity": "Hạn chế hoạt động hàng ngày của bạn",
    "asthma-impact-waking-at-night": "Thức giấc vào ban đêm",
    "asthma-impact-using-rescue-inhaler": "Sử dụng ống hít cứu hộ",
    "asthma-trigger-cold-illness": "Cảm lạnh/bệnh do virus",
    "asthma-trigger-animal-exposure": "Tiếp xúc với động vật",
    "asthma-trigger-seasonal-allergens": "Dị ứng theo mùa/phấn hoa",
    "asthma-trigger-exercise": "Tập thể dục",
    "asthma-trigger-smoke": "Khói",
    "asthma-trigger-weather-changes": "Thay đổi thời tiết cực đoan",
    "asthma-trigger-air-pollution": "Ô nhiễm không khí",
    "asthma-trigger-strong-smells": "Mùi mạnh",
    "asthma-trigger-chemicals": "Hóa chất/đồ dùng vệ sinh",
    "asthma-trigger-dust": "Bụi",
    "asthma-trigger-mold": "Nấm mốc",
    "asthma-trigger-dust-mites": "Mạt bụi",
    "asthma-trigger-rodents": "Động vật gặm nhấm",
    "asthma-trigger-cockroaches": "Gián",
    "asthma-trigger-nsaid": "NSAID/Aspirin",
    "asthma-trigger-beta-blocker": "Thuốc chẹn beta",
    "asthma-trigger-heartburn": "Ợ nóng",
    "asthma-trigger-red-wine": "Rượu vang đỏ",
    "asthma-trigger-new-foods": "Thực phẩm mới",
    "asthma-trigger-cooked-without-ventilation": "Nấu ăn (không thông gió)",
    "asthma-trigger-pet-in-bed": "Thú cưng trên giường của bạn",
    "asthma-trigger-incense-or-candle": "Nến/hương",
    "asthma-data-status-out-of-range": "Ngoài phạm vi",
    "asthma-data-status-in-range": "Trong phạm vi",
    "asthma-data-status-offline": "Ngoại tuyến",
    "asthma-data-status-establishing": "Đang thiết lập",
    "asthma-data-status-not-determined": "Chưa thiết lập đường cơ sở",
    "asthma-data-status-not-found": "Không có dữ liệu được ghi lại",
    "asthma-data-status-not-configured": "Chưa được cấu hình",
    "asthma-control-calendar-daily-entry-missed": "Bỏ lỡ mục nhập hàng ngày",
    "asthma-control-calendar-not-logged-yet": "Chưa ghi lại",
    "asthma-control-calendar-log-entries-symptoms-label": "Triệu chứng",
    "asthma-control-calendar-log-entries-impacts-label": "Tác động",
    "asthma-control-calendar-log-entries-triggers-label": "Yếu tố kích phát",
    "asthma-control-status-header-complete-daily-entry": "Hoàn thành mục nhập hàng ngày của bạn.",
    "asthma-control-status-header-multiple-out-of-range": "Nhiều điểm dữ liệu đang |||ngoài mức bình thường của bạn|||.",
    "asthma-control-status-header-abnormal-heart-rate": "Nhịp tim lúc nghỉ của bạn đang |||cao hơn mức bình thường của bạn|||.",
    "asthma-control-status-header-abnormal-respiratory-rate": "Tốc độ hô hấp của bạn đang |||cao hơn mức bình thường của bạn|||.",
    "asthma-control-status-header-abnormal-steps": "Hoạt động của bạn đang |||thấp hơn mức bình thường của bạn|||.",
    "asthma-control-status-header-abnormal-sleep": "Rối loạn giấc ngủ của bạn đang |||cao hơn mức bình thường của bạn|||.",
    "asthma-control-status-header-abnormal-blood-oxygen": "Mức oxy trong máu của bạn đang |||thấp hơn mức bình thường của bạn|||.",
    "asthma-control-status-header-abnormal-home-aqi": "Chỉ số chất lượng không khí tại nhà của bạn là |||{aqi}|||.",
    "asthma-control-status-header-abnormal-work-aqi": "Chỉ số chất lượng không khí tại nơi làm việc của bạn là |||{aqi}|||.",
    "asthma-control-status-header-no-data": "Thêm mục nhập hàng ngày để đánh giá kiểm soát hen suyễn của bạn.",
    "asthma-control-status-header-no-data-caregiver": "Thêm mục nhập hàng ngày để đánh giá kiểm soát hen suyễn của {name}.",
    "asthma-control-status-header-not-determined": "Cần thêm mục nhập hàng ngày để đánh giá kiểm soát hen suyễn của bạn.",
    "asthma-control-status-header-not-determined-caregiver": "Cần thêm mục nhập hàng ngày để đánh giá kiểm soát hen suyễn của {name}.",
    "asthma-control-status-header-controlled": "Dựa trên các mục nhập của bạn, hen suyễn của bạn đang |||được kiểm soát|||.",
    "asthma-control-status-header-controlled-caregiver": "Dựa trên các mục nhập, hen suyễn của {name} đang |||được kiểm soát|||.",
    "asthma-control-status-header-not-controlled": "Dựa trên các mục nhập của bạn, hen suyễn của bạn đang |||không được kiểm soát|||.",
    "asthma-control-status-header-not-controlled-caregiver": "Dựa trên các mục nhập, hen suyễn của {name} đang |||không được kiểm soát|||.",
    "asthma-control-status-header-not-controlled-stat-symptom-days": "Ngày có triệu chứng",
    "asthma-control-status-header-not-controlled-stat-rescue-inhaler": "Ống hít cứu hộ",
    "asthma-control-status-header-not-controlled-stat-limited-activity": "Hoạt động hạn chế",
    "asthma-control-status-header-not-controlled-stat-awakenings": "Thức giấc",
    "asthma-action-plan-manager-title": "Kế hoạch hành động hen suyễn",
    "asthma-action-plan-manager-instructions": "Lưu ảnh kế hoạch hành động hen suyễn của bạn để dễ tham khảo.",
    "asthma-action-plan-manager-instructions-caregiver": "Lưu ảnh kế hoạch hành động hen suyễn của {name} để dễ tham khảo.",
    "asthma-action-plan-manager-learn-more": "Kế hoạch hành động hen suyễn là gì?",
    "asthma-action-plan-manager-edit-button-text": "Chỉnh sửa",
    "asthma-action-plan-manager-not-found-text": "Chạm để thêm ảnh",
    "asthma-biometrics-title": "Sức khỏe & Hoạt động",
    "asthma-biometrics-daytime-resting-heart-rate-label": "Nhịp tim lúc nghỉ (Ngày)",
    "asthma-biometrics-nighttime-resting-heart-rate-label": "Nhịp tim lúc nghỉ (Đêm)",
    "asthma-biometrics-beats-per-minute-units": "BPM",
    "asthma-biometrics-respiratory-rate-label": "Tốc độ hô hấp",
    "asthma-biometrics-breaths-per-minute-units": "BPM",
    "asthma-biometrics-steps-label": "Bước",
    "asthma-biometrics-daytime-blood-oxygen-level-label": "Độ bão hòa oxy (Ngày)",
    "asthma-biometrics-nighttime-blood-oxygen-level-label": "Độ bão hòa oxy (Đêm)",
    "asthma-biometrics-percent-units": "%",
    "asthma-biometrics-sleep-disturbances-label": "Rối loạn giấc ngủ",
    "asthma-air-qualities-title": "Chất lượng không khí",
    "asthma-air-qualities-setup-button-text": "+ Thiết lập",
    "asthma-air-qualities-home-aqi-label": "AQI (Nhà)",
    "asthma-air-qualities-work-aqi-label": "AQI (Nơi làm việc)",
    "asthma-alert-takeover-notice-instructions": "Hãy dành chút thời gian để ghi lại bất kỳ triệu chứng hen suyễn nào trong mục nhập hàng ngày.",
    "asthma-alert-takeover-notice-add-entry-button-text": "+ Mục nhập hàng ngày",
    "asthma-alert-takeover-notice-not-now-button-text": "Không phải bây giờ",
    "asthma-log-entry-details-not-editable": "Bỏ lỡ mục nhập hàng ngày",
    "asthma-log-entry-details-not-logged-yet": "Chưa ghi lại",
    "asthma-log-entry-details-edit-button-text": "Chỉnh sửa",
    "asthma-log-entry-details-add-button-text": "Ghi lại mục nhập",
    "asthma-log-entry-details-symptoms-label": "Triệu chứng",
    "asthma-log-entry-details-impacts-label": "Tác động",
    "asthma-log-entry-details-triggers-label": "Yếu tố kích phát",
    "asthma-log-entry-details-component-no-data": "Không có {dataType} được ghi lại",
    "asthma-log-entry-header-today-log-label": "Hôm nay",
    "asthma-log-entry-header-yesterday-log-label": "Hôm qua",
    "asthma-log-entry-header-not-logged-yet": "Chưa ghi lại",
    "asthma-log-entry-header-add-button-text": "Ghi lại mục nhập",
    "asthma-activity-view-title": "Hoạt động",
    "asthma-activity-view-chart-title": "Bước",
    "asthma-activity-view-alert-message": "Hoạt động của bạn thấp hơn mức bình thường của bạn.",
    "asthma-alert-takeover-message": "Nhiều điểm dữ liệu đang nằm ngoài mức bình thường của bạn.",
    "asthma-air-quality-view-title": "Chất lượng không khí",
    "asthma-air-quality-view-home-aqi-chart-title": "Chất lượng không khí (Nhà)",
    "asthma-air-quality-view-home-aqi-alert-message": "AQI tại nhà của bạn không lành mạnh.",
    "asthma-air-quality-view-work-aqi-chart-title": "Chất lượng không khí (Nơi làm việc)",
    "asthma-air-quality-view-work-aqi-alert-message": "AQI tại nơi làm việc của bạn không lành mạnh.",
    "asthma-heart-and-lungs-view-title": "Tim & Phổi",
    "asthma-heart-and-lungs-view-dhr-chart-title": "Nhịp tim lúc nghỉ (Ngày)",
    "asthma-heart-and-lungs-view-dhr-alert-message": "Nhịp tim lúc nghỉ ban ngày của bạn cao hơn mức bình thường của bạn.",
    "asthma-heart-and-lungs-view-nhr-chart-title": "Nhịp tim lúc nghỉ (Đêm)",
    "asthma-heart-and-lungs-view-nhr-alert-message": "Nhịp tim lúc nghỉ ban đêm của bạn cao hơn mức bình thường của bạn.",
    "asthma-heart-and-lungs-view-rr-chart-title": "Tốc độ hô hấp",
    "asthma-heart-and-lungs-view-rr-alert-message": "Tốc độ hô hấp của bạn cao hơn mức bình thường của bạn.",
    "asthma-heart-and-lungs-view-dbol-chart-title": "Oxy trong máu (Ngày)",
    "asthma-heart-and-lungs-view-dbol-alert-message": "Oxy trong máu ban ngày của bạn thấp hơn mức bình thường của bạn.",
    "asthma-heart-and-lungs-view-nbol-chart-title": "Oxy trong máu (Đêm)",
    "asthma-heart-and-lungs-view-nbol-alert-message": "Oxy trong máu ban đêm của bạn thấp hơn mức bình thường của bạn.",
    "asthma-sleep-view-title": "Giấc ngủ",
    "asthma-sleep-view-chart-title": "Rối loạn giấc ngủ",
    "asthma-sleep-view-alert-message": "Rối loạn giấc ngủ của bạn cao hơn mức bình thường của bạn.",
    "asthma-log-entry-editor-view-symptom-level-title": "Mức độ triệu chứng",
    "asthma-log-entry-editor-view-select-one-subtitle": "Chọn một",
    "asthma-log-entry-editor-view-select-all-subtitle": "Chọn tất cả những gì áp dụng",
    "asthma-log-entry-editor-view-symptoms-title": "Triệu chứng",
    "asthma-log-entry-editor-view-impacts-title": "Tác động",
    "asthma-log-entry-editor-view-triggers-title": "Yếu tố kích phát",
    "asthma-air-quality-description-unhealthy": "Không lành mạnh",
    "asthma-air-quality-description-very-unhealthy": "Rất không lành mạnh",
    "asthma-air-quality-description-hazardous": "Nguy hiểm",
    "asthma-recommended-article-21-title": "Làm thế nào để kiểm soát hen suyễn của bạn",
    "asthma-recommended-article-21-subtitle": "Duy trì không có triệu chứng bằng cách tuân thủ kế hoạch điều trị, hiểu rõ các yếu tố kích phát và nhận biết sớm những thay đổi trong kiểm soát.",
    "asthma-recommended-article-22-title": "Hen suyễn của bạn có được kiểm soát không?",
    "asthma-recommended-article-22-subtitle": "4 câu hỏi để đánh giá xem hen suyễn của bạn có được kiểm soát không. Nếu bạn đang gặp triệu chứng nhiều hơn 2 lần một tuần hoặc nếu bạn thức giấc vào ban đêm do triệu chứng hen suyễn - hen suyễn của bạn không được kiểm soát.",
    "asthma-recommended-article-24-title": "Điều hướng vùng nguy hiểm: Sẵn sàng cho các đợt bùng phát hen suyễn",
    "asthma-recommended-article-24-subtitle": "Nhận biết sớm các triệu chứng nghiêm trọng như ho dữ dội và khó thở, và kích hoạt kế hoạch hành động hen suyễn được điều chỉnh của bạn bao gồm thuốc ngay lập tức.",
    "asthma-recommended-article-25-title": "Kiểm soát hen suyễn của bạn",
    "asthma-recommended-article-25-subtitle": "Khi hen suyễn của bạn cảm thấy không thể kiểm soát được, đã đến lúc đánh giá lại cách tiếp cận của bạn. Các bước cần thực hiện khi hen suyễn của bạn không được kiểm soát.",
    "asthma-recommended-article-32-title": "Ai cần thuốc kiểm soát?",
    "asthma-recommended-article-32-subtitle": "Khám phá vai trò quan trọng của thuốc kiểm soát trong việc duy trì hen suyễn dưới sự kiểm soát.",
    "asthma-recommended-article-33-title": "Tiếp cận thuốc",
    "asthma-recommended-article-33-subtitle": "Khi chi phí là rào cản đối với thuốc, tìm hiểu về thuốc miễn phí hoặc chi phí thấp. Uống thuốc theo chỉ định là quan trọng để duy trì kiểm soát hen suyễn.",
    "asthma-recommended-article-34-title": "Nạp lại thuốc",
    "asthma-recommended-article-34-subtitle": "Luôn cập nhật thuốc hen suyễn của bạn với các chiến lược nạp lại dễ dàng.",
    "asthma-recommended-article-35-title": "Khó nhớ thuốc",
    "asthma-recommended-article-35-subtitle": "Khám phá các chiến lược đơn giản nhưng hiệu quả để nhớ liều hàng ngày của bạn, từ mẹo lưu trữ thông minh đến tận dụng nhắc nhở ứng dụng.",
    "asthma-recommended-article-36-title": "Ống hít nào sử dụng khi nào",
    "asthma-recommended-article-36-subtitle": "Làm chủ quản lý hen suyễn của bạn: Ống hít cứu hộ hoạt động nhanh để giảm triệu chứng trong khi ống hít kiểm soát là phòng ngừa và hoạt động bằng cách giảm viêm, thường bằng cách uống hàng ngày.",
    "asthma-recommended-article-37a-title": "Kỹ thuật ống hít - MDI",
    "asthma-recommended-article-37a-subtitle": "Mẹo kỹ thuật ống hít liều lượng (MDI). Nếu không có kỹ thuật đúng, bạn có thể chỉ nhận được một phần liều lượng.",
    "asthma-recommended-article-37b-title": "Kỹ thuật ống hít - DPI",
    "asthma-recommended-article-37b-subtitle": "Mẹo kỹ thuật ống hít bột khô (DPI). Nếu không có kỹ thuật đúng, bạn có thể chỉ nhận được một phần liều lượng.",
    "asthma-recommended-article-37c-title": "Kỹ thuật ống hít - SMI",
    "asthma-recommended-article-37c-subtitle": "Mẹo kỹ thuật ống hít sương mù mềm (SMI). Nếu không có kỹ thuật đúng, bạn có thể chỉ nhận được một phần liều lượng.",
    "asthma-recommended-article-37d-title": "Kỹ thuật ống hít - máy phun sương",
    "asthma-recommended-article-37d-subtitle": "Mẹo kỹ thuật máy phun sương.",
    "asthma-recommended-article-38-title": "Tại sao tôi nên dùng thuốc kiểm soát?",
    "asthma-recommended-article-38-subtitle": "Hiểu vai trò quan trọng của thuốc kiểm soát và tại sao chúng là nền tảng của kế hoạch quản lý cá nhân hóa của bạn.",
    "asthma-recommended-article-39-title": "Tác dụng phụ của thuốc hen suyễn",
    "asthma-recommended-article-39-subtitle": "Tìm hiểu cách xác định các tác dụng phụ phổ biến và không phổ biến, và các bước đơn giản bạn có thể thực hiện để tránh tác dụng phụ phổ biến - nấm miệng (nhiễm nấm trong miệng của bạn).",
    "asthma-recommended-article-39a-title": "Làm sao tôi biết thuốc hen suyễn của tôi có hiệu quả không?",
    "asthma-recommended-article-39a-subtitle": "Thuốc kiểm soát có thể mất từ vài ngày đến vài tuần để đạt được tác động đầy đủ. Theo dõi các triệu chứng của bạn hàng ngày để xem có cải thiện không và nếu không có, hãy nói chuyện với bác sĩ của bạn.",
    "asthma-recommended-article-41-title": "Yếu tố kích phát bất ngờ",
    "asthma-recommended-article-41-subtitle": "Khám phá các yếu tố kích phát hen suyễn bất ngờ ẩn náu trong cuộc sống hàng ngày của bạn, từ NSAID (như ibuprofen) đến ly rượu vang của bạn. Biết những gì cần tìm kiếm có thể giúp bạn xác định những yếu tố kích phát bất ngờ này.",
    "asthma-recommended-article-42-title": "Hen suyễn và dị ứng theo mùa/phấn hoa",
    "asthma-recommended-article-42-subtitle": "Điều hướng mùa phấn hoa một cách dễ dàng: Xác định các yếu tố kích phát phấn hoa cụ thể của bạn, hiểu mô hình theo mùa của chúng và học cách giảm thiểu tiếp xúc.",
    "asthma-recommended-article-43-title": "Hen suyễn và chất lượng không khí",
    "asthma-recommended-article-43-subtitle": "Hiểu rằng chất lượng không khí kém có thể kích phát hen suyễn. Tìm hiểu cách điều hướng những ngày có AQI cao và ý nghĩa của các mức AQI.",
    "asthma-recommended-article-43a-title": "Hen suyễn và nhiễm trùng đường hô hấp",
    "asthma-recommended-article-43a-subtitle": "Nhiễm trùng đường hô hấp là yếu tố kích phát hen suyễn phổ biến. Cách phòng ngừa chúng và phải làm gì khi chúng xảy ra.",
    "asthma-recommended-article-43b-title": "Hen suyễn và động vật",
    "asthma-recommended-article-43b-subtitle": "Động vật/Thú cưng có thể là yếu tố kích phát hen suyễn. Tìm hiểu về cách chẩn đoán dị ứng động vật/thú cưng và các bước để giảm tác động.",
    "asthma-recommended-article-43c-title": "Hen suyễn và khói",
    "asthma-recommended-article-43c-subtitle": "Cháy rừng và khói thuốc lá có thể kích phát hen suyễn. Tìm hiểu về các bước bạn có thể thực hiện để giảm tiếp xúc của mình.",
    "asthma-recommended-article-43d-title": "Hen suyễn và thời tiết",
    "asthma-recommended-article-43d-subtitle": "Các yếu tố kích phát thời tiết phổ biến là không khí lạnh, không khí nóng và ẩm, và mưa/giông bão. Khám phá lý do tại sao những điều này có thể kích phát hen suyễn.",
    "asthma-recommended-article-43e-title": "Mùi mạnh và hóa chất/đồ dùng vệ sinh",
    "asthma-recommended-article-43e-subtitle": "Khám phá những mùi có thể kích phát hen suyễn của bạn và những điều cần suy nghĩ khi dọn dẹp.",
    "asthma-recommended-article-43f-title": "Hen suyễn và bụi/mạt bụi",
    "asthma-recommended-article-43f-subtitle": "Bụi là yếu tố kích phát hen suyễn phổ biến, nhưng lý do tại sao nó là yếu tố kích phát có thể làm bạn ngạc nhiên!",
    "asthma-recommended-article-43g-title": "Hen suyễn và nấm mốc",
    "asthma-recommended-article-43g-subtitle": "Nấm mốc cần độ ẩm để phát triển, vì vậy thường được tìm thấy ở những nơi ẩm ướt hoặc ướt. Tìm hiểu cách ngăn ngừa nấm mốc trong nhà của bạn.",
    "asthma-recommended-article-43h-title": "Hen suyễn và ợ nóng",
    "asthma-recommended-article-43h-subtitle": "Ợ nóng là gì và nó liên quan gì đến hen suyễn?",
    "blood-type": "Nhóm máu",
    "device-data-month-chart-no-data": "Không có dữ liệu",
    "device-data-month-chart-daily-average": "Trung bình hàng ngày",
    "term-information-not-found-header": "Không tìm thấy thông tin",
    "term-information-not-found-body": "Không thể tìm thấy bất kỳ thông tin nào về chủ đề này",
    "term-information-disclaimer": "<strong>TUYÊN BỐ MIỄN TRỪ TRÁCH NHIỆM:</strong> Thông tin được cung cấp không phải là lời khuyên y tế. Nó giúp bạn hiểu rõ hơn về sức khỏe của mình. Vui lòng liên hệ với nhà cung cấp dịch vụ chăm sóc sức khỏe của bạn nếu bạn có câu hỏi liên quan đến tình trạng y tế của mình.",
    "term-information-view-on-medline": "Xem trên MedlinePlus",
    "type": "Loại",
    "location": "Vị trí",
    "description": "Mô tả",
    "performed-by": "Thực hiện bởi",
    "verified-by": "Xác minh bởi",
    "normal-range": "Phạm vi bình thường",
    "more": "Thêm",
    "procedure": "Thủ thuật",
    "procedures": "Các thủ thuật",
    "lab-report": "Báo cáo xét nghiệm",
    "service-performed": "Dịch vụ đã thực hiện",
    "services-performed": "Các dịch vụ đã thực hiện",
    "device-data-month-chart-minutes": "Phút",
    "device-data-month-chart-sleep": "Giấc ngủ",
    "air-quality": "Chất lượng không khí",
    "air-quality-home": "Chất lượng không khí (Nhà)",
    "air-quality-work": "Chất lượng không khí (Nơi làm việc)",
    "sedentary-time": "Thời gian ít vận động",
    "active-time": "Thời gian hoạt động",
    "lightly-active-time": "Thời gian hoạt động nhẹ",
    "fairly-active-time": "Thời gian hoạt động vừa phải",
    "very-active-time": "Thời gian hoạt động mạnh",
    "breathing-rate": "Tốc độ hô hấp",
    "calories-burned": "Calo đã đốt cháy",
    "elevated-heart-rate-time": "Thời gian nhịp tim tăng cao",
    "fat-burn-heart-rate-time": "Thời gian đốt mỡ",
    "cardio-heart-rate-time": "Thời gian tim mạch",
    "peak-heart-rate-time": "Thời gian đỉnh điểm",
    "floors-climbed": "Số tầng đã leo",
    "heart-rate-variability": "Biến thiên nhịp tim",
    "sleep-time": "Thời gian ngủ",
    "light-sleep-time": "Thời gian ngủ nhẹ",
    "deep-sleep-time": "Thời gian ngủ sâu",
    "rem-sleep-time": "Thời gian ngủ REM",
    "spo2": "SpO2",
    "heart-rate-range": "Phạm vi nhịp tim",
    "max-heart-rate": "Nhịp tim tối đa",
    "core-sleep-time": "Thời gian ngủ chính",
    "in-bed-time": "Thời gian trên giường",
    "stand-time": "Thời gian đứng",
    "walking-heart-rate-average": "Nhịp tim trung bình khi đi bộ",
    "active-energy-burned": "Năng lượng hoạt động đã đốt cháy",
    "number-of-alcoholic-beverages": "Số lượng đồ uống có cồn",
    "active-calories": "Calo hoạt động",
    "resting-calories": "Calo lúc nghỉ",
    "total-calories": "Tổng calo",
    "min-heart-rate": "Nhịp tim tối thiểu",
    "average-heart-rate": "Nhịp tim trung bình",
    "max-stress-level": "Mức độ căng thẳng tối đa",
    "average-stress-level": "Mức độ căng thẳng trung bình",
    "total-stress-time": "Tổng thời gian căng thẳng",
    "low-stress-time": "Thời gian căng thẳng thấp",
    "medium-stress-time": "Thời gian căng thẳng trung bình",
    "high-stress-time": "Thời gian căng thẳng cao",
    "awake-time": "Thời gian thức",
    "sleep-score": "Điểm ngủ",
    "bpm": "nhịp/phút",
    "hours-abbreviation": "giờ",
    "minutes-abbreviation": "phút",
    "points-until-next-badge": "{points} điểm đến huy hiệu tiếp theo",
    "fitbit-wear-time": "Thời gian đeo Fitbit",
    "my-badges": "Huy hiệu của tôi ({badges})",
    "new-badge-title": "Làm tốt lắm!",
    "new-badge-text": "Bạn đã nhận được một huy hiệu mới!",
    "get-badge": "Nhận huy hiệu",
    "glucose-chart-no-data": "Không có chỉ số đường huyết",
    "glucose-stats-range-label": "Phạm vi đường huyết",
    "glucose-stats-avg-label": "Đường huyết trung bình",
    "glucose-stats-steps-label": "Bước",
    "glucose-stats-sleep-label": "Giấc ngủ",
    "stress-level-title": "Căng thẳng tổng thể",
    "stress-level-min-label": "Không căng thẳng",
    "stress-level-max-label": "Cực kỳ căng thẳng",
    "meal-type-meal": "Bữa ăn",
    "meal-type-snack": "Bữa ăn nhẹ",
    "meal-type-drink": "Đồ uống",
    "meal-log-title": "Nhật ký bữa ăn",
    "meal-log-no-data": "Không có bữa ăn nào được ghi lại",
    "meal-editor-time-input-label": "Thời gian",
    "meal-editor-description-input-label": "Mô tả",
    "meal-editor-description-optional": "Tùy chọn",
    "meal-editor-duplicate-timestamp-error": "Hai bữa ăn không thể có cùng thời gian.",
    "meal-editor-add-image": "Thêm hình ảnh",
    "meal-editor-image-upload-error": "Đã xảy ra lỗi khi tải lên hình ảnh đã chọn. Vui lòng thử lại, sử dụng hình ảnh khác, hoặc xóa hình ảnh để lưu.",
    "glucose-view-title": "Theo dõi đường huyết",
    "ai-assistant-loading": "Đang tương tác với dữ liệu của bạn...",
    "ai-assistant-suggestion-avg-weekly-heart-rate": "Nhịp tim trung bình của tôi trong tuần qua là bao nhiêu?",
    "ai-assistant-suggestion-highest-heart-rate-week": "Nhịp tim cao nhất của tôi trong tuần này là bao nhiêu?",
    "ai-assistant-suggestion-graph-daily-steps-21-days": "Tạo biểu đồ số bước đi hàng ngày của tôi trong 21 ngày qua",
    "ai-assistant-suggestion-weekly-workouts-average-month": "Trung bình mỗi tuần tôi tập luyện bao nhiêu lần trong tháng này?",
    "ai-assistant-suggestion-avg-monthly-blood-pressure": "Huyết áp trung bình của tôi trong tháng qua là bao nhiêu?",
    "ai-assistant-suggestion-daily-active-minutes-month": "Số phút hoạt động trung bình hàng ngày của tôi trong tháng này là bao nhiêu?",
    "ai-assistant-suggestion-resting-heart-rate-change-month": "Nhịp tim lúc nghỉ của tôi đã thay đổi như thế nào trong tháng qua?",
    "ai-assistant-suggestion-stand-ups-yesterday": "Hôm qua tôi đứng dậy bao nhiêu lần?",
    "ai-assistant-suggestion-graph-heart-rate-trends-workouts": "Bạn có thể vẽ biểu đồ xu hướng nhịp tim của tôi trong các buổi tập luyện tuần này không?",
    "ai-assistant-suggestion-sleep-7-days": "Giấc ngủ của tôi trong 7 ngày qua như thế nào?",
    "ai-assistant-suggestion-fall-asleep-time-2-weeks": "Tôi thường ngủ vào thời gian nào trong 2 tuần qua?",
    "ai-assistant-suggestion-sleep-quality-change-month": "Chất lượng giấc ngủ của tôi đã thay đổi như thế nào trong tháng qua?",
    "ai-assistant-suggestion-last-tetanus-vaccine": "Lần tiêm vắc-xin uốn ván gần đây nhất của tôi là khi nào?",
    "ai-assistant-suggestion-last-blood-test-lab-work": "Lần xét nghiệm máu hoặc xét nghiệm gần đây nhất của tôi là khi nào?",
    "ai-assistant-suggestion-abnormal-lab-results": "Tôi có kết quả xét nghiệm bất thường nào không?",
    "ai-assistant-suggestion-last-cbc-test": "Lần xét nghiệm công thức máu toàn bộ (CBC) gần đây nhất của tôi là khi nào?",
    "ai-assistant-suggestion-glucose-a1c-levels-last-test": "Mức đường huyết và A1c của tôi trong xét nghiệm gần đây nhất là bao nhiêu?",
    "ai-assistant-suggestion-graph-cholesterol-trends": "Bạn có thể cho tôi xem biểu đồ về sự thay đổi mức cholesterol của tôi theo thời gian không?",
    "ai-assistant-suggestion-last-metabolic-panel": "Lần xét nghiệm bảng điều khiển trao đổi chất gần đây nhất của tôi là khi nào?",
    "ai-assistant-suggestion-hemoglobin-levels-trend": "Xu hướng mức hemoglobin của tôi như thế nào?",
    "ai-assistant-suggestion-show-files": "Hiển thị tệp của tôi.",
    "ai-assistant-suggestion-save-graph-to-files": "Lưu biểu đồ vào tệp của tôi",
    "mindful-minutes": "Phút chánh niệm",
    "therapy-minutes": "Phút trị liệu",
    "insight-matrix-no-comparison-data": "Không có loại dữ liệu so sánh nào được cấu hình.",
    "allergylist-reactions": "Phản ứng",
    "points-abbreviation": "đ",
    "no-data": "Không có dữ liệu",
    "no-data-yet": "Chưa có dữ liệu",
    "bp-low": "Thấp",
    "bp-normal": "Bình thường",
    "bp-elevated": "Tăng cao",
    "bp-stage1": "Giai đoạn 1",
    "bp-stage2": "Giai đoạn 2",
    "bp-crisis": "Khủng hoảng",
    "bp-unknown": "Không xác định",
    "device-not-enabled": "@@DEVICE@@ không được kích hoạt cho dự án này.",
    "download-pdf-report": "Tải xuống báo cáo PDF",
    "connect-to-device": "Kết nối với @@DEVICE@@",
    "symptoms-and-treatments": "Triệu chứng & Điều trị",
    "subsequent-evaluation-note": "Ghi chú đánh giá tiếp theo",
    "summary": "Tóm tắt",
    "device-activity": "Hoạt động thiết bị",
    "daily": "Hàng ngày",
    "weekly": "Hàng tuần",
    "monthly": "Hàng tháng",
    "bonus": "Thưởng",
    "syncing-data": "Đang đồng bộ dữ liệu...",
    "health-connect-phr-sync-title": "Đồng bộ với Health Connect",
    "health-connect-phr-sync-prompt": "Chọn hồ sơ sức khỏe để đọc từ và ghi vào Health Connect"
};

export default strings;


