import { SurveyAnswer } from "@careevolution/mydatahelps-js";
import { addDays, endOfDay, startOfDay, startOfToday } from "date-fns";
import { v4 as uuid } from "uuid";

const today = new Date();
const participantID = uuid();

export const previewSeverityData: SurveyAnswer[] = [
    {
        id: "12345",
        participantID: participantID,
        surveyResultID: "1",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["severe"],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "123456",
        participantID: participantID,
        surveyResultID: "1",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityDate",
        answers: [startOfToday().toISOString()],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "123452",
        participantID: participantID,
        surveyResultID: "21",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["severity3"],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "12223456",
        participantID: participantID,
        surveyResultID: "21",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityDate",
        answers: [startOfDay(addDays(today, -1)).toISOString()],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "123457",
        participantID: participantID,
        surveyResultID: "2",
        surveyID: "1",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["moderate"],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "123458",
        participantID: participantID,
        surveyResultID: "2",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityDate",
        answers: [startOfDay(addDays(today, -2)).toISOString()],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "1234573",
        participantID: participantID,
        surveyResultID: "3",
        surveyID: "1",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["severity2"],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "1234583",
        participantID: participantID,
        surveyResultID: "3",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityDate",
        answers: [startOfDay(addDays(today, -3)).toISOString()],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "14234573",
        participantID: participantID,
        surveyResultID: "4",
        surveyID: "1",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["moderate"],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "12345834",
        participantID: participantID,
        surveyResultID: "4",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityDate",
        answers: [startOfDay(addDays(today, -4)).toISOString()],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "142345736",
        participantID: participantID,
        surveyResultID: "5",
        surveyID: "1",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["mild"],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "1234583466",
        participantID: participantID,
        surveyResultID: "5",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityDate",
        answers: [startOfDay(addDays(today, -5)).toISOString()],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "1423457376",
        participantID: participantID,
        surveyResultID: "6",
        surveyID: "1",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["severity1"],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "1234583466",
        participantID: participantID,
        surveyResultID: "6",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityDate",
        answers: [startOfDay(addDays(today, -6)).toISOString()],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "12374597",
        participantID: participantID,
        surveyResultID: "7",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -7)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["mild"],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "123874598",
        participantID: participantID,
        surveyResultID: "8",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -8)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["severe"],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "1238745998",
        participantID: participantID,
        surveyResultID: "9",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: endOfDay(addDays(today, -8)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["mild"],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "10234583466",
        participantID: participantID,
        surveyResultID: "10",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityDate",
        answers: [endOfDay(addDays(today, -9)).toISOString()],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "1237459710",
        participantID: participantID,
        surveyResultID: "10",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["mild"],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "10234583466",
        participantID: participantID,
        surveyResultID: "11",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityDate",
        answers: [startOfDay(addDays(today, -9)).toISOString()],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "1237459710",
        participantID: participantID,
        surveyResultID: "11",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["severe"],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "12387459988",
        participantID: participantID,
        surveyResultID: "12",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: endOfDay(addDays(today, -10)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["severe"],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "102345834898",
        participantID: participantID,
        surveyResultID: "12",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: endOfDay(addDays(today, -10)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityDate",
        answers: [endOfDay(addDays(today, -10)).toISOString()],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "123745971013",
        participantID: participantID,
        surveyResultID: "13",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -10)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["moderate"],
        insertedDate: Date.now.toString(),
        type: "Question"
    },
    {
        id: "1023458346613",
        participantID: participantID,
        surveyResultID: "13",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -10)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityDate",
        answers: [endOfDay(addDays(today, -10)).toISOString()],
        insertedDate: Date.now.toString(),
        type: "Question"
    }
];