import { SurveyAnswer } from "@careevolution/mydatahelps-js";
import { addDays, startOfDay } from "date-fns";

var today = new Date();

export const previewSeverityData : SurveyAnswer[] = [
    {   id: "12345",
        surveyResultID: "1",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["mild"],
        insertedDate: Date.now.toString()
    },
    {   id: "123456",
        surveyResultID: "1",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: today.toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "swellingDate",
        answers: [today.toISOString()],
        insertedDate: Date.now.toString()
    },
    {   id: "123457",
        surveyResultID: "2",
        surveyID: "1",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -1)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["mild"],
        insertedDate: Date.now.toString()
    },
    {   id: "123458",
        surveyResultID: "2",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -1)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "swellingDate",
        answers: [startOfDay(addDays(today, -1)).toISOString()],
        insertedDate: Date.now.toString()
    },
    {   id: "123459",
        surveyResultID: "3",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -2)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["severity1"],
        insertedDate: Date.now.toString()
    },
    {   
        id: "1234567",
        surveyResultID: "3",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -2)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "swellingDate",
        answers: [startOfDay(addDays(today, -2)).toISOString()],
        insertedDate: Date.now.toString()
    },
    {   id: "123468",
        surveyResultID: "3",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -3)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["severity3"],
        insertedDate: Date.now.toString()
    },
    {   id: "12369",
        surveyResultID: "3",
        surveyID: "1",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -3)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "swellingDate",
        answers: [startOfDay(addDays(today, -3)).toISOString(),],
        insertedDate: Date.now.toString()
    },
    {   id: "123479",
        surveyResultID: "4",
        surveyID: "1",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -4)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["severe"],
        insertedDate: Date.now.toString()
    },
    {   id: "123478",
        surveyResultID: "4",
        surveyID: "1",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -4)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "swellingDate",
        answers: [startOfDay(addDays(today, -4)).toISOString()],
        insertedDate: Date.now.toString()
    },
    {   
        id: "123477",
        surveyResultID: "5",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -5)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["severe"],
        insertedDate: Date.now.toString()
    },
    {   
        id: "123475",
        surveyResultID: "5",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -5)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "swellingDate",
        answers: [startOfDay(addDays(today, -5)).toISOString()],
        insertedDate: Date.now.toString()
    },
    {   id: "123474",
        surveyResultID: "6",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -6)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["moderate"],
        insertedDate: Date.now.toString()
    },
    {   id: "123473",
        surveyResultID: "6",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -6)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "swellingDate",
        answers: [startOfDay(addDays(today, -6)).toISOString()],
        insertedDate: Date.now.toString()
    },
    {   id: "123472",
        surveyResultID: "7",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -7)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["severity2"],
        insertedDate: Date.now.toString()
    },
    {   id: "123471",
        surveyResultID: "7",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -7)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "swellingDate",
        answers: [startOfDay(addDays(today, -7)).toISOString()],
        insertedDate: Date.now.toString()
    },
    {   id: "123489",
        surveyResultID: "8",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -8)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "severityValue",
        answers: ["moderate"],
        insertedDate: Date.now.toString()
    },
    {   id: "123488",
        surveyResultID: "8",
        surveyID: "2",
        surveyVersion: 1,
        surveyName: "Survey 1",
        surveyDisplayName: "test",
        date: startOfDay(addDays(today, -8)).toISOString(),
        stepIdentifier: "1",
        resultIdentifier: "swellingDate",
        answers: [startOfDay(addDays(today, -8)).toISOString()],
        insertedDate: Date.now.toString()
    }
];