name: MDH UI Build and Test Workflow

on:
  push:
    branches:
      - '**' # Match any branch
    paths-ignore:
      - 'amplify.yml'          # Exclude the main Amplify configuration file
      - 'customHttp.yml'       # Exclude the custom HTTP configuration file
      - '*.md'                 # Markdown files
      - '.vscode'               # Exclude the VSCode configuration folder
  pull_request:
    branches:
      - '**' # Match any branch
    paths-ignore:
      - 'amplify.yml'          # Exclude the main Amplify configuration file
      - 'customHttp.yml'       # Exclude the custom HTTP configuration file
      - '*.md'                 # Markdown files
      - '.vscode'               # Exclude the VSCode configuration folder

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: npm ci
        run: npm ci
        continue-on-error: false
      - name: Run Build
        run: npm run rollup
      - name: build
        run: npm run build-storybook
        continue-on-error: false
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: storybook-build
          path: storybook-static
          retention-days: 5
      - name: test
        run: npm run test
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: coverage/
          retention-days: 5

  notify-on-failure:
    # This job only runs if the previous build-and-test job fails
    needs: build-and-test
    if: failure()
    runs-on: ubuntu-latest

    steps:
      # Step 1: Send Slack notification on failure
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "GitHub Action *${{ github.workflow }}* failed.\nFailing commit details: \n*Author:* ${{ github.event.head_commit.author.name }}\n*Commit Hash:* ${{ github.sha }}\n*Branch:* ${{ github.ref }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Github Workflow *${{ github.workflow }}* failed\n\n*Failing commit details:*\n• *Author:* ${{ github.event.head_commit.author.name }}\n• *Commit Hash:* ${{ github.sha }}\n• *Branch:* ${{ github.ref }}\n• View commit:* ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}