name: Publish to npmjs and ProGet (snapshots / prereleases)

on:
  workflow_dispatch:
  push:
    tags:
      - "*-*"

permissions:
  id-token: write
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install Dependencies
        run: npm ci
      - name: Run Build
        run: npm run rollup
      - name: Deploy to npmjs
        run: |
          npm config set @careevolution:registry=https://registry.npmjs.org/
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPMJS_TOKEN }}
          npm publish --tag next --access public
      - name: Deploy to ProGet
        run: |
          echo "@careevolution:registry=https://proget.careevolution.com/npm/npm/" > .npmrc
          npm config set @careevolution:registry=https://proget.careevolution.com/npm/npm/
          npm config set //proget.careevolution.com/npm/npm/:_authToken ${{ secrets.PROGET_TOKEN }}
          npm publish --tag next